%%%% regsvc.erl
%%%%
%%%% TODO:
%%%%    + generate spontaneous messages, probably modeled as a timeout

-module(regsvc).
-export([ping/2, get/2, set/4, bulk_get/3]).  % client interface
-export([start_link/0, stop/1]).  % server interface
-export([init/1, handle_call/2, handle_cast/2]).  % hls_gs callbacks

-behavior(hls_gs).
-hls_tags([set, get, ping, bulk_get, ack, read, bulk_read]).  % public wire payloads
-compile({parse_transform, hls_pack}).  % auto-defines un/pack

-define(REGISTER_COUNT, 16).
-define(MAX_PAYLOAD, 3).

%%%
%%% Types
%%%

-record(set, {
    register = hls_type:zero() :: hls_nums:u32(),
    value = hls_type:zero() :: hls_nums:u32(),
    mask = hls_type:zero() :: hls_nums:u32()
}).

-record(get, {
    register = hls_type:zero() :: hls_nums:u32()
}).

-record(ping, {
    value = hls_type:zero() :: hls_nums:u32()
}).

-record(bulk_get, {
    start = hls_type:zero() :: hls_nums:u32(),
    count = hls_type:zero() :: hls_nums:u32()
}).

-record(ack, {
    value = hls_type:zero() :: hls_nums:u32()
}).

-record(read, {
    value = hls_type:zero() :: hls_nums:u32()
}).

-record(bulk_read, {
    values = hls_type:zero() ::
        hls_lists:list(hls_nums:u32(), ?MAX_PAYLOAD)
}).

-record(state, {
    registers = hls_type:zero() ::
        hls_lists:list(hls_nums:u32(), ?REGISTER_COUNT)
}).

%%%
%%% Client interface
%%%

ping(PID, Value) ->
    #ack{value = Reply} = gen_server:call(PID, #ping{value = Value}),
    Reply.

get(PID, Register) ->
    #read{value = Value} = gen_server:call(PID, #get{register = Register}),
    Value.

set(PID, Register, Value, Mask) ->
    gen_server:cast(PID, {set, Register, Value, Mask}).

bulk_get(PID, Start, Count) ->
    #bulk_read{values = MaxPayload} = gen_server:call(PID, #bulk_get{start = Start, count = Count}),
    lists:sublist(MaxPayload, 1, Count).

%%%
%%% Server management
%%%

start_link() ->
    hls_gs:start_link(?MODULE, []).

stop(PID) ->
    hls_gs:stop(PID).

%%%
%%% gen_server behavior
%%%

-spec init(any()) -> #state{}.  % obligatory type signature
init([]) ->
    #state{}.

handle_cast(#set{mask = Mask}, State) when Mask =:= 0 ->
    {noreply, State};
handle_cast(#set{register = Register, value = Value, mask = Mask}, State)
        when Register < ?REGISTER_COUNT ->
    OldValue = hls_lists:nth(Register + 1, State#state.registers),
    NewValue = (OldValue band bnot Mask) bor (Value band Mask),
    NewRegisters = hls_lists:set(Register + 1, State#state.registers, NewValue),
    {noreply, State#state{registers = NewRegisters}}.

handle_call(#ping{value = Value}, State) ->
    {reply, #ack{value = Value}, State};
handle_call(#get{register = Register}, State)
        when Register < ?REGISTER_COUNT ->
    Value = hls_lists:nth(Register + 1, State#state.registers),
    {reply, #read{value = Value}, State};
handle_call(#bulk_get{count = 0}, State) ->
    {reply, #bulk_read{}, State};
handle_call(#bulk_get{start = Start, count = Count}, State)
        when Count > 0,
             Count =< ?MAX_PAYLOAD,
             Start + Count =< ?REGISTER_COUNT ->
    Sublist = hls_lists:sublist(
        hls_lists:list(hls_nums:u32(), ?REGISTER_COUNT),
        State#state.registers, Start + 1, Count
    ),
    Trim = hls_lists:array_slice(
        hls_lists:list(hls_nums:u32(), ?REGISTER_COUNT),
        Sublist,
        1, ?MAX_PAYLOAD
    ),
    {reply, #bulk_read{values = Trim}, State}.

%
%
% % % % sample functions autogenerated by the parse transform
%
%
% pack(Record = #set{}) ->
%     <<(Record#set.register):32/little-unsigned-integer,
%       (Record#set.value):32/little-unsigned-integer,
%       (Record#set.mask):32/little-unsigned-integer>>;
% pack(Record = #get{}) ->
%     <<(Record#get.register):32/little-unsigned-integer>>;
% pack(Record = #ping{}) ->
%     <<(Record#ping.value):32/little-unsigned-integer>>;
% pack(Record = #bulk_get{}) ->
%     <<(Record#bulk_get.start):32/little-unsigned-integer,
%       (Record#bulk_get.count):32/little-unsigned-integer>>;
% pack(Record = #ack{}) ->
%     <<(Record#ack.value):32/little-unsigned-integer>>;
% pack(Record = #read{}) ->
%     <<(Record#read.value):32/little-unsigned-integer>>.

% unpack(set, Binary) ->
%     <<Register:32/little-unsigned-integer,
%       Value:32/little-unsigned-integer,
%       Mask:32/little-unsigned-integer,
%       Rest/binary>> =
%         Binary,
%     {#set{register = Register, value = Value, mask = Mask}, Rest};
% unpack(get, Binary) ->
%     <<Register:32/little-unsigned-integer,Rest/binary>> = Binary,
%     {#get{register = Register}, Rest};
% unpack(ping, Binary) ->
%     <<Value:32/little-unsigned-integer,Rest/binary>> = Binary,
%     {#ping{value = Value}, Rest};
% unpack(bulk_get, Binary) ->
%     <<Start:32/little-unsigned-integer,
%       Count:32/little-unsigned-integer,
%       Rest/binary>> =
%         Binary,
%     {#bulk_get{start = Start, count = Count}, Rest};
% unpack(ack, Binary) ->
%     <<Value:32/little-unsigned-integer,Rest/binary>> = Binary,
%     {#ack{value = Value}, Rest};
% unpack(read, Binary) ->
%     <<Value:32/little-unsigned-integer,Rest/binary>> = Binary,
%     {#read{value = Value}, Rest}.

% pack_tag(state) ->
%     1;
% pack_tag(set) ->
%     2;
% pack_tag(get) ->
%     3;
% pack_tag(ping) ->
%     4;
% pack_tag(bulk_get) ->
%     5;
% pack_tag(ack) ->
%     6;
% pack_tag(read) ->
%     7.

% unpack_tag(1) ->
%     state;
% unpack_tag(2) ->
%     set;
% unpack_tag(3) ->
%     get;
% unpack_tag(4) ->
%     ping;
% unpack_tag(5) ->
%     bulk_get;
% unpack_tag(6) ->
%     ack;
% unpack_tag(7) ->
%     read.
