// src/examples/phi_decoder/phenom_syndrome_cell.erl.x
// This file is auto-generated by xls_parse. Manual changes will be
// overwritten the next time it is generated.

import axis;

const MAILBOX_CAPACITY = u8:5;

pub enum Tag : u8 {
  NONE = u8:0,
  ERROR = u8:1,
  SYNDROME = u8:2,
  PHI = u8:3,
  ANYON_MOVE = u8:4,
  PHI0 = u8:5,
  PHENOM_CONFIG = u8:6,
  PHENOM_REQUEST = u8:7,
  PHENOM_QUERY = u8:8,
  PHENOM_DATA = u8:9,
  PHENOM_ANYON = u8:10,
  PHI_CORRECTION = u8:11,
}

enum Phase : u8 {
  CONFIGURING = u8:0,
  WAITING = u8:1,
  COLLECTING = u8:2,
  ANNOUNCING = u8:3,
}

enum Directive : u2 {
  CONSUME = u2:0,
  POSTPONE = u2:1,
  FAIL = u2:2,
}

struct Phi {
  epoch : u32,
  values : u32[2],
}

fn phi_from_bits<N: u32>(raw: bits[N]) -> Phi {
  Phi {
    epoch: raw[0:32] as u32,
    values: raw[32:96] as u32[2],
  }
}

fn bits_from_phi(s: Phi) -> bits[bit_count<Phi>()] {
  (s.values as bits[64]) ++ (s.epoch as bits[32]) ++  zero!<bits[0]>()
}

struct Anyonmove {
  step : u32,
  present : u32,
}

fn anyonmove_from_bits<N: u32>(raw: bits[N]) -> Anyonmove {
  Anyonmove {
    step: raw[0:32] as u32,
    present: raw[32:64] as u32,
  }
}

fn bits_from_anyonmove(s: Anyonmove) -> bits[bit_count<Anyonmove>()] {
  (s.present as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phi0 {
  step : u32,
  source : u32,
  value : u32,
}

fn phi0_from_bits<N: u32>(raw: bits[N]) -> Phi0 {
  Phi0 {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
    value: raw[64:96] as u32,
  }
}

fn bits_from_phi0(s: Phi0) -> bits[bit_count<Phi0>()] {
  (s.value as bits[32]) ++ (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phenomconfig {
  seed : u32,
  threshold : u32,
  x : u16,
  y : u16,
}

fn phenomconfig_from_bits<N: u32>(raw: bits[N]) -> Phenomconfig {
  Phenomconfig {
    seed: raw[0:32] as u32,
    threshold: raw[32:64] as u32,
    x: raw[64:80] as u16,
    y: raw[80:96] as u16,
  }
}

fn bits_from_phenomconfig(s: Phenomconfig) -> bits[bit_count<Phenomconfig>()] {
  (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.threshold as bits[32]) ++ (s.seed as bits[32]) ++  zero!<bits[0]>()
}

struct Phenomrequest {
  step : u32,
}

fn phenomrequest_from_bits<N: u32>(raw: bits[N]) -> Phenomrequest {
  Phenomrequest {
    step: raw[0:32] as u32,
  }
}

fn bits_from_phenomrequest(s: Phenomrequest) -> bits[bit_count<Phenomrequest>()] {
  (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phenomquery {
  step : u32,
  source : u32,
}

fn phenomquery_from_bits<N: u32>(raw: bits[N]) -> Phenomquery {
  Phenomquery {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
  }
}

fn bits_from_phenomquery(s: Phenomquery) -> bits[bit_count<Phenomquery>()] {
  (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phenomdata {
  step : u32,
  source : u32,
  present : u32,
}

fn phenomdata_from_bits<N: u32>(raw: bits[N]) -> Phenomdata {
  Phenomdata {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
    present: raw[64:96] as u32,
  }
}

fn bits_from_phenomdata(s: Phenomdata) -> bits[bit_count<Phenomdata>()] {
  (s.present as bits[32]) ++ (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phenomanyon {
  step : u32,
  present : u32,
  x : u16,
  y : u16,
}

fn phenomanyon_from_bits<N: u32>(raw: bits[N]) -> Phenomanyon {
  Phenomanyon {
    step: raw[0:32] as u32,
    present: raw[32:64] as u32,
    x: raw[64:80] as u16,
    y: raw[80:96] as u16,
  }
}

fn bits_from_phenomanyon(s: Phenomanyon) -> bits[bit_count<Phenomanyon>()] {
  (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.present as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Phicorrection {
  step : u32,
  x : u16,
  y : u16,
  direction : u32,
}

fn phicorrection_from_bits<N: u32>(raw: bits[N]) -> Phicorrection {
  Phicorrection {
    step: raw[0:32] as u32,
    x: raw[32:48] as u16,
    y: raw[48:64] as u16,
    direction: raw[64:96] as u32,
  }
}

fn bits_from_phicorrection(s: Phicorrection) -> bits[bit_count<Phicorrection>()] {
  (s.direction as bits[32]) ++ (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

struct Syndrome {
  step : u32,
  seen_sources : u32,
  data_parity : u32,
  previous_measurement : u32,
  announcement : u32,
  random_state : u32,
  threshold : u32,
  x : u16,
  y : u16,
}

fn syndrome_from_bits<N: u32>(raw: bits[N]) -> Syndrome {
  Syndrome {
    step: raw[0:32] as u32,
    seen_sources: raw[32:64] as u32,
    data_parity: raw[64:96] as u32,
    previous_measurement: raw[96:128] as u32,
    announcement: raw[128:160] as u32,
    random_state: raw[160:192] as u32,
    threshold: raw[192:224] as u32,
    x: raw[224:240] as u16,
    y: raw[240:256] as u16,
  }
}

fn bits_from_syndrome(s: Syndrome) -> bits[bit_count<Syndrome>()] {
  (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.threshold as bits[32]) ++ (s.random_state as bits[32]) ++ (s.announcement as bits[32]) ++ (s.previous_measurement as bits[32]) ++ (s.data_parity as bits[32]) ++ (s.seen_sources as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub enum OutputPort : u8 {
  NORTH = u8:0,
  EAST = u8:1,
  WEST = u8:2,
  SOUTH = u8:3,
  PHI = u8:4,
}

pub struct Egress {
  port: OutputPort,
  frame: axis::Frame,
}

pub const EGRESS_DEPTH = u32:4;

struct EntryEffects {
  count: u8,
  valid: bool[5],
  values: Egress[5],
}

struct MailboxSlot {
  postponed: u1,
  frame: axis::Frame,
}

struct Machine {
  phase: Phase,
  entered_from: Phase,
  data: Syndrome,
  slots: MailboxSlot[5],
  occupied: u8,
  enter_pending: u1,
  entry_effect_index: u8,
  // Reserves one queue slot for the frame being assembled.
  admission_pending: u1,
  // A failed service ignores input until reset.
  failed: u1,
}

fn initial_machine() -> Machine {
let _0 = Syndrome {
  ..zero!<Syndrome>()
};
let _1 = (Tag::SYNDROME, _0);
let _2 = (Phase::CONFIGURING, _1, );
let _3 = if (bool:false) {
    zero!<Machine>()
} else {
    Machine {
  phase: _2.0,
  entered_from: _2.0,
  data: _2.1.1,
  enter_pending: u1:1,
  ..zero!<Machine>()
}
};
  _3
}

fn enter(old_phase: Phase, phase: Phase, data: Syndrome) -> (Syndrome, EntryEffects) {
  match phase {
    Phase::CONFIGURING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _0
      };
      (entered_data, EntryEffects {
        count: u8:0,
        valid: [
          bool:false,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
    Phase::WAITING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _0
      };
      (entered_data, EntryEffects {
        count: u8:0,
        valid: [
          bool:false,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
    Phase::COLLECTING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _3
      };
      let effect_0_valid = {
        bool:true
      };
      let effect_0 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 8,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_1_valid = {
        bool:true
      };
      let effect_1 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 4,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_2_valid = {
        bool:true
      };
      let effect_2 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 2,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_3_valid = {
        bool:true
      };
      let effect_3 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 1,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      (entered_data, EntryEffects {
        count: u8:4,
        valid: [
          effect_0_valid,
          effect_1_valid,
          effect_2_valid,
          effect_3_valid,
          bool:false,
        ],
        values: [
          Egress { port: OutputPort::NORTH, frame: effect_0 },
          Egress { port: OutputPort::EAST, frame: effect_1 },
          Egress { port: OutputPort::WEST, frame: effect_2 },
          Egress { port: OutputPort::SOUTH, frame: effect_3 },
          zero!<Egress>(),
        ],
      })
    },
    Phase::ANNOUNCING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Syndrome_1.1.announcement;
        let _2 = Syndrome_1.1.x;
        let _3 = Syndrome_1.1.y;
        let _4 = Phenomanyon {
          step: _0,
          present: _1,
          x: _2,
          y: _3,
          ..zero!<Phenomanyon>()
        };
        let _5 = (Tag::PHENOM_ANYON, _4, bits_from_phenomanyon(_4));
        let Anyon_1 = _5;
        let _6 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _6
      };
      let effect_0_valid = {
        bool:true
      };
      let effect_0 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Syndrome_1.1.announcement;
        let _2 = Syndrome_1.1.x;
        let _3 = Syndrome_1.1.y;
        let _4 = Phenomanyon {
          step: _0,
          present: _1,
          x: _2,
          y: _3,
          ..zero!<Phenomanyon>()
        };
        let _5 = (Tag::PHENOM_ANYON, _4, bits_from_phenomanyon(_4));
        let Anyon_1 = _5;
        let _6 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(Anyon_1.0 as u8, Anyon_1.2)
        };
        _6
      };
      (entered_data, EntryEffects {
        count: u8:1,
        valid: [
          effect_0_valid,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          Egress { port: OutputPort::PHI, frame: effect_0 },
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
  }
}

fn dispatch(frame: axis::Frame, phase: Phase, data: Syndrome) -> (Phase, Syndrome, Directive, u1) {
  match frame.header.op as Tag {
    Tag::PHI => {
      let message = phi_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::ANYON_MOVE => {
      let message = anyonmove_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI0 => {
      let message = phi0_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_CONFIG => {
      let message = phenomconfig_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Seed_1 = message.seed;
          let Xls_clause_1_Threshold_1 = message.threshold;
          let Xls_clause_1_X_1 = message.x;
          let Xls_clause_1_Y_1 = message.y;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let _0 = Xls_clause_1_Seed_1 > 0;
          let _14 = if _0 {
            let _1 = Xls_clause_1_Seed_1 <= 4294967295;
            let _13 = if _1 {
              let _2 = Xls_clause_1_Threshold_1 >= 0;
              let _12 = if _2 {
                let _3 = Xls_clause_1_Threshold_1 <= 4294967295;
                let _11 = if _3 {
                  let _4 = Xls_clause_1_X_1 >= 0;
                  let _10 = if _4 {
                    let _5 = Xls_clause_1_X_1 <= 65535;
                    let _9 = if _5 {
                      let _6 = Xls_clause_1_Y_1 >= 0;
                      let _8 = if _6 {
                        let _7 = Xls_clause_1_Y_1 <= 65535;
                        (_7, bool:false)
                      } else {
                        (bool:0, bool:false)
                      };
                      let case_match_1_1 = bool:false;
                      let case_match_1_2 = _8.1;
                      (_8.0, (case_match_1_1 != case_match_1_2) || bool:false)
                    } else {
                      (bool:0, bool:false)
                    };
                    let case_match_2_1 = bool:false;
                    let case_match_2_2 = _9.1;
                    (_9.0, (case_match_2_1 != case_match_2_2) || bool:false)
                  } else {
                    (bool:0, bool:false)
                  };
                  let case_match_3_1 = bool:false;
                  let case_match_3_2 = _10.1;
                  (_10.0, (case_match_3_1 != case_match_3_2) || bool:false)
                } else {
                  (bool:0, bool:false)
                };
                let case_match_4_1 = bool:false;
                let case_match_4_2 = _11.1;
                (_11.0, (case_match_4_1 != case_match_4_2) || bool:false)
              } else {
                (bool:0, bool:false)
              };
              let case_match_5_1 = bool:false;
              let case_match_5_2 = _12.1;
              (_12.0, (case_match_5_1 != case_match_5_2) || bool:false)
            } else {
              (bool:0, bool:false)
            };
            let case_match_6_1 = bool:false;
            let case_match_6_2 = _13.1;
            (_13.0, (case_match_6_1 != case_match_6_2) || bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_7_1 = bool:false;
          let case_match_7_2 = _14.1;
          if _14.0 {
            let _15 = Syndrome {
              random_state: Xls_clause_1_Seed_1,
              threshold: Xls_clause_1_Threshold_1,
              x: Xls_clause_1_X_1,
              y: Xls_clause_1_Y_1,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _16 = (Tag::SYNDROME, _15);
            let Xls_clause_1_Configured_1 = _16;
            let _17 = (Phase::WAITING, Xls_clause_1_Configured_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_17.0, _17.1.1, _17.2, _17.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::CONFIGURING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::WAITING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::COLLECTING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::ANNOUNCING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_REQUEST => {
      let message = phenomrequest_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = (Phase::CONFIGURING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::CONFIGURING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = Syndrome {
              seen_sources: 0,
              data_parity: 0,
              announcement: 0,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _1 = (Tag::SYNDROME, _0);
            let Xls_clause_1_Collecting_1 = _1;
            let _2 = (Phase::COLLECTING, Xls_clause_1_Collecting_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_2.0, _2.1.1, _2.2, _2.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::WAITING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = (Phase::COLLECTING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_3.0, _3.1.1, _3.2, _3.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::COLLECTING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = Syndrome {
              step: Xls_clause_1_NextStep_1,
              seen_sources: 0,
              data_parity: 0,
              announcement: 0,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _4 = (Tag::SYNDROME, _3);
            let Xls_clause_1_Collecting_1 = _4;
            let _5 = (Phase::COLLECTING, Xls_clause_1_Collecting_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_5.0, _5.1.1, _5.2, _5.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::ANNOUNCING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_QUERY => {
      let message = phenomquery_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_DATA => {
      let message = phenomdata_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::CONFIGURING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = (Phase::WAITING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::WAITING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Source_1 = message.source;
          let Xls_clause_1_Present_1 = message.present;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Seen_1 = data.seen_sources;
          let Xls_clause_1_Parity_1 = data.data_parity;
          let Xls_clause_1_PreviousMeasurement_1 = data.previous_measurement;
          let Xls_clause_1_RandomState_1 = data.random_state;
          let Xls_clause_1_Threshold_1 = data.threshold;
          let _12 = if Xls_clause_1_Step_1 == data.step {
            let _0 = Xls_clause_1_Source_1 == 1;
            let _6 = if _0 {
              (bool:1, bool:false)
            } else {
              let _1 = Xls_clause_1_Source_1 == 2;
              let _5 = if _1 {
                (bool:1, bool:false)
              } else {
                let _2 = Xls_clause_1_Source_1 == 4;
                let _4 = if _2 {
                  (bool:1, bool:false)
                } else {
                  let _3 = Xls_clause_1_Source_1 == 8;
                  (_3, bool:false)
                };
                let case_match_1_1 = bool:false;
                let case_match_1_2 = _4.1;
                (_4.0, (case_match_1_1 != case_match_1_2) || bool:false)
              };
              let case_match_2_1 = bool:false;
              let case_match_2_2 = _5.1;
              (_5.0, (case_match_2_1 != case_match_2_2) || bool:false)
            };
            let case_match_3_1 = bool:false;
            let case_match_3_2 = _6.1;
            let _11 = if _6.0 {
              let _7 = Xls_clause_1_Seen_1 & Xls_clause_1_Source_1;
              let _8 = _7 == 0;
              let _10 = if _8 {
                let _9 = Xls_clause_1_Present_1 < 2;
                (_9, bool:false)
              } else {
                (bool:0, bool:false)
              };
              let case_match_4_1 = bool:false;
              let case_match_4_2 = _10.1;
              (_10.0, (case_match_4_1 != case_match_4_2) || bool:false)
            } else {
              (bool:0, bool:false)
            };
            let case_match_5_1 = bool:false;
            let case_match_5_2 = _11.1;
            (_11.0, (case_match_3_1 != case_match_3_2) || (case_match_5_1 != case_match_5_2) || bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_6_1 = bool:false;
          let case_match_6_2 = _12.1;
          if _12.0 {
            let _13 = Xls_clause_1_Seen_1 | Xls_clause_1_Source_1;
            let Xls_clause_1_NewSeen_1 = _13;
            let _14 = Xls_clause_1_Parity_1 ^ Xls_clause_1_Present_1;
            let Xls_clause_1_NewParity_1 = _14;
            let _15 = Xls_clause_1_NewSeen_1 == 15;
            let _27 = if _15 {
              let _16 = (Xls_clause_1_RandomState_1 ^ (Xls_clause_1_RandomState_1 << u32:13)) & u32:0xffffffff;
              let _17 = (_16 ^ (_16 >> u32:17)) & u32:0xffffffff;
              let _18 = (_17 ^ (_17 << u32:5)) & u32:0xffffffff;
              let Xls_clause_1_NextRandom_1 = _18;
              let _19 = Xls_clause_1_NextRandom_1 < Xls_clause_1_Threshold_1;
              let _21 = if _19 {
                let _20 = (1 as u32);
                (_20, bool:false)
              } else {
                let _20 = (0 as u32);
                (_20, bool:false)
              };
              let case_match_7_1 = bool:false;
              let case_match_7_2 = _21.1;
              let Xls_clause_1_Measurement_1 = _21.0;
              let _22 = Xls_clause_1_NewParity_1 ^ Xls_clause_1_Measurement_1;
              let _23 = _22 ^ Xls_clause_1_PreviousMeasurement_1;
              let Xls_clause_1_Detection_1 = _23;
              let _24 = Syndrome {
                seen_sources: Xls_clause_1_NewSeen_1,
                data_parity: Xls_clause_1_NewParity_1,
                previous_measurement: Xls_clause_1_Measurement_1,
                announcement: Xls_clause_1_Detection_1,
                random_state: Xls_clause_1_NextRandom_1,
                ..(Xls_clause_1_Syndrome_1).1
              };
              let _25 = (Tag::SYNDROME, _24);
              let Xls_clause_1_Complete_1 = _25;
              let _26 = (Phase::ANNOUNCING, Xls_clause_1_Complete_1, Directive::CONSUME, bool:0, );
              (_26, (case_match_7_1 != case_match_7_2) || bool:false)
            } else {
              let _16 = Syndrome {
                seen_sources: Xls_clause_1_NewSeen_1,
                data_parity: Xls_clause_1_NewParity_1,
                ..(Xls_clause_1_Syndrome_1).1
              };
              let _17 = (Tag::SYNDROME, _16);
              let Xls_clause_1_Collected_1 = _17;
              let _18 = (Phase::COLLECTING, Xls_clause_1_Collected_1, Directive::CONSUME, bool:0, );
              (_18, bool:false)
            };
            let case_match_8_1 = bool:false;
            let case_match_8_2 = _27.1;
            if ((case_match_8_1 != case_match_8_2) || bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_27.0.0, _27.0.1.1, _27.0.2, _27.0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::COLLECTING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = (Phase::ANNOUNCING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_3.0, _3.1.1, _3.2, _3.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::ANNOUNCING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_ANYON => {
      let message = phenomanyon_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI_CORRECTION => {
      let message = phicorrection_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    _ => (phase, data, Directive::FAIL, u1:0),
  }
}

pub proc Service {
  req_in: chan<axis::Frame> in;
  egress_out: chan<Egress> out;
  admission_out: chan<u1> out;

  config(req_in: chan<axis::Frame> in,
         egress_out: chan<Egress> out,
         admission_out: chan<u1> out) {
    (req_in, egress_out, admission_out)
  }

  init { initial_machine() }

  next(machine: Machine) {
    if machine.failed {
      machine
    } else if machine.enter_pending {
      let (entered_data, effects) = enter(
        machine.entered_from, machine.phase, machine.data);
      let has_effect = machine.entry_effect_index < effects.count;
      let effect = effects.values[
        machine.entry_effect_index as u32];
      let emit_effect = has_effect && effects.valid[
        machine.entry_effect_index as u32];
      let egress_tok = send_if(
        join(), egress_out, emit_effect, effect);
      let next_effect_index =
        machine.entry_effect_index + (has_effect as u8);
      let entry_complete = next_effect_index >= effects.count;
      let reserve = entry_complete &&
        !machine.admission_pending &&
        machine.occupied < MAILBOX_CAPACITY;
      let admission_tok = send_if(
        egress_tok, admission_out, reserve, u1:1);
      let _entry_tok = admission_tok;
      Machine {
        data: if entry_complete { entered_data } else { machine.data },
        enter_pending: !entry_complete,
        entry_effect_index: if entry_complete {
          u8:0
        } else { next_effect_index },
        admission_pending: machine.admission_pending || reserve,
        ..machine
      }
    } else {
      let (tok, frame, received) = recv_if_non_blocking(
        join(), req_in, machine.admission_pending,
        zero!<axis::Frame>());
      let tag_ok = (frame.header.op == (Tag::PHI as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::ANYON_MOVE as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHI0 as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_CONFIG as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_REQUEST as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PHENOM_QUERY as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHENOM_DATA as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_ANYON as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHI_CORRECTION as u8) && frame.header.payload_words == u8:3);
      let accepted = received && tag_ok;
      let invalid_input = received && !tag_ok;
      let incoming_slot = MailboxSlot {
        frame,
        ..zero!<MailboxSlot>()
      };
      let admitted_slots = if accepted {
        update(machine.slots, machine.occupied as u32, incoming_slot)
      } else { machine.slots };
      let admitted_occupied = machine.occupied + (accepted as u8);
      let eligible_0 = u8:0 < admitted_occupied &&
        !admitted_slots[0].postponed;
      let eligible_1 = u8:1 < admitted_occupied &&
        !admitted_slots[1].postponed;
      let eligible_2 = u8:2 < admitted_occupied &&
        !admitted_slots[2].postponed;
      let eligible_3 = u8:3 < admitted_occupied &&
        !admitted_slots[3].postponed;
      let eligible_4 = u8:4 < admitted_occupied &&
        !admitted_slots[4].postponed;
      let found = eligible_0 || eligible_1 || eligible_2 || eligible_3 || eligible_4;
      let selected = if eligible_0 { u8:0 } else { if eligible_1 { u8:1 } else { if eligible_2 { u8:2 } else { if eligible_3 { u8:3 } else { if eligible_4 { u8:4 } else { u8:0 } } } } };
      let selected_frame = admitted_slots[selected as u32].frame;
      let dispatchable = found && !invalid_input;
      let (next_phase, next_data, directive, repeat_phase) =
        if dispatchable {
          dispatch(selected_frame, machine.phase, machine.data)
        } else {
          (machine.phase, machine.data, Directive::CONSUME, u1:0)
        };
      let invalid_repeat = dispatchable && repeat_phase &&
        (directive != Directive::CONSUME ||
         next_phase != machine.phase);
      let effective = dispatchable && !invalid_repeat;
      let selected_slot = admitted_slots[selected as u32];
      let postponed_slot = MailboxSlot {
        postponed: u1:1,
        ..selected_slot
      };
      let postponed_slots = update(
        admitted_slots, selected as u32, postponed_slot);
      let compacted_0 = if u8:0 < selected {
        admitted_slots[0]
      } else if u8:1 < admitted_occupied {
        admitted_slots[1]
      } else { zero!<MailboxSlot>() };
      let compacted_1 = if u8:1 < selected {
        admitted_slots[1]
      } else if u8:2 < admitted_occupied {
        admitted_slots[2]
      } else { zero!<MailboxSlot>() };
      let compacted_2 = if u8:2 < selected {
        admitted_slots[2]
      } else if u8:3 < admitted_occupied {
        admitted_slots[3]
      } else { zero!<MailboxSlot>() };
      let compacted_3 = if u8:3 < selected {
        admitted_slots[3]
      } else if u8:4 < admitted_occupied {
        admitted_slots[4]
      } else { zero!<MailboxSlot>() };
      let compacted_4 = zero!<MailboxSlot>();
      let compacted_slots = [compacted_0, compacted_1, compacted_2, compacted_3, compacted_4];
      let transition_slots = match directive {
        Directive::CONSUME => compacted_slots,
        Directive::POSTPONE => postponed_slots,
        Directive::FAIL => admitted_slots,
      };
      let candidate_slots = if effective {
        transition_slots
      } else { admitted_slots };
      let candidate_occupied = if effective &&
          directive == Directive::CONSUME {
        admitted_occupied - u8:1
      } else { admitted_occupied };
      let candidate_phase = if effective {
        next_phase
      } else { machine.phase };
      let candidate_data = if effective {
        next_data
      } else { machine.data };
      let phase_changed = candidate_phase != machine.phase;
      let phase_boundary = phase_changed ||
        (effective && repeat_phase);
      let unblocked_slots = [MailboxSlot { postponed: u1:0, ..candidate_slots[0] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[1] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[2] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[3] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[4] }];
      let final_slots = if phase_boundary {
        unblocked_slots
      } else { candidate_slots };
      let failed = invalid_input || invalid_repeat ||
        (effective && directive == Directive::FAIL);
      let admission_pending =
        machine.admission_pending && !received;
      // Preserve occupied + admission_pending <= capacity.
      let reserve = !failed && !received && !admission_pending &&
        candidate_occupied < MAILBOX_CAPACITY;
      let _admission_tok = send_if(
        tok, admission_out, reserve, u1:1);
      Machine {
        phase: candidate_phase,
        entered_from: if phase_boundary {
          machine.phase
        } else { machine.entered_from },
        data: candidate_data,
        slots: final_slots,
        occupied: candidate_occupied,
        enter_pending: effective && phase_boundary && !failed,
        admission_pending: admission_pending || reserve,
        failed,
        ..machine
      }
    }
  }
}

proc EgressDemux {
  egress_in: chan<Egress> in;
  north_out: chan<axis::Frame> out;
  east_out: chan<axis::Frame> out;
  west_out: chan<axis::Frame> out;
  south_out: chan<axis::Frame> out;
  phi_out: chan<axis::Frame> out;

  config(egress_in: chan<Egress> in,
         north_out: chan<axis::Frame> out,
         east_out: chan<axis::Frame> out,
         west_out: chan<axis::Frame> out,
         south_out: chan<axis::Frame> out,
         phi_out: chan<axis::Frame> out
  ) {
    (egress_in, north_out, east_out, west_out, south_out, phi_out)
  }

  init { () }

  next(state: ()) {
    let (tok, egress) = recv(join(), egress_in);
    let _send_tok = match egress.port {
      OutputPort::NORTH =>
        send(tok, north_out, egress.frame),
      OutputPort::EAST =>
        send(tok, east_out, egress.frame),
      OutputPort::WEST =>
        send(tok, west_out, egress.frame),
      OutputPort::SOUTH =>
        send(tok, south_out, egress.frame),
      OutputPort::PHI =>
        send(tok, phi_out, egress.frame),
    };
    state
  }
}

pub proc Top {
  ext_recv: chan<axis::Beat> in;
  north_send: chan<axis::Beat> out;
  east_send: chan<axis::Beat> out;
  west_send: chan<axis::Beat> out;
  south_send: chan<axis::Beat> out;
  phi_send: chan<axis::Beat> out;

  config(ext_recv: chan<axis::Beat> in,
         north_send: chan<axis::Beat> out,
         east_send: chan<axis::Beat> out,
         west_send: chan<axis::Beat> out,
         south_send: chan<axis::Beat> out,
         phi_send: chan<axis::Beat> out) {
    let (req_p, req_c) = chan<axis::Frame, u32:1>("req");
    let (admit_p, admit_c) = chan<u1, u32:1>("admit");
    let (egress_p, egress_c) =
      chan<Egress, EGRESS_DEPTH>("egress");
    let (north_p, north_c) = chan<axis::Frame, u32:1>("north");
    let (east_p, east_c) = chan<axis::Frame, u32:1>("east");
    let (west_p, west_c) = chan<axis::Frame, u32:1>("west");
    let (south_p, south_c) = chan<axis::Frame, u32:1>("south");
    let (phi_p, phi_c) = chan<axis::Frame, u32:1>("phi");
    spawn axis::ReservedRx(ext_recv, req_p, admit_c);
    spawn Service(req_c, egress_p, admit_p);
    spawn EgressDemux(egress_c, north_p, east_p, west_p, south_p, phi_p);
    spawn axis::Tx(north_c, north_send);
    spawn axis::Tx(east_c, east_send);
    spawn axis::Tx(west_c, west_send);
    spawn axis::Tx(south_c, south_send);
    spawn axis::Tx(phi_c, phi_send);
    (ext_recv, north_send, east_send, west_send, south_send, phi_send)
  }

  init { () }
  next(state: ()) { state }
}
