// src/examples/phi_decoder/phenom_syndrome_cell.erl.x
// This file is auto-generated by xls_parse. Manual changes will be
// overwritten the next time it is generated.

import axis;

const MAILBOX_CAPACITY = u8:5;
const MAILBOX_DEPTH = u32:5;

pub enum Tag : u8 {
  NONE = u8:0,
  ERROR = u8:1,
  SYNDROME = u8:2,
  PHI = u8:3,
  ANYON_MOVE = u8:4,
  PHI0 = u8:5,
  PHENOM_CONFIG = u8:6,
  PHENOM_REQUEST = u8:7,
  PHENOM_QUERY = u8:8,
  PHENOM_DATA = u8:9,
  PHENOM_ANYON = u8:10,
  PHI_CORRECTION = u8:11,
  PHI_CONFIG = u8:12,
  PAULI_QUERY = u8:13,
  PAULI_REPLY = u8:14,
  NOISE_CUTOFF = u8:15,
  PAULI_UPDATE = u8:16,
  PHI_STATUS = u8:17,
}

enum Phase : u8 {
  CONFIGURING = u8:0,
  WAITING = u8:1,
  COLLECTING = u8:2,
  ANNOUNCING = u8:3,
}

enum Directive : u2 {
  CONSUME = u2:0,
  POSTPONE = u2:1,
  FAIL = u2:2,
}

pub struct Phi {
  epoch : u32,
  values : s32[2],
}

pub fn phi_from_bits<N: u32>(raw: bits[N]) -> Phi {
  Phi {
    epoch: raw[0:32] as u32,
    values: raw[32:96] as s32[2],
  }
}

pub fn bits_from_phi(s: Phi) -> bits[bit_count<Phi>()] {
  (s.values as bits[64]) ++ (s.epoch as bits[32]) ++  zero!<bits[0]>()
}

pub struct Anyonmove {
  step : u32,
  present : u32,
}

pub fn anyonmove_from_bits<N: u32>(raw: bits[N]) -> Anyonmove {
  Anyonmove {
    step: raw[0:32] as u32,
    present: raw[32:64] as u32,
  }
}

pub fn bits_from_anyonmove(s: Anyonmove) -> bits[bit_count<Anyonmove>()] {
  (s.present as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phi0 {
  step : u32,
  source : u32,
  value : s32,
}

pub fn phi0_from_bits<N: u32>(raw: bits[N]) -> Phi0 {
  Phi0 {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
    value: raw[64:96] as s32,
  }
}

pub fn bits_from_phi0(s: Phi0) -> bits[bit_count<Phi0>()] {
  (s.value as bits[32]) ++ (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phenomconfig {
  seed : u32,
  threshold : u32,
  x : u16,
  y : u16,
}

pub fn phenomconfig_from_bits<N: u32>(raw: bits[N]) -> Phenomconfig {
  Phenomconfig {
    seed: raw[0:32] as u32,
    threshold: raw[32:64] as u32,
    x: raw[64:80] as u16,
    y: raw[80:96] as u16,
  }
}

pub fn bits_from_phenomconfig(s: Phenomconfig) -> bits[bit_count<Phenomconfig>()] {
  (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.threshold as bits[32]) ++ (s.seed as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phenomrequest {
  step : u32,
}

pub fn phenomrequest_from_bits<N: u32>(raw: bits[N]) -> Phenomrequest {
  Phenomrequest {
    step: raw[0:32] as u32,
  }
}

pub fn bits_from_phenomrequest(s: Phenomrequest) -> bits[bit_count<Phenomrequest>()] {
  (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phenomquery {
  step : u32,
  source : u32,
}

pub fn phenomquery_from_bits<N: u32>(raw: bits[N]) -> Phenomquery {
  Phenomquery {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
  }
}

pub fn bits_from_phenomquery(s: Phenomquery) -> bits[bit_count<Phenomquery>()] {
  (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phenomdata {
  step : u32,
  source : u32,
  flags : u32,
}

pub fn phenomdata_from_bits<N: u32>(raw: bits[N]) -> Phenomdata {
  Phenomdata {
    step: raw[0:32] as u32,
    source: raw[32:64] as u32,
    flags: raw[64:96] as u32,
  }
}

pub fn bits_from_phenomdata(s: Phenomdata) -> bits[bit_count<Phenomdata>()] {
  (s.flags as bits[32]) ++ (s.source as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phenomanyon {
  step : u32,
  flags : u32,
  x : u16,
  y : u16,
}

pub fn phenomanyon_from_bits<N: u32>(raw: bits[N]) -> Phenomanyon {
  Phenomanyon {
    step: raw[0:32] as u32,
    flags: raw[32:64] as u32,
    x: raw[64:80] as u16,
    y: raw[80:96] as u16,
  }
}

pub fn bits_from_phenomanyon(s: Phenomanyon) -> bits[bit_count<Phenomanyon>()] {
  (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.flags as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phicorrection {
  step : u32,
  x : u16,
  y : u16,
  direction : u32,
}

pub fn phicorrection_from_bits<N: u32>(raw: bits[N]) -> Phicorrection {
  Phicorrection {
    step: raw[0:32] as u32,
    x: raw[32:48] as u16,
    y: raw[48:64] as u16,
    direction: raw[64:96] as u32,
  }
}

pub fn bits_from_phicorrection(s: Phicorrection) -> bits[bit_count<Phicorrection>()] {
  (s.direction as bits[32]) ++ (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phiconfig {
  seed : u32,
}

pub fn phiconfig_from_bits<N: u32>(raw: bits[N]) -> Phiconfig {
  Phiconfig {
    seed: raw[0:32] as u32,
  }
}

pub fn bits_from_phiconfig(s: Phiconfig) -> bits[bit_count<Phiconfig>()] {
  (s.seed as bits[32]) ++  zero!<bits[0]>()
}

pub struct Pauliquery {
  request_id : u32,
  measurement : u32,
}

pub fn pauliquery_from_bits<N: u32>(raw: bits[N]) -> Pauliquery {
  Pauliquery {
    request_id: raw[0:32] as u32,
    measurement: raw[32:64] as u32,
  }
}

pub fn bits_from_pauliquery(s: Pauliquery) -> bits[bit_count<Pauliquery>()] {
  (s.measurement as bits[32]) ++ (s.request_id as bits[32]) ++  zero!<bits[0]>()
}

pub struct Paulireply {
  request_id : u32,
  x : u16,
  y : u16,
  anticommutes : u32,
}

pub fn paulireply_from_bits<N: u32>(raw: bits[N]) -> Paulireply {
  Paulireply {
    request_id: raw[0:32] as u32,
    x: raw[32:48] as u16,
    y: raw[48:64] as u16,
    anticommutes: raw[64:96] as u32,
  }
}

pub fn bits_from_paulireply(s: Paulireply) -> bits[bit_count<Paulireply>()] {
  (s.anticommutes as bits[32]) ++ (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.request_id as bits[32]) ++  zero!<bits[0]>()
}

pub struct Noisecutoff {
  first_quiet_step : u32,
}

pub fn noisecutoff_from_bits<N: u32>(raw: bits[N]) -> Noisecutoff {
  Noisecutoff {
    first_quiet_step: raw[0:32] as u32,
  }
}

pub fn bits_from_noisecutoff(s: Noisecutoff) -> bits[bit_count<Noisecutoff>()] {
  (s.first_quiet_step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Pauliupdate {
  pauli : u32,
}

pub fn pauliupdate_from_bits<N: u32>(raw: bits[N]) -> Pauliupdate {
  Pauliupdate {
    pauli: raw[0:32] as u32,
  }
}

pub fn bits_from_pauliupdate(s: Pauliupdate) -> bits[bit_count<Pauliupdate>()] {
  (s.pauli as bits[32]) ++  zero!<bits[0]>()
}

pub struct Phistatus {
  step : u32,
  x : u16,
  y : u16,
  flags : u32,
}

pub fn phistatus_from_bits<N: u32>(raw: bits[N]) -> Phistatus {
  Phistatus {
    step: raw[0:32] as u32,
    x: raw[32:48] as u16,
    y: raw[48:64] as u16,
    flags: raw[64:96] as u32,
  }
}

pub fn bits_from_phistatus(s: Phistatus) -> bits[bit_count<Phistatus>()] {
  (s.flags as bits[32]) ++ (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub struct Syndrome {
  step : u32,
  seen_sources : u32,
  data_parity : u32,
  previous_measurement : u32,
  announcement : u32,
  data_quiet : u32,
  announcement_quiet : u32,
  random_state : u32,
  threshold : u32,
  x : u16,
  y : u16,
  noise_disabled : u32,
  cutoff_armed : u32,
  cutoff_step : u32,
}

pub fn syndrome_from_bits<N: u32>(raw: bits[N]) -> Syndrome {
  Syndrome {
    step: raw[0:32] as u32,
    seen_sources: raw[32:64] as u32,
    data_parity: raw[64:96] as u32,
    previous_measurement: raw[96:128] as u32,
    announcement: raw[128:160] as u32,
    data_quiet: raw[160:192] as u32,
    announcement_quiet: raw[192:224] as u32,
    random_state: raw[224:256] as u32,
    threshold: raw[256:288] as u32,
    x: raw[288:304] as u16,
    y: raw[304:320] as u16,
    noise_disabled: raw[320:352] as u32,
    cutoff_armed: raw[352:384] as u32,
    cutoff_step: raw[384:416] as u32,
  }
}

pub fn bits_from_syndrome(s: Syndrome) -> bits[bit_count<Syndrome>()] {
  (s.cutoff_step as bits[32]) ++ (s.cutoff_armed as bits[32]) ++ (s.noise_disabled as bits[32]) ++ (s.y as bits[16]) ++ (s.x as bits[16]) ++ (s.threshold as bits[32]) ++ (s.random_state as bits[32]) ++ (s.announcement_quiet as bits[32]) ++ (s.data_quiet as bits[32]) ++ (s.announcement as bits[32]) ++ (s.previous_measurement as bits[32]) ++ (s.data_parity as bits[32]) ++ (s.seen_sources as bits[32]) ++ (s.step as bits[32]) ++  zero!<bits[0]>()
}

pub enum OutputPort : u8 {
  NORTH = u8:0,
  EAST = u8:1,
  WEST = u8:2,
  SOUTH = u8:3,
  PHI = u8:4,
}

pub struct Egress {
  port: OutputPort,
  frame: axis::Frame,
}

pub const EGRESS_DEPTH = u32:4;

struct EntryEffects {
  count: u8,
  valid: bool[5],
  values: Egress[5],
}

struct MailboxSlot {
  postponed: u1,
  frame: axis::Frame,
}

struct Machine {
  phase: Phase,
  entered_from: Phase,
  data: Syndrome,
  slots: MailboxSlot[5],
  occupied: u8,
  enter_pending: u1,
  entry_effect_index: u8,
  // Reserves one queue slot for the frame being assembled.
  admission_pending: u1,
  // A failed service ignores input until reset.
  failed: u1,
}

struct SharedMachine {
  phase: Phase,
  entered_from: Phase,
  data: Syndrome,
  enter_pending: u1,
  entry_effect_index: u8,
  failed: u1,
}

pub type MachineBits = bits[442];

pub struct MachineRamReq {
  addr: u32,
  data: MachineBits,
  write_mask: (),
  read_mask: (),
  we: u1,
  re: u1,
}

pub struct MachineRamResp { data: MachineBits }

pub struct MailboxRamReq {
  addr: u32,
  data: bits[128],
  write_mask: (),
  read_mask: (),
  we: u1,
  re: u1,
}

pub struct MailboxRamResp { data: bits[128] }

struct MachineStep {
  machine: Machine,
  egress: Egress,
  egress_valid: u1,
  admission_valid: u1,
}

pub struct ScheduledRequest {
  slot: u32,
  frame: axis::Frame,
  credit: u1,
}

pub struct ScheduledEgress {
  slot: u32,
  egress: Egress,
}

struct SharedStep {
  machine: SharedMachine,
  egress: Egress,
  egress_valid: u1,
  dispatched: u1,
  directive: Directive,
  phase_boundary: u1,
}

enum SharedPhase : u3 {
  BOOT = u3:0,
  STARTUP = u3:1,
  COLLECT = u3:2,
  READ = u3:3,
  EXECUTE = u3:4,
}

// XLS channel legalization currently confuses multiple otherwise-
// identical SharedService instances connected to different external
// RAM ports. INSTANCE_ID distinguishes those specializations; it is
// neither actor state nor part of scheduling policy.
struct SharedState<ACTOR_COUNT: u32, PRODUCER_COUNT: u32> {
  instance_id: u32,
  phase: SharedPhase,
  slot: u32,
  machine: SharedMachine,
  frame: axis::Frame,
  received: u1,
  mailbox_index: u8,
  order_index: u8,
  cursor: u32,
  startup_seen: u32,
  pending: ScheduledRequest[PRODUCER_COUNT],
  pending_valid: u1[PRODUCER_COUNT],
  occupied: u8[ACTOR_COUNT],
  order: u8[5][ACTOR_COUNT],
  postponed: u1[5][ACTOR_COUNT],
  egress_busy: u1,
}

fn initial_machine() -> Machine {
let _0 = Syndrome {
  ..zero!<Syndrome>()
};
let _1 = (Tag::SYNDROME, _0);
let _2 = (Phase::CONFIGURING, _1, );
let _3 = if (bool:false) {
    zero!<Machine>()
} else {
    Machine {
  phase: _2.0,
  entered_from: _2.0,
  data: _2.1.1,
  enter_pending: u1:1,
  ..zero!<Machine>()
}
};
  _3
}

fn shared_machine(machine: Machine) -> SharedMachine {
  SharedMachine {
    phase: machine.phase,
    entered_from: machine.entered_from,
    data: machine.data,
    enter_pending: machine.enter_pending,
    entry_effect_index: machine.entry_effect_index,
    failed: machine.failed,
  }
}

fn initial_shared_machine() -> SharedMachine {
  shared_machine(initial_machine())
}

fn axis_frame_from_bits(raw: bits[128]) -> axis::Frame {
  axis::Frame {
    header: axis::Header {
      payload_words: raw[0:8],
      txid: raw[8:16],
      flags: raw[16:24],
      op: raw[24:32],
    },
    payload: raw[32:128],
  }
}

fn bits_from_axis_frame(frame: axis::Frame) -> bits[128] {
  frame.payload ++ (frame.header.op as bits[8]) ++
    (frame.header.flags as bits[8]) ++
    (frame.header.txid as bits[8]) ++
    (frame.header.payload_words as bits[8])
}

fn machine_from_bits(raw: MachineBits) -> SharedMachine {
  SharedMachine {
    phase: raw[0:8] as Phase,
    entered_from: raw[8:16] as Phase,
    data: syndrome_from_bits(raw[16:432]),
    enter_pending: raw[432:433],
    entry_effect_index: raw[433:441],
    failed: raw[441:442],
  }
}

fn bits_from_machine(machine: SharedMachine) -> MachineBits {
  machine.failed ++
    (machine.entry_effect_index as bits[8]) ++
    machine.enter_pending ++
    bits_from_syndrome(machine.data) ++
    (machine.entered_from as bits[8]) ++
    (machine.phase as bits[8])
}

fn machine_read(slot: u32) -> MachineRamReq {
  MachineRamReq {
    addr: slot,
    re: u1:1,
    ..zero!<MachineRamReq>()
  }
}

fn machine_write(slot: u32, machine: SharedMachine) -> MachineRamReq {
  MachineRamReq {
    addr: slot,
    data: bits_from_machine(machine),
    we: u1:1,
    ..zero!<MachineRamReq>()
  }
}

fn mailbox_addr(slot: u32, index: u8) -> u32 {
  slot * u32:5 + index as u32
}

fn mailbox_read(slot: u32, index: u8) -> MailboxRamReq {
  MailboxRamReq {
    addr: mailbox_addr(slot, index),
    re: u1:1,
    ..zero!<MailboxRamReq>()
  }
}

fn mailbox_write(
    slot: u32, index: u8, frame: axis::Frame) -> MailboxRamReq {
  MailboxRamReq {
    addr: mailbox_addr(slot, index),
    data: bits_from_axis_frame(frame),
    we: u1:1,
    ..zero!<MailboxRamReq>()
  }
}

fn enter(old_phase: Phase, phase: Phase, data: Syndrome) -> (Syndrome, EntryEffects) {
  match phase {
    Phase::CONFIGURING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _0
      };
      (entered_data, EntryEffects {
        count: u8:0,
        valid: [
          bool:false,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
    Phase::WAITING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _0
      };
      (entered_data, EntryEffects {
        count: u8:0,
        valid: [
          bool:false,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
    Phase::COLLECTING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _3
      };
      let effect_0_valid = {
        bool:true
      };
      let effect_0 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 8,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_1_valid = {
        bool:true
      };
      let effect_1 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 4,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_2_valid = {
        bool:true
      };
      let effect_2 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 2,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      let effect_3_valid = {
        bool:true
      };
      let effect_3 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Phenomquery {
          step: _0,
          ..zero!<Phenomquery>()
        };
        let _2 = (Tag::PHENOM_QUERY, _1, bits_from_phenomquery(_1));
        let Query_1 = _2;
        let _3 = Phenomquery {
          source: 1,
          ..(Query_1).1
        };
        let _4 = (Tag::PHENOM_QUERY, _3, bits_from_phenomquery(_3));
        let _5 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(_4.0 as u8, _4.2)
        };
        _5
      };
      (entered_data, EntryEffects {
        count: u8:4,
        valid: [
          effect_0_valid,
          effect_1_valid,
          effect_2_valid,
          effect_3_valid,
          bool:false,
        ],
        values: [
          Egress { port: OutputPort::NORTH, frame: effect_0 },
          Egress { port: OutputPort::EAST, frame: effect_1 },
          Egress { port: OutputPort::WEST, frame: effect_2 },
          Egress { port: OutputPort::SOUTH, frame: effect_3 },
          zero!<Egress>(),
        ],
      })
    },
    Phase::ANNOUNCING => {
      let entered_data = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Syndrome_1.1.announcement;
        let _2 = Syndrome_1.1.announcement_quiet;
        let _3 = _2 << 1;
        let _4 = _1 | _3;
        let _5 = Syndrome_1.1.x;
        let _6 = Syndrome_1.1.y;
        let _7 = Phenomanyon {
          step: _0,
          flags: _4,
          x: _5,
          y: _6,
          ..zero!<Phenomanyon>()
        };
        let _8 = (Tag::PHENOM_ANYON, _7, bits_from_phenomanyon(_7));
        let Anyon_1 = _8;
        let _9 = if (bool:false) {
            data
        } else {
            Syndrome_1.1
        };
        _9
      };
      let effect_0_valid = {
        bool:true
      };
      let effect_0 = {
        let _OldPhase_1 = old_phase;
        let __1 = phase;
        let Syndrome_1 = (Tag::SYNDROME, data);
        let _0 = Syndrome_1.1.step;
        let _1 = Syndrome_1.1.announcement;
        let _2 = Syndrome_1.1.announcement_quiet;
        let _3 = _2 << 1;
        let _4 = _1 | _3;
        let _5 = Syndrome_1.1.x;
        let _6 = Syndrome_1.1.y;
        let _7 = Phenomanyon {
          step: _0,
          flags: _4,
          x: _5,
          y: _6,
          ..zero!<Phenomanyon>()
        };
        let _8 = (Tag::PHENOM_ANYON, _7, bits_from_phenomanyon(_7));
        let Anyon_1 = _8;
        let _9 = if (bool:false) {
            zero!<axis::Frame>()
        } else {
            axis::pack(Anyon_1.0 as u8, Anyon_1.2)
        };
        _9
      };
      (entered_data, EntryEffects {
        count: u8:1,
        valid: [
          effect_0_valid,
          bool:false,
          bool:false,
          bool:false,
          bool:false,
        ],
        values: [
          Egress { port: OutputPort::PHI, frame: effect_0 },
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
          zero!<Egress>(),
        ],
      })
    },
  }
}

fn dispatch(frame: axis::Frame, phase: Phase, data: Syndrome) -> (Phase, Syndrome, Directive, u1) {
  match frame.header.op as Tag {
    Tag::PHI => {
      let message = phi_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::ANYON_MOVE => {
      let message = anyonmove_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI0 => {
      let message = phi0_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_CONFIG => {
      let message = phenomconfig_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Seed_1 = message.seed;
          let Xls_clause_1_Threshold_1 = message.threshold;
          let Xls_clause_1_X_1 = message.x;
          let Xls_clause_1_Y_1 = message.y;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let _0 = Xls_clause_1_Seed_1 > 0;
          let _14 = if _0 {
            let _1 = Xls_clause_1_Seed_1 <= 4294967295;
            let _13 = if _1 {
              let _2 = Xls_clause_1_Threshold_1 >= 0;
              let _12 = if _2 {
                let _3 = Xls_clause_1_Threshold_1 <= 4294967295;
                let _11 = if _3 {
                  let _4 = Xls_clause_1_X_1 >= 0;
                  let _10 = if _4 {
                    let _5 = Xls_clause_1_X_1 <= 65535;
                    let _9 = if _5 {
                      let _6 = Xls_clause_1_Y_1 >= 0;
                      let _8 = if _6 {
                        let _7 = Xls_clause_1_Y_1 <= 65535;
                        (_7, bool:false)
                      } else {
                        (bool:0, bool:false)
                      };
                      let case_match_1_1 = bool:false;
                      let case_match_1_2 = _8.1;
                      (_8.0, (case_match_1_1 != case_match_1_2) || bool:false)
                    } else {
                      (bool:0, bool:false)
                    };
                    let case_match_2_1 = bool:false;
                    let case_match_2_2 = _9.1;
                    (_9.0, (case_match_2_1 != case_match_2_2) || bool:false)
                  } else {
                    (bool:0, bool:false)
                  };
                  let case_match_3_1 = bool:false;
                  let case_match_3_2 = _10.1;
                  (_10.0, (case_match_3_1 != case_match_3_2) || bool:false)
                } else {
                  (bool:0, bool:false)
                };
                let case_match_4_1 = bool:false;
                let case_match_4_2 = _11.1;
                (_11.0, (case_match_4_1 != case_match_4_2) || bool:false)
              } else {
                (bool:0, bool:false)
              };
              let case_match_5_1 = bool:false;
              let case_match_5_2 = _12.1;
              (_12.0, (case_match_5_1 != case_match_5_2) || bool:false)
            } else {
              (bool:0, bool:false)
            };
            let case_match_6_1 = bool:false;
            let case_match_6_2 = _13.1;
            (_13.0, (case_match_6_1 != case_match_6_2) || bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_7_1 = bool:false;
          let case_match_7_2 = _14.1;
          if _14.0 {
            let _15 = Syndrome {
              random_state: Xls_clause_1_Seed_1,
              threshold: Xls_clause_1_Threshold_1,
              x: Xls_clause_1_X_1,
              y: Xls_clause_1_Y_1,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _16 = (Tag::SYNDROME, _15);
            let Xls_clause_1_Configured_1 = _16;
            let _17 = (Phase::WAITING, Xls_clause_1_Configured_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_17.0, _17.1.1, _17.2, _17.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::CONFIGURING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::WAITING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::COLLECTING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::ANNOUNCING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_REQUEST => {
      let message = phenomrequest_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = (Phase::CONFIGURING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::CONFIGURING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = Syndrome {
              seen_sources: 0,
              data_parity: 0,
              announcement: 0,
              data_quiet: 1,
              announcement_quiet: 0,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _1 = (Tag::SYNDROME, _0);
            let Xls_clause_1_Collecting_1 = _1;
            let _2 = (Phase::COLLECTING, Xls_clause_1_Collecting_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_2.0, _2.1.1, _2.2, _2.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::WAITING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = (Phase::COLLECTING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_3.0, _3.1.1, _3.2, _3.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::COLLECTING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = Syndrome {
              step: Xls_clause_1_NextStep_1,
              seen_sources: 0,
              data_parity: 0,
              announcement: 0,
              data_quiet: 1,
              announcement_quiet: 0,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _4 = (Tag::SYNDROME, _3);
            let Xls_clause_1_Collecting_1 = _4;
            let _5 = (Phase::COLLECTING, Xls_clause_1_Collecting_1, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_5.0, _5.1.1, _5.2, _5.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::ANNOUNCING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_QUERY => {
      let message = phenomquery_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_DATA => {
      let message = phenomdata_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::CONFIGURING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if Xls_clause_1_Step_1 == data.step {
            let _0 = (Phase::WAITING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::WAITING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_Step_1 = message.step;
          let Xls_clause_1_Source_1 = message.source;
          let Xls_clause_1_Flags_1 = message.flags;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Seen_1 = data.seen_sources;
          let Xls_clause_1_Parity_1 = data.data_parity;
          let Xls_clause_1_PreviousMeasurement_1 = data.previous_measurement;
          let Xls_clause_1_RandomState_1 = data.random_state;
          let Xls_clause_1_Threshold_1 = data.threshold;
          let _12 = if Xls_clause_1_Step_1 == data.step {
            let _0 = Xls_clause_1_Source_1 == 1;
            let _6 = if _0 {
              (bool:1, bool:false)
            } else {
              let _1 = Xls_clause_1_Source_1 == 2;
              let _5 = if _1 {
                (bool:1, bool:false)
              } else {
                let _2 = Xls_clause_1_Source_1 == 4;
                let _4 = if _2 {
                  (bool:1, bool:false)
                } else {
                  let _3 = Xls_clause_1_Source_1 == 8;
                  (_3, bool:false)
                };
                let case_match_1_1 = bool:false;
                let case_match_1_2 = _4.1;
                (_4.0, (case_match_1_1 != case_match_1_2) || bool:false)
              };
              let case_match_2_1 = bool:false;
              let case_match_2_2 = _5.1;
              (_5.0, (case_match_2_1 != case_match_2_2) || bool:false)
            };
            let case_match_3_1 = bool:false;
            let case_match_3_2 = _6.1;
            let _11 = if _6.0 {
              let _7 = Xls_clause_1_Seen_1 & Xls_clause_1_Source_1;
              let _8 = _7 == 0;
              let _10 = if _8 {
                let _9 = Xls_clause_1_Flags_1 < 4;
                (_9, bool:false)
              } else {
                (bool:0, bool:false)
              };
              let case_match_4_1 = bool:false;
              let case_match_4_2 = _10.1;
              (_10.0, (case_match_4_1 != case_match_4_2) || bool:false)
            } else {
              (bool:0, bool:false)
            };
            let case_match_5_1 = bool:false;
            let case_match_5_2 = _11.1;
            (_11.0, (case_match_3_1 != case_match_3_2) || (case_match_5_1 != case_match_5_2) || bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_6_1 = bool:false;
          let case_match_6_2 = _12.1;
          if _12.0 {
            let _13 = Xls_clause_1_Flags_1 & 1;
            let Xls_clause_1_Present_1 = _13;
            let _14 = Xls_clause_1_Flags_1 & 2;
            let _15 = _14 >> 1;
            let Xls_clause_1_Quiet_1 = _15;
            let _16 = Xls_clause_1_Seen_1 | Xls_clause_1_Source_1;
            let Xls_clause_1_NewSeen_1 = _16;
            let _17 = Xls_clause_1_Parity_1 ^ Xls_clause_1_Present_1;
            let Xls_clause_1_NewParity_1 = _17;
            let _18 = Xls_clause_1_Syndrome_1.1.data_quiet;
            let _19 = _18 & Xls_clause_1_Quiet_1;
            let Xls_clause_1_NewDataQuiet_1 = _19;
            let _20 = Xls_clause_1_NewSeen_1 == 15;
            let _47 = if _20 {
              let _21 = Xls_clause_1_Syndrome_1.1.cutoff_armed;
              let _22 = _21 == 1;
              let _23 = Xls_clause_1_Syndrome_1.1.cutoff_step;
              let _24 = Xls_clause_1_Step_1 >= _23;
              let _25 = _22 && _24;
              let Xls_clause_1_CutoffApplies_1 = _25;
              let _26 = Xls_clause_1_Syndrome_1.1.noise_disabled;
              let _27 = _26 == 1;
              let _28 = _27 || Xls_clause_1_CutoffApplies_1;
              let Xls_clause_1_NoiseDisabled_1 = _28;
              let _30 = if Xls_clause_1_NoiseDisabled_1 {
                let _29 = (1 as u32);
                (_29, bool:false)
              } else {
                let _29 = (0 as u32);
                (_29, bool:false)
              };
              let case_match_7_1 = bool:false;
              let case_match_7_2 = _30.1;
              let Xls_clause_1_NoiseDisabledWord_1 = _30.0;
              let _34 = if Xls_clause_1_NoiseDisabled_1 {
                (Xls_clause_1_RandomState_1, bool:false)
              } else {
                let _31 = (Xls_clause_1_RandomState_1 ^ (Xls_clause_1_RandomState_1 << u32:13)) & u32:0xffffffff;
                let _32 = (_31 ^ (_31 >> u32:17)) & u32:0xffffffff;
                let _33 = (_32 ^ (_32 << u32:5)) & u32:0xffffffff;
                (_33, bool:false)
              };
              let case_match_8_1 = bool:false;
              let case_match_8_2 = _34.1;
              let Xls_clause_1_NextRandom_1 = _34.0;
              let _38 = if Xls_clause_1_NoiseDisabled_1 {
                let _35 = (0 as u32);
                (_35, bool:false)
              } else {
                let _35 = Xls_clause_1_NextRandom_1 < Xls_clause_1_Threshold_1;
                let _37 = if _35 {
                  let _36 = (1 as u32);
                  (_36, bool:false)
                } else {
                  let _36 = (0 as u32);
                  (_36, bool:false)
                };
                let case_match_9_1 = bool:false;
                let case_match_9_2 = _37.1;
                (_37.0, (case_match_9_1 != case_match_9_2) || bool:false)
              };
              let case_match_10_1 = bool:false;
              let case_match_10_2 = _38.1;
              let Xls_clause_1_Measurement_1 = _38.0;
              let _39 = Xls_clause_1_NewParity_1 ^ Xls_clause_1_Measurement_1;
              let _40 = _39 ^ Xls_clause_1_PreviousMeasurement_1;
              let Xls_clause_1_Detection_1 = _40;
              let _41 = Xls_clause_1_NewDataQuiet_1 & Xls_clause_1_NoiseDisabledWord_1;
              let _43 = if Xls_clause_1_CutoffApplies_1 {
                let _42 = (0 as u32);
                (_42, bool:false)
              } else {
                let _42 = Xls_clause_1_Syndrome_1.1.cutoff_armed;
                (_42, bool:false)
              };
              let case_match_11_1 = bool:false;
              let case_match_11_2 = _43.1;
              let _44 = Syndrome {
                seen_sources: Xls_clause_1_NewSeen_1,
                data_parity: Xls_clause_1_NewParity_1,
                previous_measurement: Xls_clause_1_Measurement_1,
                announcement: Xls_clause_1_Detection_1,
                data_quiet: Xls_clause_1_NewDataQuiet_1,
                announcement_quiet: _41,
                random_state: Xls_clause_1_NextRandom_1,
                noise_disabled: Xls_clause_1_NoiseDisabledWord_1,
                cutoff_armed: _43.0,
                ..(Xls_clause_1_Syndrome_1).1
              };
              let _45 = (Tag::SYNDROME, _44);
              let Xls_clause_1_Complete_1 = _45;
              let _46 = (Phase::ANNOUNCING, Xls_clause_1_Complete_1, Directive::CONSUME, bool:0, );
              (_46, (case_match_10_1 != case_match_10_2) || (case_match_11_1 != case_match_11_2) || (case_match_7_1 != case_match_7_2) || (case_match_8_1 != case_match_8_2) || bool:false)
            } else {
              let _21 = Syndrome {
                seen_sources: Xls_clause_1_NewSeen_1,
                data_parity: Xls_clause_1_NewParity_1,
                data_quiet: Xls_clause_1_NewDataQuiet_1,
                ..(Xls_clause_1_Syndrome_1).1
              };
              let _22 = (Tag::SYNDROME, _21);
              let Xls_clause_1_Collected_1 = _22;
              let _23 = (Phase::COLLECTING, Xls_clause_1_Collected_1, Directive::CONSUME, bool:0, );
              (_23, bool:false)
            };
            let case_match_12_1 = bool:false;
            let case_match_12_2 = _47.1;
            if ((case_match_12_1 != case_match_12_2) || bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_47.0.0, _47.0.1.1, _47.0.2, _47.0.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::COLLECTING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_NextStep_1 = message.step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _0 = Xls_clause_1_Step_1 + 1;
          let _1 = _0 & 4294967295;
          let _2 = Xls_clause_1_NextStep_1 == _1;
          if _2 {
            let _3 = (Phase::ANNOUNCING, Xls_clause_1_Syndrome_1, Directive::POSTPONE, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_3.0, _3.1.1, _3.2, _3.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::ANNOUNCING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHENOM_ANYON => {
      let message = phenomanyon_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI_CORRECTION => {
      let message = phicorrection_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI_CONFIG => {
      let message = phiconfig_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PAULI_QUERY => {
      let message = pauliquery_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PAULI_REPLY => {
      let message = paulireply_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::NOISE_CUTOFF => {
      let message = noisecutoff_from_bits(frame.payload);
      match phase {
        Phase::CONFIGURING => {
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          if bool:true {
            let _0 = (Phase::CONFIGURING, Xls_clause_1_Syndrome_1, Directive::FAIL, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_0.0, _0.1.1, _0.2, _0.3)
            }
          } else {
            (phase, data, Directive::FAIL, u1:0)
          }
        },
        Phase::WAITING => {
          let Xls_clause_1_FirstQuietStep_1 = message.first_quiet_step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _1 = if (data.noise_disabled == 0 && data.cutoff_armed == 0) {
            let _0 = Xls_clause_1_FirstQuietStep_1 >= Xls_clause_1_Step_1;
            (_0, bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_1_1 = bool:false;
          let case_match_1_2 = _1.1;
          if _1.0 {
            let _2 = Syndrome {
              cutoff_armed: 1,
              cutoff_step: Xls_clause_1_FirstQuietStep_1,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _3 = (Tag::SYNDROME, _2);
            let _4 = (Phase::WAITING, _3, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_4.0, _4.1.1, _4.2, _4.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::WAITING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::COLLECTING => {
          let Xls_clause_1_FirstQuietStep_1 = message.first_quiet_step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _1 = if (data.noise_disabled == 0 && data.cutoff_armed == 0) {
            let _0 = Xls_clause_1_FirstQuietStep_1 >= Xls_clause_1_Step_1;
            (_0, bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_1_1 = bool:false;
          let case_match_1_2 = _1.1;
          if _1.0 {
            let _2 = Syndrome {
              cutoff_armed: 1,
              cutoff_step: Xls_clause_1_FirstQuietStep_1,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _3 = (Tag::SYNDROME, _2);
            let _4 = (Phase::COLLECTING, _3, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_4.0, _4.1.1, _4.2, _4.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::COLLECTING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        Phase::ANNOUNCING => {
          let Xls_clause_1_FirstQuietStep_1 = message.first_quiet_step;
          let Xls_clause_1_Syndrome_1 = (Tag::SYNDROME, data);
          let Xls_clause_1_Step_1 = data.step;
          let _1 = if (data.noise_disabled == 0 && data.cutoff_armed == 0) {
            let _0 = Xls_clause_1_FirstQuietStep_1 > Xls_clause_1_Step_1;
            (_0, bool:false)
          } else {
            (bool:0, bool:false)
          };
          let case_match_1_1 = bool:false;
          let case_match_1_2 = _1.1;
          if _1.0 {
            let _2 = Syndrome {
              cutoff_armed: 1,
              cutoff_step: Xls_clause_1_FirstQuietStep_1,
              ..(Xls_clause_1_Syndrome_1).1
            };
            let _3 = (Tag::SYNDROME, _2);
            let _4 = (Phase::ANNOUNCING, _3, Directive::CONSUME, bool:0, );
            if (bool:false) {
              (phase, data, Directive::FAIL, u1:0)
            } else {
              (_4.0, _4.1.1, _4.2, _4.3)
            }
          } else {
            let Xls_clause_2_Syndrome_1 = (Tag::SYNDROME, data);
            if bool:true {
              let _0 = (Phase::ANNOUNCING, Xls_clause_2_Syndrome_1, Directive::FAIL, bool:0, );
              if (bool:false) {
                (phase, data, Directive::FAIL, u1:0)
              } else {
                (_0.0, _0.1.1, _0.2, _0.3)
              }
            } else {
              (phase, data, Directive::FAIL, u1:0)
            }
          }
        },
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PAULI_UPDATE => {
      let message = pauliupdate_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    Tag::PHI_STATUS => {
      let message = phistatus_from_bits(frame.payload);
      match phase {
        _ => (phase, data, Directive::FAIL, u1:0),
      }
    },
    _ => (phase, data, Directive::FAIL, u1:0),
  }
}

fn machine_step(
    machine: Machine, frame: axis::Frame, received: u1,
    egress_ready: u1) -> MachineStep {
  if machine.failed {
    MachineStep { machine, ..zero!<MachineStep>() }
  } else if machine.enter_pending {
    let (entered_data, effects) = enter(
      machine.entered_from, machine.phase, machine.data);
    let has_effect = machine.entry_effect_index < effects.count;
    let effect = effects.values[
      machine.entry_effect_index as u32];
    let emit_effect = has_effect && effects.valid[
      machine.entry_effect_index as u32];
    let can_advance = !emit_effect || egress_ready;
    let next_effect_index = machine.entry_effect_index +
      ((has_effect && can_advance) as u8);
    let entry_complete = can_advance &&
      next_effect_index >= effects.count;
    let reserve = entry_complete &&
      !machine.admission_pending &&
      machine.occupied < MAILBOX_CAPACITY;
    let advanced_machine = Machine {
      data: if entry_complete { entered_data } else { machine.data },
      enter_pending: !entry_complete,
      entry_effect_index: if entry_complete {
        u8:0
      } else { next_effect_index },
      admission_pending: machine.admission_pending || reserve,
      ..machine
    };
    MachineStep {
      machine: if can_advance { advanced_machine } else { machine },
      egress: effect,
      egress_valid: emit_effect && can_advance,
      admission_valid: reserve,
    }
  } else {
      let tag_ok = (frame.header.op == (Tag::PHI as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::ANYON_MOVE as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHI0 as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_CONFIG as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_REQUEST as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PHENOM_QUERY as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHENOM_DATA as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_ANYON as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHI_CORRECTION as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHI_CONFIG as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PAULI_QUERY as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PAULI_REPLY as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::NOISE_CUTOFF as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PAULI_UPDATE as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PHI_STATUS as u8) && frame.header.payload_words == u8:3);
      let accepted = received && tag_ok;
      let invalid_input = received && !tag_ok;
      let incoming_slot = MailboxSlot {
        frame,
        ..zero!<MailboxSlot>()
      };
      let admitted_slots = if accepted {
        update(machine.slots, machine.occupied as u32, incoming_slot)
      } else { machine.slots };
      let admitted_occupied = machine.occupied + (accepted as u8);
      let eligible_0 = u8:0 < admitted_occupied &&
        !admitted_slots[0].postponed;
      let eligible_1 = u8:1 < admitted_occupied &&
        !admitted_slots[1].postponed;
      let eligible_2 = u8:2 < admitted_occupied &&
        !admitted_slots[2].postponed;
      let eligible_3 = u8:3 < admitted_occupied &&
        !admitted_slots[3].postponed;
      let eligible_4 = u8:4 < admitted_occupied &&
        !admitted_slots[4].postponed;
      let found = eligible_0 || eligible_1 || eligible_2 || eligible_3 || eligible_4;
      let selected = if eligible_0 { u8:0 } else { if eligible_1 { u8:1 } else { if eligible_2 { u8:2 } else { if eligible_3 { u8:3 } else { if eligible_4 { u8:4 } else { u8:0 } } } } };
      let selected_frame = admitted_slots[selected as u32].frame;
      let dispatchable = found && !invalid_input;
      let (next_phase, next_data, directive, repeat_phase) =
        if dispatchable {
          dispatch(selected_frame, machine.phase, machine.data)
        } else {
          (machine.phase, machine.data, Directive::CONSUME, u1:0)
        };
      let invalid_repeat = dispatchable && repeat_phase &&
        (directive != Directive::CONSUME ||
         next_phase != machine.phase);
      let effective = dispatchable && !invalid_repeat;
      let selected_slot = admitted_slots[selected as u32];
      let postponed_slot = MailboxSlot {
        postponed: u1:1,
        ..selected_slot
      };
      let postponed_slots = update(
        admitted_slots, selected as u32, postponed_slot);
      let compacted_0 = if u8:0 < selected {
        admitted_slots[0]
      } else if u8:1 < admitted_occupied {
        admitted_slots[1]
      } else { zero!<MailboxSlot>() };
      let compacted_1 = if u8:1 < selected {
        admitted_slots[1]
      } else if u8:2 < admitted_occupied {
        admitted_slots[2]
      } else { zero!<MailboxSlot>() };
      let compacted_2 = if u8:2 < selected {
        admitted_slots[2]
      } else if u8:3 < admitted_occupied {
        admitted_slots[3]
      } else { zero!<MailboxSlot>() };
      let compacted_3 = if u8:3 < selected {
        admitted_slots[3]
      } else if u8:4 < admitted_occupied {
        admitted_slots[4]
      } else { zero!<MailboxSlot>() };
      let compacted_4 = zero!<MailboxSlot>();
      let compacted_slots = [compacted_0, compacted_1, compacted_2, compacted_3, compacted_4];
      let transition_slots = match directive {
        Directive::CONSUME => compacted_slots,
        Directive::POSTPONE => postponed_slots,
        Directive::FAIL => admitted_slots,
      };
      let candidate_slots = if effective {
        transition_slots
      } else { admitted_slots };
      let candidate_occupied = if effective &&
          directive == Directive::CONSUME {
        admitted_occupied - u8:1
      } else { admitted_occupied };
      let candidate_phase = if effective {
        next_phase
      } else { machine.phase };
      let candidate_data = if effective {
        next_data
      } else { machine.data };
      let phase_changed = candidate_phase != machine.phase;
      let phase_boundary = phase_changed ||
        (effective && repeat_phase);
      let unblocked_slots = [MailboxSlot { postponed: u1:0, ..candidate_slots[0] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[1] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[2] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[3] },
        MailboxSlot { postponed: u1:0, ..candidate_slots[4] }];
      let final_slots = if phase_boundary {
        unblocked_slots
      } else { candidate_slots };
      let failed = invalid_input || invalid_repeat ||
        (effective && directive == Directive::FAIL);
      let admission_pending =
        machine.admission_pending && !received;
      // Preserve occupied + admission_pending <= capacity.
      let reserve = !failed && !received && !admission_pending &&
        candidate_occupied < MAILBOX_CAPACITY;
      let next_machine = Machine {
        phase: candidate_phase,
        entered_from: if phase_boundary {
          machine.phase
        } else { machine.entered_from },
        data: candidate_data,
        slots: final_slots,
        occupied: candidate_occupied,
        enter_pending: effective && phase_boundary && !failed,
        admission_pending: admission_pending || reserve,
        failed,
        ..machine
      };
      MachineStep {
        machine: next_machine,
        admission_valid: reserve,
        ..zero!<MachineStep>()
      }
  }
}

fn shared_machine_step(
    machine: SharedMachine, frame: axis::Frame, received: u1,
    egress_ready: u1) -> SharedStep {
  if machine.failed {
    SharedStep { machine, ..zero!<SharedStep>() }
  } else if machine.enter_pending {
    let (entered_data, effects) = enter(
      machine.entered_from, machine.phase, machine.data);
    let has_effect = machine.entry_effect_index < effects.count;
    let effect = effects.values[
      machine.entry_effect_index as u32];
    let emit_effect = has_effect && effects.valid[
      machine.entry_effect_index as u32];
    let can_advance = !emit_effect || egress_ready;
    let next_effect_index = machine.entry_effect_index +
      ((has_effect && can_advance) as u8);
    let entry_complete = can_advance &&
      next_effect_index >= effects.count;
    let advanced_machine = SharedMachine {
      data: if entry_complete { entered_data } else { machine.data },
      enter_pending: !entry_complete,
      entry_effect_index: if entry_complete {
        u8:0
      } else { next_effect_index },
      ..machine
    };
    SharedStep {
      machine: if can_advance { advanced_machine } else { machine },
      egress: effect,
      egress_valid: emit_effect && can_advance,
      ..zero!<SharedStep>()
    }
  } else if received {
    let tag_ok = (frame.header.op == (Tag::PHI as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::ANYON_MOVE as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHI0 as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_CONFIG as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_REQUEST as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PHENOM_QUERY as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PHENOM_DATA as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHENOM_ANYON as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHI_CORRECTION as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::PHI_CONFIG as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PAULI_QUERY as u8) && frame.header.payload_words == u8:2) || (frame.header.op == (Tag::PAULI_REPLY as u8) && frame.header.payload_words == u8:3) || (frame.header.op == (Tag::NOISE_CUTOFF as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PAULI_UPDATE as u8) && frame.header.payload_words == u8:1) || (frame.header.op == (Tag::PHI_STATUS as u8) && frame.header.payload_words == u8:3);
    let (next_phase, next_data, directive, repeat_phase) =
      if tag_ok {
        dispatch(frame, machine.phase, machine.data)
      } else {
        (machine.phase, machine.data, Directive::FAIL, u1:0)
      };
    let invalid_repeat = tag_ok && repeat_phase &&
      (directive != Directive::CONSUME ||
       next_phase != machine.phase);
    let effective = tag_ok && !invalid_repeat;
    let phase_changed = effective && next_phase != machine.phase;
    let phase_boundary = phase_changed ||
      (effective && repeat_phase);
    let failed = !tag_ok || invalid_repeat ||
      (effective && directive == Directive::FAIL);
    let next_machine = SharedMachine {
      phase: if effective { next_phase } else { machine.phase },
      entered_from: if phase_boundary {
        machine.phase
      } else { machine.entered_from },
      data: if effective { next_data } else { machine.data },
      enter_pending: effective && phase_boundary && !failed,
      failed,
      ..machine
    };
    SharedStep {
      machine: next_machine,
      dispatched: tag_ok && !invalid_repeat,
      directive,
      phase_boundary,
      ..zero!<SharedStep>()
    }
  } else {
    SharedStep { machine, ..zero!<SharedStep>() }
  }
}

pub proc Service {
  req_in: chan<axis::Frame> in;
  egress_out: chan<Egress> out;
  admission_out: chan<u1> out;

  config(req_in: chan<axis::Frame> in,
         egress_out: chan<Egress> out,
         admission_out: chan<u1> out) {
    (req_in, egress_out, admission_out)
  }

  init { initial_machine() }

  next(machine: Machine) {
    let receive_enabled = !machine.failed &&
      !machine.enter_pending && machine.admission_pending;
    let (tok, frame, received) = recv_if_non_blocking(
      join(), req_in, receive_enabled, zero!<axis::Frame>());
    let stepped = machine_step(machine, frame, received, u1:1);
    let egress_tok = send_if(
      tok, egress_out, stepped.egress_valid, stepped.egress);
    let _admission_tok = send_if(
      egress_tok, admission_out, stepped.admission_valid, u1:1);
    stepped.machine
  }
}

fn free_mailbox_index<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
    state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
    slot: u32) -> u8 {
  let (_found, selected) = unroll_for! (candidate, acc):
      (u32, (u1, u8)) in
      u32:0..MAILBOX_DEPTH {
    let used = unroll_for! (position, found):
        (u32, u1) in u32:0..MAILBOX_DEPTH {
      found || (
        position < state.occupied[slot] as u32 &&
        state.order[slot][position] == candidate as u8)
    }(u1:0);
    let take = !acc.0 && !used;
    (
      acc.0 || take,
      if take { candidate as u8 } else { acc.1 }
    )
  }((u1:0, u8:0));
  selected
}

fn mailbox_selection<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
    state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
    slot: u32) -> (u1, u8, u8) {
  unroll_for! (position, acc):
      (u32, (u1, u8, u8)) in
      u32:0..MAILBOX_DEPTH {
    let physical = state.order[slot][position];
    let take = !acc.0 &&
      position < state.occupied[slot] as u32 &&
      !state.postponed[slot][physical as u32];
    (
      acc.0 || take,
      if take { position as u8 } else { acc.1 },
      if take { physical } else { acc.2 }
    )
  }((u1:0, u8:0, u8:0))
}

fn compact_order(
    row: u8[MAILBOX_DEPTH],
    selected: u8,
    occupied: u8) -> u8[MAILBOX_DEPTH] {
  unroll_for! (position, result):
      (u32, u8[MAILBOX_DEPTH]) in
      u32:0..MAILBOX_DEPTH {
    let value = if position < selected as u32 {
      row[position]
    } else if position + u32:1 < occupied as u32 {
      row[position + u32:1]
    } else {
      u8:0
    };
    update(result, position, value)
  }(zero!<u8[MAILBOX_DEPTH]>())
}

// One mailbox owner admits frames, keeps queue metadata, and fairly
// advances all actors in a homogeneous scheduler group. Every producer
// has one holding slot, so one full actor cannot block unrelated traffic
// before manager admission.
pub proc SharedService<
    ACTOR_COUNT: u32,
    PRODUCER_COUNT: u32,
    STARTUP_COUNT: u32,
    INSTANCE_ID: u32
> {
  request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in;
  startup_in: chan<ScheduledRequest> in;
  egress_out: chan<ScheduledEgress> out;
  ram_req_out: chan<MachineRamReq> out;
  ram_resp_in: chan<MachineRamResp> in;
  ram_wr_comp_in: chan<()> in;
  mailbox_req_out: chan<MailboxRamReq> out;
  mailbox_resp_in: chan<MailboxRamResp> in;
  mailbox_wr_comp_in: chan<()> in;

  config(
      request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in,
      startup_in: chan<ScheduledRequest> in,
      egress_out: chan<ScheduledEgress> out,
      ram_req_out: chan<MachineRamReq> out,
      ram_resp_in: chan<MachineRamResp> in,
      ram_wr_comp_in: chan<()> in,
      mailbox_req_out: chan<MailboxRamReq> out,
      mailbox_resp_in: chan<MailboxRamResp> in,
      mailbox_wr_comp_in: chan<()> in
  ) {
    (
      request_in,
      startup_in,
      egress_out,
      ram_req_out,
      ram_resp_in,
      ram_wr_comp_in,
      mailbox_req_out,
      mailbox_resp_in,
      mailbox_wr_comp_in,
    )
  }

  init {
    SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
      instance_id: INSTANCE_ID,
      phase: SharedPhase::BOOT,
      ..zero!<SharedState<ACTOR_COUNT, PRODUCER_COUNT>>()
    }
  }

  next(state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>) {
    match state.phase {
      SharedPhase::BOOT => {
        let write_tok = send(
          join(),
          ram_req_out,
          machine_write(state.cursor, initial_shared_machine()));
        let (_done, _) = recv(write_tok, ram_wr_comp_in);
        if state.cursor + u32:1 == ACTOR_COUNT {
          SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
            phase: if STARTUP_COUNT == u32:0 {
              SharedPhase::COLLECT
            } else {
              SharedPhase::STARTUP
            },
            ..zero!<SharedState<ACTOR_COUNT, PRODUCER_COUNT>>()
          }
        } else {
          SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
            cursor: state.cursor + u32:1,
            ..state
          }
        }
      },
      SharedPhase::STARTUP => {
        let (tok, request) = recv(join(), startup_in);
        let physical = state.occupied[request.slot];
        let write_tok = send(
          tok,
          mailbox_req_out,
          mailbox_write(request.slot, physical, request.frame));
        let (_done, _) = recv(write_tok, mailbox_wr_comp_in);
        let occupied = update(
          state.occupied, request.slot, physical + u8:1);
        let row = update(
          state.order[request.slot], physical as u32, physical);
        let order = update(state.order, request.slot, row);
        let startup_seen = state.startup_seen + u32:1;
        SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          phase: if startup_seen == STARTUP_COUNT {
            SharedPhase::COLLECT
          } else {
            SharedPhase::STARTUP
          },
          startup_seen,
          occupied,
          order,
          ..state
        }
      },
      SharedPhase::COLLECT => {
        let (capture_tok, pending, pending_valid) =
          unroll_for! (producer, acc):
              (u32, (
                token,
                ScheduledRequest[PRODUCER_COUNT],
                u1[PRODUCER_COUNT]
              )) in u32:0..PRODUCER_COUNT {
            let (next_tok, request, received) =
              recv_if_non_blocking(
                acc.0,
                request_in[producer],
                !acc.2[producer],
                zero!<ScheduledRequest>());
            (
              next_tok,
              if received {
                update(acc.1, producer, request)
              } else {
                acc.1
              },
              if received {
                update(acc.2, producer, u1:1)
              } else {
                acc.2
              }
            )
          }((join(), state.pending, state.pending_valid));
        let (credit_found, credit_producer) =
          unroll_for! (candidate, acc):
              (u32, (u1, u32)) in u32:0..PRODUCER_COUNT {
            let take = !acc.0 && pending_valid[candidate] &&
              pending[candidate].credit;
            (acc.0 || take, if take { candidate } else { acc.1 })
          }((u1:0, u32:0));
        let (found, producer) = unroll_for! (candidate, acc):
            (u32, (u1, u32)) in u32:0..PRODUCER_COUNT {
          let slot = pending[candidate].slot;
          let eligible = !acc.0 &&
            pending_valid[candidate] &&
            !pending[candidate].credit &&
            slot < ACTOR_COUNT &&
            state.occupied[slot] < MAILBOX_CAPACITY;
          (
            acc.0 || eligible,
            if eligible { candidate } else { acc.1 }
          )
        }((u1:0, u32:0));
        let request = pending[producer];
        let physical = free_mailbox_index(state, request.slot);
        let write_tok = send_if(
          capture_tok,
          mailbox_req_out,
          found,
          mailbox_write(request.slot, physical, request.frame));
        let (_done, _) = recv_if(
          write_tok, mailbox_wr_comp_in, found, ());
        let old_count = state.occupied[request.slot];
        let occupied = if found {
          update(state.occupied, request.slot, old_count + u8:1)
        } else {
          state.occupied
        };
        let row = update(
          state.order[request.slot], old_count as u32, physical);
        let order = if found {
          update(state.order, request.slot, row)
        } else {
          state.order
        };
        let remaining_after_admission = if found {
          update(pending_valid, producer, u1:0)
        } else {
          pending_valid
        };
        let remaining = if credit_found {
          update(remaining_after_admission, credit_producer, u1:0)
        } else {
          remaining_after_admission
        };
        SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          phase: SharedPhase::READ,
          pending,
          pending_valid: remaining,
          occupied,
          order,
          egress_busy: state.egress_busy && !credit_found,
          ..state
        }
      },
      SharedPhase::READ => {
        let (received, order_index, mailbox_index) =
          mailbox_selection(state, state.cursor);
        let state_tok = send(
          join(), ram_req_out, machine_read(state.cursor));
        let mailbox_tok = send_if(
          join(),
          mailbox_req_out,
          received,
          mailbox_read(state.cursor, mailbox_index));
        let (state_done, response) = recv(state_tok, ram_resp_in);
        let (mailbox_done, mailbox_response) = recv_if(
          mailbox_tok,
          mailbox_resp_in,
          received,
          zero!<MailboxRamResp>());
        let _done = join(state_done, mailbox_done);
        SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          phase: SharedPhase::EXECUTE,
          slot: state.cursor,
          machine: machine_from_bits(response.data),
          frame: axis_frame_from_bits(mailbox_response.data),
          received,
          mailbox_index,
          order_index,
          ..state
        }
      },
      SharedPhase::EXECUTE => {
        let stepped = shared_machine_step(
          state.machine, state.frame, state.received,
          !state.egress_busy);
        let scheduled = ScheduledEgress {
          slot: state.slot,
          egress: stepped.egress,
        };
        let egress_tok = send_if(
          join(), egress_out, stepped.egress_valid, scheduled);
        let write_tok = send(
          egress_tok,
          ram_req_out,
          machine_write(state.slot, stepped.machine));
        let (_done, _) = recv(write_tok, ram_wr_comp_in);
        let consumed = state.received &&
          stepped.dispatched &&
          stepped.directive == Directive::CONSUME;
        let should_postpone = state.received &&
          stepped.dispatched &&
          stepped.directive == Directive::POSTPONE;
        let old_count = state.occupied[state.slot];
        let occupied = update(
          state.occupied,
          state.slot,
          if consumed { old_count - u8:1 } else { old_count });
        let compacted = compact_order(
          state.order[state.slot], state.order_index, old_count);
        let order = if consumed {
          update(state.order, state.slot, compacted)
        } else {
          state.order
        };
        let marked = update(
          state.postponed[state.slot],
          state.mailbox_index as u32,
          u1:1);
        let postponed_row = if stepped.phase_boundary {
          zero!<u1[MAILBOX_DEPTH]>()
        } else if should_postpone {
          marked
        } else {
          state.postponed[state.slot]
        };
        let postponed = update(
          state.postponed, state.slot, postponed_row);
        let cursor = if state.cursor + u32:1 == ACTOR_COUNT {
          u32:0
        } else {
          state.cursor + u32:1
        };
        SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          phase: SharedPhase::COLLECT,
          cursor,
          occupied,
          order,
          postponed,
          egress_busy: state.egress_busy || stepped.egress_valid,
          ..state
        }
      },
    }
  }
}
proc EgressDemux {
  egress_in: chan<Egress> in;
  north_out: chan<axis::Frame> out;
  east_out: chan<axis::Frame> out;
  west_out: chan<axis::Frame> out;
  south_out: chan<axis::Frame> out;
  phi_out: chan<axis::Frame> out;

  config(egress_in: chan<Egress> in,
         north_out: chan<axis::Frame> out,
         east_out: chan<axis::Frame> out,
         west_out: chan<axis::Frame> out,
         south_out: chan<axis::Frame> out,
         phi_out: chan<axis::Frame> out
  ) {
    (egress_in, north_out, east_out, west_out, south_out, phi_out)
  }

  init { () }

  next(state: ()) {
    let (tok, egress) = recv(join(), egress_in);
    let _send_tok = match egress.port {
      OutputPort::NORTH =>
        send(tok, north_out, egress.frame),
      OutputPort::EAST =>
        send(tok, east_out, egress.frame),
      OutputPort::WEST =>
        send(tok, west_out, egress.frame),
      OutputPort::SOUTH =>
        send(tok, south_out, egress.frame),
      OutputPort::PHI =>
        send(tok, phi_out, egress.frame),
    };
    state
  }
}

pub proc Top {
  ext_recv: chan<axis::Beat> in;
  north_send: chan<axis::Beat> out;
  east_send: chan<axis::Beat> out;
  west_send: chan<axis::Beat> out;
  south_send: chan<axis::Beat> out;
  phi_send: chan<axis::Beat> out;

  config(ext_recv: chan<axis::Beat> in,
         north_send: chan<axis::Beat> out,
         east_send: chan<axis::Beat> out,
         west_send: chan<axis::Beat> out,
         south_send: chan<axis::Beat> out,
         phi_send: chan<axis::Beat> out) {
    let (req_p, req_c) = chan<axis::Frame, u32:1>("req");
    let (admit_p, admit_c) = chan<u1, u32:1>("admit");
    let (egress_p, egress_c) =
      chan<Egress, EGRESS_DEPTH>("egress");
    let (north_p, north_c) = chan<axis::Frame, u32:1>("north");
    let (east_p, east_c) = chan<axis::Frame, u32:1>("east");
    let (west_p, west_c) = chan<axis::Frame, u32:1>("west");
    let (south_p, south_c) = chan<axis::Frame, u32:1>("south");
    let (phi_p, phi_c) = chan<axis::Frame, u32:1>("phi");
    spawn axis::ReservedRx(ext_recv, req_p, admit_c);
    spawn Service(req_c, egress_p, admit_p);
    spawn EgressDemux(egress_c, north_p, east_p, west_p, south_p, phi_p);
    spawn axis::Tx(north_c, north_send);
    spawn axis::Tx(east_c, east_send);
    spawn axis::Tx(west_c, west_send);
    spawn axis::Tx(south_c, south_send);
    spawn axis::Tx(phi_c, phi_send);
    (ext_recv, north_send, east_send, west_send, south_send, phi_send)
  }

  init { () }
  next(state: ()) { state }
}
