// phi_phenom_topology.x
// Auto-generated by xls_topology_dslx from normalized Erlang data.
// Manual changes will be overwritten.
//
// Actor summaries validate route schemas and actor-to-actor layouts.
// Direct Frame edges also require matching local selectors; tag remapping
// is not implemented. External producers must agree on one encoding.
// One typed actor egress feeds one queue per source/recipient lane; the 3
// lane(s) reached through multiple source ports retain actor action order.
// 2 startup prefix(es) emit all target startup frames before
// receiving that target's first routed frame.

import axis;
import phenom_data_cell;
import phenom_syndrome_cell;
import phi_halo_cell;

const CHANNEL_DEPTH = u32:1;

// 1 queued fanout route(s) complete at actor-egress acceptance;
// their source router subsequently waits for every lane queue.

proc FrameRelay {
  frame_in: chan<axis::Frame> in;
  frame_out: chan<axis::Frame> out;

  config(frame_in: chan<axis::Frame> in,
         frame_out: chan<axis::Frame> out) {
    (frame_in, frame_out)
  }

  init { () }

  next(state: ()) {
    let (tok, frame) = recv(join(), frame_in);
    send(tok, frame_out, frame);
    state
  }
}

proc ActorRouter0 {
  egress_in: chan<phenom_data_cell::Egress> in;
  actor_0_lane_0_out: chan<axis::Frame> out;

  config(egress_in: chan<phenom_data_cell::Egress> in,
         actor_0_lane_0_out: chan<axis::Frame> out
  ) {
    (egress_in, actor_0_lane_0_out)
  }

  init { () }

  next(state: ()) {
    let (tok, egress) = recv(join(), egress_in);
    let _route_tok = match egress.port {
      phenom_data_cell::OutputPort::NORTH =>
        send(tok, actor_0_lane_0_out, egress.frame),
      phenom_data_cell::OutputPort::EAST =>
        send(tok, actor_0_lane_0_out, egress.frame),
      phenom_data_cell::OutputPort::WEST =>
        send(tok, actor_0_lane_0_out, egress.frame),
      phenom_data_cell::OutputPort::SOUTH =>
        send(tok, actor_0_lane_0_out, egress.frame),
    };
    state
  }
}

proc ActorRouter1 {
  egress_in: chan<phi_halo_cell::Egress> in;
  actor_1_lane_1_out: chan<axis::Frame> out;
  actor_1_lane_2_out: chan<axis::Frame> out;
  actor_1_lane_3_out: chan<axis::Frame> out;

  config(egress_in: chan<phi_halo_cell::Egress> in,
         actor_1_lane_1_out: chan<axis::Frame> out,
         actor_1_lane_2_out: chan<axis::Frame> out,
         actor_1_lane_3_out: chan<axis::Frame> out
  ) {
    (egress_in, actor_1_lane_1_out, actor_1_lane_2_out, actor_1_lane_3_out)
  }

  init { () }

  next(state: ()) {
    let (tok, egress) = recv(join(), egress_in);
    let _route_tok = match egress.port {
      phi_halo_cell::OutputPort::NORTH =>
        send(tok, actor_1_lane_1_out, egress.frame),
      phi_halo_cell::OutputPort::EAST =>
        send(tok, actor_1_lane_1_out, egress.frame),
      phi_halo_cell::OutputPort::WEST =>
        send(tok, actor_1_lane_1_out, egress.frame),
      phi_halo_cell::OutputPort::SOUTH =>
        send(tok, actor_1_lane_1_out, egress.frame),
      phi_halo_cell::OutputPort::SYNDROME =>
        send(tok, actor_1_lane_2_out, egress.frame),
      phi_halo_cell::OutputPort::CORRECTION =>
        send(tok, actor_1_lane_3_out, egress.frame),
    };
    state
  }
}

proc ActorRouter2 {
  egress_in: chan<phenom_syndrome_cell::Egress> in;
  actor_2_lane_4_out: chan<axis::Frame> out;
  actor_2_lane_5_out: chan<axis::Frame> out;
  actor_2_lane_6_out: chan<axis::Frame> out;

  config(egress_in: chan<phenom_syndrome_cell::Egress> in,
         actor_2_lane_4_out: chan<axis::Frame> out,
         actor_2_lane_5_out: chan<axis::Frame> out,
         actor_2_lane_6_out: chan<axis::Frame> out
  ) {
    (egress_in, actor_2_lane_4_out, actor_2_lane_5_out, actor_2_lane_6_out)
  }

  init { () }

  next(state: ()) {
    let (tok, egress) = recv(join(), egress_in);
    let _route_tok = match egress.port {
      phenom_syndrome_cell::OutputPort::NORTH =>
        send(tok, actor_2_lane_4_out, egress.frame),
      phenom_syndrome_cell::OutputPort::EAST =>
        send(tok, actor_2_lane_4_out, egress.frame),
      phenom_syndrome_cell::OutputPort::WEST =>
        send(tok, actor_2_lane_4_out, egress.frame),
      phenom_syndrome_cell::OutputPort::SOUTH =>
        send(tok, actor_2_lane_4_out, egress.frame),
      phenom_syndrome_cell::OutputPort::PHI =>
        {
        let lane_5_tok = send(tok, actor_2_lane_5_out, egress.frame);
        let lane_6_tok = send(tok, actor_2_lane_6_out, egress.frame);
        join(lane_5_tok, lane_6_tok)
      },
    };
    state
  }
}

proc StartupPrefix0 {
  routed_in: chan<axis::Frame> in;
  frame_out: chan<axis::Frame> out;

  config(routed_in: chan<axis::Frame> in,
         frame_out: chan<axis::Frame> out) {
    (routed_in, frame_out)
  }

  init { u32:0 }

  next(index: u32) {
    let starting = index < u32:1;
    let startup_frame = match index {
      u32:0 => axis::pack(u8:6, uN[96]:0x00000000800000009E3779B9),
      _ => zero!<axis::Frame>(),
    };
    let (tok, routed_frame) = recv_if(
      join(), routed_in, !starting, zero!<axis::Frame>());
    let frame = if starting { startup_frame } else { routed_frame };
    send(tok, frame_out, frame);
    if starting { index + u32:1 } else { index }
  }
}

proc StartupPrefix1 {
  routed_in: chan<axis::Frame> in;
  frame_out: chan<axis::Frame> out;

  config(routed_in: chan<axis::Frame> in,
         frame_out: chan<axis::Frame> out) {
    (routed_in, frame_out)
  }

  init { u32:0 }

  next(index: u32) {
    let starting = index < u32:1;
    let startup_frame = match index {
      u32:0 => axis::pack(u8:6, uN[96]:0x000000008000000085EBCA6B),
      _ => zero!<axis::Frame>(),
    };
    let (tok, routed_frame) = recv_if(
      join(), routed_in, !starting, zero!<axis::Frame>());
    let frame = if starting { startup_frame } else { routed_frame };
    send(tok, frame_out, frame);
    if starting { index + u32:1 } else { index }
  }
}

pub proc Top {
  announcement_out: chan<axis::Frame> out;
  correction_out: chan<axis::Frame> out;

  config(
      announcement_out: chan<axis::Frame> out,
      correction_out: chan<axis::Frame> out
  ) {
    // Actor data uses phenom_data_cell output ABI order [north,east,west,south].
    let (actor_0_req_p, actor_0_req_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_0_req");
    let (actor_0_admit_p, actor_0_admit_c) = chan<u1, CHANNEL_DEPTH>("actor_0_admit");
    let (actor_0_egress_p, actor_0_egress_c) = chan<phenom_data_cell::Egress, u32:4>("actor_0_egress");
    // Actor phi uses phi_halo_cell output ABI order [north,east,west,south,syndrome,correction].
    let (actor_1_req_p, actor_1_req_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_1_req");
    let (actor_1_admit_p, actor_1_admit_c) = chan<u1, CHANNEL_DEPTH>("actor_1_admit");
    let (actor_1_egress_p, actor_1_egress_c) = chan<phi_halo_cell::Egress, u32:5>("actor_1_egress");
    // Actor syndrome uses phenom_syndrome_cell output ABI order [north,east,west,south,phi].
    let (actor_2_req_p, actor_2_req_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_2_req");
    let (actor_2_admit_p, actor_2_admit_c) = chan<u1, CHANNEL_DEPTH>("actor_2_admit");
    let (actor_2_egress_p, actor_2_egress_c) = chan<phenom_syndrome_cell::Egress, u32:4>("actor_2_egress");
    spawn phenom_data_cell::Service(
      actor_0_req_c,
      actor_0_egress_p,
      actor_0_admit_p);
    spawn phi_halo_cell::Service(
      actor_1_req_c,
      actor_1_egress_p,
      actor_1_admit_p);
    spawn phenom_syndrome_cell::Service(
      actor_2_req_c,
      actor_2_egress_p,
      actor_2_admit_p);
    let (actor_0_lane_0_p, actor_0_lane_0_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_0_lane_0");
    let (actor_1_lane_1_p, actor_1_lane_1_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_1_lane_1");
    let (actor_1_lane_2_p, actor_1_lane_2_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_1_lane_2");
    let (actor_1_lane_3_p, actor_1_lane_3_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_1_lane_3");
    let (actor_2_lane_4_p, actor_2_lane_4_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_2_lane_4");
    let (actor_2_lane_5_p, actor_2_lane_5_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_2_lane_5");
    let (actor_2_lane_6_p, actor_2_lane_6_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_2_lane_6");
    spawn ActorRouter0(actor_0_egress_c, actor_0_lane_0_p);
    spawn ActorRouter1(actor_1_egress_c, actor_1_lane_1_p, actor_1_lane_2_p, actor_1_lane_3_p);
    spawn ActorRouter2(actor_2_egress_c, actor_2_lane_4_p, actor_2_lane_5_p, actor_2_lane_6_p);
    let (startup_0_prefix_p, startup_0_prefix_c) = chan<axis::Frame, CHANNEL_DEPTH>("startup_0_prefix");
    spawn StartupPrefix0(actor_2_lane_4_c, startup_0_prefix_p);
    spawn axis::ReservedFrame(startup_0_prefix_c, actor_0_req_p, actor_0_admit_c);
    let (actor_1_ingress_mux_0_0_p, actor_1_ingress_mux_0_0_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_1_ingress_mux_0_0");
    spawn axis::FrameMux2(actor_1_lane_1_c, actor_2_lane_5_c, actor_1_ingress_mux_0_0_p);
    spawn axis::ReservedFrame(actor_1_ingress_mux_0_0_c, actor_1_req_p, actor_1_admit_c);
    let (actor_2_ingress_mux_0_0_p, actor_2_ingress_mux_0_0_c) = chan<axis::Frame, CHANNEL_DEPTH>("actor_2_ingress_mux_0_0");
    spawn axis::FrameMux2(actor_0_lane_0_c, actor_1_lane_2_c, actor_2_ingress_mux_0_0_p);
    let (startup_1_prefix_p, startup_1_prefix_c) = chan<axis::Frame, CHANNEL_DEPTH>("startup_1_prefix");
    spawn StartupPrefix1(actor_2_ingress_mux_0_0_c, startup_1_prefix_p);
    spawn axis::ReservedFrame(startup_1_prefix_c, actor_2_req_p, actor_2_admit_c);
    spawn FrameRelay(actor_2_lane_6_c, announcement_out);
    spawn FrameRelay(actor_1_lane_3_c, correction_out);

    (announcement_out, correction_out)
  }

  init { () }
  next(state: ()) { state }
}
