%%%% phi_memory_gateway_dslx
%%%%
%%%% Routed AXI-stream boundary for the phi memory experiment.

-module(phi_memory_gateway_dslx).
-moduledoc """
Generates the routed AXI-stream gateway around one phi/noise topology.

The checked artifact imports the distance-three topology. `to_dslx/1` also
emits the staging-only distance-one wrapper without flattening either imported
topology into the gateway source.

The procedural DSLX below is the narrow, hand-written backend adapter. Its ABI
facts are not repeated there: endpoint allocation, external order, message
selectors, payload widths, target selectors, and frame capacity are rendered
from `phi_memory_boundary`, which derives them from the topology and generated
actor codecs. The checked `.x` file is a reviewable generated artifact.

Malformed routes and frames are drained without actor delivery. Until the
gateway has a typed connection-fault sideband, the host observes that rejection
through the experiment timeout rather than an invented application reply.
""".

-export([to_dslx/0, to_dslx/1]).

-doc "Generates the checked distance-three gateway.".
-spec to_dslx() -> iolist().
to_dslx() ->
    to_dslx(3).

-doc "Generates the gateway for a checked or staging topology module.".
-spec to_dslx(1 | 3) -> iolist().
to_dslx(1) ->
    emit(1, phi_noise_topology_smoke, phi_memory_gateway_smoke);
to_dslx(3) ->
    emit(3, phi_noise_topology, phi_memory_gateway);
to_dslx(_Distance) ->
    error(badarg).

emit(Distance, TopologyModule, Artifact) ->
    Contract = phi_memory_boundary:contract(Distance),
    [
        "// ", atom_to_list(Artifact), ".x\n",
        "// Auto-generated by phi_memory_gateway_dslx.\n",
        "// Manual changes will be overwritten.\n\n",
        "import axis;\n",
        "import hls_spatial_router;\n",
        "import ", atom_to_list(TopologyModule), ";\n\n",
        "const WIDTH = u16:", integer_to_list(Distance), ";\n",
        "const HEIGHT = u16:", integer_to_list(Distance), ";\n",
        body(TopologyModule, Contract)
    ].

body(TopologyModule, Contract) ->
    Template = """
    const DATA_HEIGHT = HEIGHT * u16:2;
    @BOUNDARY_CONSTANTS@

    type BoundaryFrame = axis::FrameN<@BOUNDARY_WORDS@>;

    enum RouteState : u2 {
      HEADER = 0,
      FORWARD = 1,
      DROP = 2,
    }

    fn route_word(source: u16, destination: u16) -> u32 {
      ((source as u32) << u32:16) | destination as u32
    }

    // Consumes exactly one route beat, then forwards or drains the complete
    // boundary Frame. Invalid routes cannot desynchronize the next packet.
    proc RouteIngress {
      routed_in: chan<axis::Beat> in;
      boundary_out: chan<axis::Beat> out;

      config(
          routed_in: chan<axis::Beat> in,
          boundary_out: chan<axis::Beat> out
      ) {
        (routed_in, boundary_out)
      }

      init { RouteState::HEADER }

      next(state: RouteState) {
        let (tok, beat) = recv(join(), routed_in);
        match state {
          RouteState::HEADER => if beat.tlast {
            RouteState::HEADER
          } else if beat.word == route_word(HOST_ENDPOINT, GATEWAY_ENDPOINT) {
            RouteState::FORWARD
          } else {
            RouteState::DROP
          },
          RouteState::FORWARD => {
            let _done = send(tok, boundary_out, beat);
            if beat.tlast { RouteState::HEADER } else { RouteState::FORWARD }
          },
          RouteState::DROP =>
            if beat.tlast { RouteState::HEADER } else { RouteState::DROP },
        }
      }
    }

    fn rectangle(frame: BoundaryFrame) -> hls_spatial_router::Rectangle {
      hls_spatial_router::Rectangle {
        x0: frame.payload[0:16] as u16,
        y0: frame.payload[16:32] as u16,
        x1: frame.payload[32:48] as u16,
        y1: frame.payload[48:64] as u16,
      }
    }

    fn header_valid(header: axis::Header) -> u1 {
      let op_and_words = match header.op {
    @HEADER_VALID_ARMS@
        _ => false,
      };
      header.flags == BOUNDARY_VERSION && header.txid == u8:0 && op_and_words
    }

    fn rectangle_valid(bounds: hls_spatial_router::Rectangle) -> u1 {
      hls_spatial_router::valid(bounds) &&
        bounds.x1 < WIDTH && bounds.y1 < DATA_HEIGHT
    }

    fn actor_payload_valid(frame: BoundaryFrame) -> u1 {
      match frame.header.op {
    @PAYLOAD_VALID_ARMS@
        _ => false,
      }
    }

    fn boundary_valid(frame: BoundaryFrame) -> u1 {
      header_valid(frame.header) && rectangle_valid(rectangle(frame)) &&
        actor_payload_valid(frame)
    }

    fn inner_payload_words(op: u8) -> u8 {
      match op {
    @INNER_WORD_ARMS@
        _ => u8:0,
      }
    }

    fn control_target(op: u8) -> u2 {
      match op {
    @CONTROL_TARGET_ARMS@
        _ => u2:0,
      }
    }

    fn spatial_frame(frame: BoundaryFrame) ->
        hls_spatial_router::SpatialFrame {
      let inner = axis::Frame {
        header: axis::Header {
          payload_words: inner_payload_words(frame.header.op),
          op: frame.header.op,
          ..zero!<axis::Header>()
        },
        payload: frame.payload[64:@ACTOR_PAYLOAD_END@] as bits[96],
      };
      hls_spatial_router::SpatialFrame {
        rectangle: rectangle(frame),
        target: control_target(frame.header.op),
        frame: inner,
      }
    }

    proc SpatialIngress {
      boundary_in: chan<BoundaryFrame> in;
      spatial_out: chan<hls_spatial_router::SpatialFrame> out;
      arm_out: chan<u1> out;

      config(
          boundary_in: chan<BoundaryFrame> in,
          spatial_out: chan<hls_spatial_router::SpatialFrame> out,
          arm_out: chan<u1> out
      ) {
        (boundary_in, spatial_out, arm_out)
      }

      init { u1:0 }

      next(armed: u1) {
        let (tok, frame) = recv(join(), boundary_in);
        let valid = boundary_valid(frame);
        let arm_tok = send_if(tok, arm_out, valid && !armed, u1:1);
        let _done = send_if(
          arm_tok, spatial_out, valid, spatial_frame(frame));
        armed || valid
      }
    }

    struct RoutedFrame {
      source: u16,
      frame: axis::Frame,
    }

    fn source_endpoint(cursor: u32) -> u16 {
      match cursor {
    @SOURCE_ENDPOINT_ARMS@
      }
    }

    // Polls one statically indexed input per activation and advances after
    // every attempt, so no continuously active stream can starve another.
    proc FrameMux {
      frame_in: chan<axis::Frame>[@OUTPUT_COUNT@] in;
      routed_out: chan<RoutedFrame> out;

      config(
          frame_in: chan<axis::Frame>[@OUTPUT_COUNT@] in,
          routed_out: chan<RoutedFrame> out
      ) {
        (frame_in, routed_out)
      }

      init { u32:0 }

      next(cursor: u32) {
        let (tok, received, frame) =
          unroll_for! (candidate, acc):
              (u32, (token, u1, axis::Frame)) in u32:0..@OUTPUT_COUNT@ {
            let (next_tok, next_frame, valid) = recv_if_non_blocking(
              acc.0,
              frame_in[candidate],
              cursor == candidate,
              zero!<axis::Frame>());
            (
              next_tok,
              acc.1 | valid,
              if valid { next_frame } else { acc.2 }
            )
          }((join(), u1:0, zero!<axis::Frame>()));
        let routed = RoutedFrame { source: source_endpoint(cursor), frame };
        let _done = send_if(tok, routed_out, received, routed);
        if cursor == @LAST_OUTPUT@ { u32:0 } else { cursor + u32:1 }
      }
    }

    // FrameMux may fill this gate's single upstream holding slot before the
    // first valid command. Nothing reaches RoutedTx until the activation
    // credit arrives, and the full slot backpressures further mux output.
    proc EgressGate {
      frame_in: chan<RoutedFrame> in;
      frame_out: chan<RoutedFrame> out;
      arm_in: chan<u1> in;

      config(
          frame_in: chan<RoutedFrame> in,
          frame_out: chan<RoutedFrame> out,
          arm_in: chan<u1> in
      ) {
        (frame_in, frame_out, arm_in)
      }

      init { u1:0 }

      next(armed: u1) {
        if armed {
          let (tok, frame) = recv(join(), frame_in);
          let _done = send(tok, frame_out, frame);
          armed
        } else {
          let (_tok, arm) = recv(join(), arm_in);
          arm
        }
      }
    }

    fn header_word(header: axis::Header) -> u32 {
      ((header.op as u32) << u32:24) |
        ((header.flags as u32) << u32:16) |
        ((header.txid as u32) << u32:8) |
        header.payload_words as u32
    }

    struct RoutedTxState {
      active: u1,
      route_pending: u1,
      source: u16,
      frame: axis::Frame,
      beats_sent: u8,
    }

    proc RoutedTx {
      frame_in: chan<RoutedFrame> in;
      routed_out: chan<axis::Beat> out;

      config(
          frame_in: chan<RoutedFrame> in,
          routed_out: chan<axis::Beat> out
      ) {
        (frame_in, routed_out)
      }

      init { zero!<RoutedTxState>() }

      next(state: RoutedTxState) {
        let (tok, routed) = recv_if(
          join(), frame_in, !state.active, zero!<RoutedFrame>());
        let state2 = if state.active {
          state
        } else {
          RoutedTxState {
            active: u1:1,
            route_pending: u1:1,
            source: routed.source,
            frame: routed.frame,
            ..zero!<RoutedTxState>()
          }
        };
        let (beat, next_state) = if state2.route_pending {
          let beat = axis::Beat {
            tlast: u1:0,
            word: route_word(state2.source, HOST_ENDPOINT),
          };
          (beat, RoutedTxState { route_pending: u1:0, ..state2 })
        } else {
          let header = axis::Header {
            txid: u8:0,
            flags: BOUNDARY_VERSION,
            ..state2.frame.header
          };
          let last = state2.beats_sent == header.payload_words;
          let word = if state2.beats_sent == u8:0 {
            header_word(header)
          } else {
            state2.frame.payload[
              u8:32 * (state2.beats_sent - u8:1) +: u32]
          };
          let beat = axis::Beat { tlast: last, word };
          let next_state = if last {
            zero!<RoutedTxState>()
          } else {
            let beats_sent = state2.beats_sent + u8:1;
            RoutedTxState { beats_sent, ..state2 }
          };
          (beat, next_state)
        };
        let _done = send(tok, routed_out, beat);
        next_state
      }
    }

    pub proc Top {
      routed_in: chan<axis::Beat> in;
      routed_out: chan<axis::Beat> out;

      config(
          routed_in: chan<axis::Beat> in,
          routed_out: chan<axis::Beat> out
      ) {
        let (boundary_beats_p, boundary_beats_c) =
          chan<axis::Beat, u32:1>("boundary_beats");
        let (boundary_frames_p, boundary_frames_c) =
          chan<BoundaryFrame, u32:1>("boundary_frames");
        let (control_p, control_c) =
          chan<hls_spatial_router::SpatialFrame, u32:1>("control");
        let (arm_p, arm_c) = chan<u1, u32:1>("arm");
        let (topology_outputs_p, topology_outputs_c) =
          chan<axis::Frame, u32:0>[@OUTPUT_COUNT@]("topology_outputs");
        let (pre_gate_p, pre_gate_c) =
          chan<RoutedFrame, u32:1>("pre_gate");
        let (egress_p, egress_c) =
          chan<RoutedFrame, u32:1>("egress");
        spawn RouteIngress(routed_in, boundary_beats_p);
        spawn axis::RxN<@BOUNDARY_WORDS@>(
          boundary_beats_c, boundary_frames_p);
        spawn SpatialIngress(boundary_frames_c, control_p, arm_p);
        spawn @TOPOLOGY@::Top(
          control_c,
    @TOPOLOGY_OUTPUTS@);
        spawn FrameMux(topology_outputs_c, pre_gate_p);
        spawn EgressGate(pre_gate_c, egress_p, arm_c);
        spawn RoutedTx(egress_c, routed_out);
        (routed_in, routed_out)
      }

      init { () }
      next(state: ()) { state }
    }
    """,
    [
        substitute(Template, [
            {"@TOPOLOGY@", atom_to_list(TopologyModule)},
            {"@BOUNDARY_CONSTANTS@", boundary_constants(Contract)},
            {"@BOUNDARY_WORDS@", u32(max_boundary_words(Contract))},
            {"@ACTOR_PAYLOAD_END@",
                integer_to_list(64 + 32 * max_actor_payload_words(Contract))},
            {"@HEADER_VALID_ARMS@", header_valid_arms(Contract)},
            {"@PAYLOAD_VALID_ARMS@", payload_valid_arms(Contract)},
            {"@INNER_WORD_ARMS@", inner_word_arms(Contract)},
            {"@CONTROL_TARGET_ARMS@", control_target_arms(Contract)},
            {"@SOURCE_ENDPOINT_ARMS@", source_endpoint_arms(Contract)},
            {"@OUTPUT_COUNT@", u32(length(maps:get(outputs, Contract)))},
            {"@LAST_OUTPUT@", u32(length(maps:get(outputs, Contract)) - 1)},
            {"@TOPOLOGY_OUTPUTS@", topology_outputs(Contract)}
        ]),
        "\n"
    ].

boundary_constants(Contract = #{
    version := Version,
    host_endpoint := Host,
    ingress := #{endpoint := Gateway},
    outputs := Outputs
}) ->
    lists:droplast(lists:flatten([
        constant("BOUNDARY_VERSION", "u8", Version),
        constant("HOST_ENDPOINT", "u16", Host),
        constant("GATEWAY_ENDPOINT", "u16", Gateway),
        [
            constant(endpoint_constant(Id), "u16", Endpoint)
            || #{id := Id, endpoint := Endpoint} <- Outputs
        ],
        [
            constant(op_constant(Name), "u8", Selector)
            || #{name := Name, selector := Selector} <- command_schemas(Contract)
        ]
    ])).

constant(Name, Type, Value) ->
    ["const ", Name, " = ", Type, ":", integer_to_list(Value), ";\n"].

header_valid_arms(Contract) ->
    join_with("\n", [
        ["    ", op_constant(Name),
            " => header.payload_words == u8:",
            integer_to_list(2 + Words), ","]
        || #{name := Name, payload_words := Words} <- command_schemas(Contract)
    ]).

payload_valid_arms(Contract) ->
    join_with("\n", [
        payload_valid_arm(Schema) || Schema <- command_schemas(Contract)
    ]).

payload_valid_arm(#{name := noise_cutoff}) ->
    ["    ", op_constant(noise_cutoff), " => true,"];
payload_valid_arm(#{name := Name, payload_words := Words})
        when Name =:= pauli_query; Name =:= pauli_update ->
    Start = 64 + 32 * (Words - 1),
    ["    ", op_constant(Name), " => frame.payload[",
        integer_to_list(Start), ":", integer_to_list(Start + 32),
        "] as u32 <= u32:3,"].

inner_word_arms(Contract) ->
    join_with("\n", [
        ["    ", op_constant(Name), " => u8:",
            integer_to_list(Words), ","]
        || #{name := Name, payload_words := Words} <- command_schemas(Contract)
    ]).

control_target_arms(#{ingress := #{targets := Targets}}) ->
    join_with("\n", [
        ["    ", op_constant(Name), " => u2:",
            integer_to_list(Index), ","]
        || #{index := Index, schemas := Schemas} <- Targets,
           #{name := Name} <- Schemas
    ]).

source_endpoint_arms(#{outputs := Outputs}) ->
    {Initial, [Last]} = lists:split(length(Outputs) - 1, Outputs),
    InitialArms = [
            ["    u32:", integer_to_list(Index), " => ",
                endpoint_constant(Id), ","]
            || {Index, #{id := Id}} <- lists:enumerate(0, Initial)
    ],
    LastArm = ["    _ => ", endpoint_constant(maps:get(id, Last)), ","],
    join_with("\n", InitialArms ++ [LastArm]).

topology_outputs(#{outputs := Outputs}) ->
    join_with(
        ",\n",
        [
            ["      topology_outputs_p[u32:",
                integer_to_list(Index), "]"]
            || {Index, _Output} <- lists:enumerate(0, Outputs)
        ]
    ).

max_boundary_words(Contract) ->
    2 + max_actor_payload_words(Contract).

max_actor_payload_words(Contract) ->
    lists:max([
        Words
        || #{payload_words := Words} <- command_schemas(Contract)
    ]).

command_schemas(#{ingress := #{targets := Targets}}) ->
    lists:append([maps:get(schemas, Target) || Target <- Targets]).

endpoint_constant(Id) ->
    string:uppercase(atom_to_list(Id)) ++ "_ENDPOINT".

op_constant(Name) ->
    "OP_" ++ string:uppercase(atom_to_list(Name)).

u32(Value) ->
    ["u32:", integer_to_list(Value)].

substitute(Source, Replacements) ->
    lists:foldl(
        fun({Marker, Value}, Current) ->
            lists:flatten(string:replace(
                Current,
                Marker,
                lists:flatten(Value),
                all
            ))
        end,
        Source,
        Replacements
    ).

join_with(_Separator, []) -> [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].
