%%%% phi_memory_gateway_dslx
%%%%
%%%% Routed AXI-stream boundary for the phi memory experiment.

-module(phi_memory_gateway_dslx).
-moduledoc """
Generates the routed AXI-stream gateway around one phi/noise topology.

The checked artifact imports the distance-three topology. `to_dslx/1` also
emits the staging-only distance-one wrapper without flattening either imported
topology into the gateway source.

This generator renders only phi-specific boundary policy and composition.
Endpoint allocation, external order, message selectors, payload widths, target
selectors, and frame capacity come from `phi_memory_boundary`. Reusable routed
packet ingress, activation gating, and frame transmission live in
`hls_fabric_router.x`.

Malformed routes and frames are drained without actor delivery. Until the
gateway has a typed connection-fault sideband, the host observes that rejection
through the experiment timeout rather than an invented application reply.
""".

-export([to_dslx/0, to_dslx/1]).

-doc "Generates the checked distance-three gateway.".
-spec to_dslx() -> iolist().
to_dslx() ->
    to_dslx(3).

-doc "Generates the gateway for a checked or staging topology module.".
-spec to_dslx(1 | 3) -> iolist().
to_dslx(1) ->
    emit(1, phi_noise_topology_smoke, phi_memory_gateway_smoke);
to_dslx(3) ->
    emit(3, phi_noise_topology, phi_memory_gateway);
to_dslx(_Distance) ->
    error(badarg).

emit(Distance, TopologyModule, Artifact) ->
    Contract = phi_memory_boundary:contract(Distance),
    [
        "// ", atom_to_list(Artifact), ".x\n",
        "// Auto-generated by phi_memory_gateway_dslx.\n",
        "// Manual changes will be overwritten.\n\n",
        "import axis;\n",
        "import hls_fabric_router;\n",
        "import hls_spatial_router;\n",
        [["import ", Module, ";\n"]
            || Module <- lists:usort([
                Name || {_Stem, Name} <- scheduler_ram_bindings()
            ])],
        "import ", atom_to_list(TopologyModule), ";\n\n",
        "const WIDTH = u16:", integer_to_list(Distance), ";\n",
        "const HEIGHT = u16:", integer_to_list(Distance), ";\n",
        body(TopologyModule, Contract)
    ].

body(TopologyModule, Contract) ->
    [
        boundary_declarations(Contract),
        boundary_policy(Contract),
        spatial_ingress(), "\n",
        frame_mux(Contract),
        top_proc(TopologyModule, Contract)
    ].

boundary_declarations(Contract) ->
    [
        "const DATA_HEIGHT = HEIGHT * u16:2;\n",
        boundary_constants(Contract),
        "\n",
        "type BoundaryFrame = axis::FrameN<",
        u32(max_boundary_words(Contract)),
        ">;\n\n"
    ].

boundary_policy(Contract) ->
    [
        render_rectangle(), "\n",
        render_header_valid(Contract),
        render_rectangle_valid(), "\n",
        render_payload_valid(Contract),
        render_boundary_valid(), "\n",
        render_inner_payload_words(Contract),
        render_control_target(Contract),
        render_spatial_frame(Contract)
    ].

render_rectangle() ->
    """
    fn rectangle(frame: BoundaryFrame) -> hls_spatial_router::Rectangle {
      hls_spatial_router::Rectangle {
        x0: frame.payload[0:16] as u16,
        y0: frame.payload[16:32] as u16,
        x1: frame.payload[32:48] as u16,
        y1: frame.payload[48:64] as u16,
      }
    }

    """.

render_header_valid(Contract) ->
    [
        "fn header_valid(header: axis::Header) -> u1 {\n",
        "  let op_and_words = match header.op {\n",
        header_valid_arms(Contract), "\n",
        "    _ => false,\n",
        "  };\n",
        "  header.flags == BOUNDARY_VERSION && header.txid == u8:0 && ",
        "op_and_words\n",
        "}\n\n"
    ].

render_rectangle_valid() ->
    """
    fn rectangle_valid(bounds: hls_spatial_router::Rectangle) -> u1 {
      hls_spatial_router::valid(bounds) &&
        bounds.x1 < WIDTH && bounds.y1 < DATA_HEIGHT
    }

    """.

render_payload_valid(Contract) ->
    [
        "fn actor_payload_valid(frame: BoundaryFrame) -> u1 {\n",
        "  match frame.header.op {\n",
        payload_valid_arms(Contract), "\n",
        "    _ => false,\n",
        "  }\n",
        "}\n\n"
    ].

render_boundary_valid() ->
    """
    fn boundary_valid(frame: BoundaryFrame) -> u1 {
      header_valid(frame.header) && rectangle_valid(rectangle(frame)) &&
        actor_payload_valid(frame)
    }

    """.

render_inner_payload_words(Contract) ->
    [
        "fn inner_payload_words(op: u8) -> u8 {\n",
        "  match op {\n",
        inner_word_arms(Contract), "\n",
        "    _ => u8:0,\n",
        "  }\n",
        "}\n\n"
    ].

render_control_target(Contract) ->
    [
        "fn control_target(op: u8) -> u2 {\n",
        "  match op {\n",
        control_target_arms(Contract), "\n",
        "    _ => u2:0,\n",
        "  }\n",
        "}\n\n"
    ].

render_spatial_frame(Contract) ->
    ActorPayloadEnd = 64 + 32 * max_actor_payload_words(Contract),
    [
        "fn spatial_frame(frame: BoundaryFrame) ->\n",
        "    hls_spatial_router::SpatialFrame {\n",
        "  let inner = axis::Frame {\n",
        "    header: axis::Header {\n",
        "      payload_words: inner_payload_words(frame.header.op),\n",
        "      op: frame.header.op,\n",
        "      ..zero!<axis::Header>()\n",
        "    },\n",
        "    payload: frame.payload[64:", integer_to_list(ActorPayloadEnd),
        "] as bits[96],\n",
        "  };\n",
        "  hls_spatial_router::SpatialFrame {\n",
        "    rectangle: rectangle(frame),\n",
        "    target: control_target(frame.header.op),\n",
        "    frame: inner,\n",
        "  }\n",
        "}\n\n"
    ].

spatial_ingress() ->
    """
    proc SpatialIngress {
      boundary_in: chan<BoundaryFrame> in;
      spatial_out: chan<hls_spatial_router::SpatialFrame> out;
      arm_out: chan<u1> out;

      config(
          boundary_in: chan<BoundaryFrame> in,
          spatial_out: chan<hls_spatial_router::SpatialFrame> out,
          arm_out: chan<u1> out
      ) {
        (boundary_in, spatial_out, arm_out)
      }

      init { u1:0 }

      next(armed: u1) {
        let (tok, frame) = recv(join(), boundary_in);
        let valid = boundary_valid(frame);
        let arm_tok = send_if(tok, arm_out, valid && !armed, u1:1);
        let _done = send_if(
          arm_tok, spatial_out, valid, spatial_frame(frame));
        armed || valid
      }
    }

    """.

frame_mux(Contract = #{outputs := Outputs}) ->
    OutputCount = length(Outputs),
    [
        "fn source_endpoint(cursor: u32) -> u16 {\n",
        "  match cursor {\n",
        source_endpoint_arms(Contract), "\n",
        "  }\n",
        "}\n\n",
        "// Polls one statically indexed input per activation and advances ",
        "after\n",
        "// every attempt, so no continuously active stream can starve ",
        "another.\n",
        "proc FrameMux {\n",
        "  frame_in: chan<axis::Frame>[", u32(OutputCount), "] in;\n",
        "  routed_out: chan<hls_fabric_router::RoutedFrame> out;\n\n",
        "  config(\n",
        "      frame_in: chan<axis::Frame>[", u32(OutputCount), "] in,\n",
        "      routed_out: chan<hls_fabric_router::RoutedFrame> out\n",
        "  ) {\n",
        "    (frame_in, routed_out)\n",
        "  }\n\n",
        "  init { u32:0 }\n\n",
        "  next(cursor: u32) {\n",
        "    let (tok, received, frame) =\n",
        "      unroll_for! (candidate, acc):\n",
        "          (u32, (token, u1, axis::Frame)) in u32:0..",
        u32(OutputCount), " {\n",
        "        let (next_tok, next_frame, valid) = recv_if_non_blocking(\n",
        "          acc.0,\n",
        "          frame_in[candidate],\n",
        "          cursor == candidate,\n",
        "          zero!<axis::Frame>());\n",
        "        (\n",
        "          next_tok,\n",
        "          acc.1 | valid,\n",
        "          if valid { next_frame } else { acc.2 }\n",
        "        )\n",
        "      }((join(), u1:0, zero!<axis::Frame>()));\n",
        "    let boundary_frame = axis::Frame {\n",
        "      header: axis::Header {\n",
        "        txid: u8:0,\n",
        "        flags: BOUNDARY_VERSION,\n",
        "        ..frame.header\n",
        "      },\n",
        "      ..frame\n",
        "    };\n",
        "    let routed = hls_fabric_router::RoutedFrame {\n",
        "      source: source_endpoint(cursor),\n",
        "      frame: boundary_frame,\n",
        "    };\n",
        "    let _done = send_if(tok, routed_out, received, routed);\n",
        "    if cursor == ", u32(OutputCount - 1),
        " { u32:0 } else { cursor + u32:1 }\n",
        "  }\n",
        "}\n\n"
    ].

top_proc(TopologyModule, Contract = #{outputs := Outputs}) ->
    OutputCount = length(Outputs),
    RamMembers = scheduler_ram_members(),
    RamNames = scheduler_ram_names(),
    [
        "pub proc Top {\n",
        [["  ", Member, ";\n"] || Member <- RamMembers],
        "  routed_in: chan<axis::Beat> in;\n",
        "  routed_out: chan<axis::Beat> out;\n\n",
        "  config(\n",
        [["      ", Member, ",\n"] || Member <- RamMembers],
        "      routed_in: chan<axis::Beat> in,\n",
        "      routed_out: chan<axis::Beat> out\n",
        "  ) {\n",
        "    let (boundary_beats_p, boundary_beats_c) =\n",
        "      chan<axis::Beat, u32:1>(\"boundary_beats\");\n",
        "    let (boundary_frames_p, boundary_frames_c) =\n",
        "      chan<BoundaryFrame, u32:1>(\"boundary_frames\");\n",
        "    let (control_p, control_c) =\n",
        "      chan<hls_spatial_router::SpatialFrame, u32:1>(\"control\");\n",
        "    let (arm_p, arm_c) = chan<u1, u32:1>(\"arm\");\n",
        "    let (topology_outputs_p, topology_outputs_c) =\n",
        "      chan<axis::Frame, u32:0>[", u32(OutputCount),
        "](\"topology_outputs\");\n",
        "    let (pre_gate_p, pre_gate_c) =\n",
        "      chan<hls_fabric_router::RoutedFrame, u32:1>(\"pre_gate\");\n",
        "    let (egress_p, egress_c) =\n",
        "      chan<hls_fabric_router::RoutedFrame, u32:1>(\"egress\");\n",
        "    spawn hls_fabric_router::EndpointIngress<\n",
        "      HOST_ENDPOINT, GATEWAY_ENDPOINT\n",
        "    >(routed_in, boundary_beats_p);\n",
        "    spawn axis::RxN<", u32(max_boundary_words(Contract)), ">(\n",
        "      boundary_beats_c, boundary_frames_p);\n",
        "    spawn SpatialIngress(boundary_frames_c, control_p, arm_p);\n",
        "    spawn ", atom_to_list(TopologyModule), "::Top(\n",
        [["      ", Name, ",\n"] || Name <- RamNames],
        "      control_c,\n",
        topology_outputs(Contract), ");\n",
        "    spawn FrameMux(topology_outputs_c, pre_gate_p);\n",
        "    spawn hls_fabric_router::EgressGate(\n",
        "      pre_gate_c, egress_p, arm_c);\n",
        "    spawn hls_fabric_router::RoutedTx<HOST_ENDPOINT>(\n",
        "      egress_c, routed_out);\n",
        "    (", join_with(", ", RamNames ++
            ["routed_in", "routed_out"]), ")\n",
        "  }\n\n",
        "  init { () }\n",
        "  next(state: ()) { state }\n",
        "}\n"
    ].

scheduler_ram_members() ->
    lists:append([
        [
            [Stem, "_ram_req_out: chan<", Module,
                "::MachineRamReq> out"],
            [Stem, "_ram_resp_in: chan<", Module,
                "::MachineRamResp> in"],
            [Stem, "_ram_wr_comp_in: chan<()> in"],
            [Stem, "_mailbox_req_out: chan<", Module,
                "::MailboxRamReq> out"],
            [Stem, "_mailbox_resp_in: chan<", Module,
                "::MailboxRamResp> in"],
            [Stem, "_mailbox_wr_comp_in: chan<()> in"]
        ]
        || {Stem, Module} <- scheduler_ram_bindings()
    ]).

scheduler_ram_names() ->
    lists:append([
        [
            [Stem, "_ram_req_out"],
            [Stem, "_ram_resp_in"],
            [Stem, "_ram_wr_comp_in"],
            [Stem, "_mailbox_req_out"],
            [Stem, "_mailbox_resp_in"],
            [Stem, "_mailbox_wr_comp_in"]
        ]
        || {Stem, _Module} <- scheduler_ram_bindings()
    ]).

scheduler_ram_bindings() ->
    #{groups := Groups} = phi_noise_topology_dslx:scheduler_plan(),
    [
        {["scheduler_", integer_to_list(Index)], atom_to_list(Module)}
        || {Index, #{module := Module}} <- lists:enumerate(0, Groups)
    ].

boundary_constants(#{
    version := Version,
    host_endpoint := Host,
    ingress := #{endpoint := Gateway},
    outputs := Outputs
} = Contract) ->
    [
        constant("BOUNDARY_VERSION", "u8", Version),
        constant("HOST_ENDPOINT", "u16", Host),
        constant("GATEWAY_ENDPOINT", "u16", Gateway),
        [
            constant(endpoint_constant(Id), "u16", Endpoint)
            || #{id := Id, endpoint := Endpoint} <- Outputs
        ],
        [
            constant(op_constant(Name), "u8", Selector)
            || #{name := Name, selector := Selector} <- command_schemas(Contract)
        ]
    ].

constant(Name, Type, Value) ->
    ["const ", Name, " = ", Type, ":", integer_to_list(Value), ";\n"].

header_valid_arms(Contract) ->
    join_with("\n", [
        ["    ", op_constant(Name),
            " => header.payload_words == u8:",
            integer_to_list(2 + Words), ","]
        || #{name := Name, payload_words := Words} <- command_schemas(Contract)
    ]).

payload_valid_arms(Contract) ->
    join_with("\n", [
        payload_valid_arm(Schema) || Schema <- command_schemas(Contract)
    ]).

payload_valid_arm(#{name := noise_cutoff}) ->
    ["    ", op_constant(noise_cutoff), " => true,"];
payload_valid_arm(#{name := Name, payload_words := Words})
        when Name =:= pauli_query; Name =:= pauli_update ->
    Start = 64 + 32 * (Words - 1),
    ["    ", op_constant(Name), " => frame.payload[",
        integer_to_list(Start), ":", integer_to_list(Start + 32),
        "] as u32 <= u32:3,"].

inner_word_arms(Contract) ->
    join_with("\n", [
        ["    ", op_constant(Name), " => u8:",
            integer_to_list(Words), ","]
        || #{name := Name, payload_words := Words} <- command_schemas(Contract)
    ]).

control_target_arms(#{ingress := #{targets := Targets}}) ->
    join_with("\n", [
        ["    ", op_constant(Name), " => u2:",
            integer_to_list(Index), ","]
        || #{index := Index, schemas := Schemas} <- Targets,
           #{name := Name} <- Schemas
    ]).

source_endpoint_arms(#{outputs := Outputs}) ->
    {Initial, [Last]} = lists:split(length(Outputs) - 1, Outputs),
    InitialArms = [
        ["    u32:", integer_to_list(Index), " => ",
            endpoint_constant(Id), ","]
        || {Index, #{id := Id}} <- lists:enumerate(0, Initial)
    ],
    LastArm = ["    _ => ", endpoint_constant(maps:get(id, Last)), ","],
    join_with("\n", InitialArms ++ [LastArm]).

topology_outputs(#{outputs := Outputs}) ->
    join_with(",\n", [
        ["      topology_outputs_p[u32:", integer_to_list(Index), "]"]
        || {Index, _Output} <- lists:enumerate(0, Outputs)
    ]).

max_boundary_words(Contract) ->
    2 + max_actor_payload_words(Contract).

max_actor_payload_words(Contract) ->
    lists:max([
        Words
        || #{payload_words := Words} <- command_schemas(Contract)
    ]).

command_schemas(#{ingress := #{targets := Targets}}) ->
    lists:append([maps:get(schemas, Target) || Target <- Targets]).

endpoint_constant(Id) ->
    string:uppercase(atom_to_list(Id)) ++ "_ENDPOINT".

op_constant(Name) ->
    "OP_" ++ string:uppercase(atom_to_list(Name)).

u32(Value) ->
    ["u32:", integer_to_list(Value)].

join_with(_Separator, []) -> [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].
