-module(xls_actor_codegen).
-moduledoc false.
-export([emit/3, entry_value/5, input_tag_ok/3, reply_failure_binding/1]).
-export_type([spec/0]).
-define(REDUCTION_SERVICE, xls_statem_reduction_service_codegen).
%% One phase's checked evaluation and possible ordered effect layouts.
-type entry() :: #{
    phase := atom(),
    evaluation := #{body := iodata(), result := iodata(), failed := iodata(), failure := iodata()},
    layouts := [map()]
}.
%% Lowered dispatch arm for one phase and message schema.
-type cast_clause() :: #{
    tag := atom(),
    phase := atom(),
    body := iodata(),
    result := iodata()
}.
%% Complete renderer input, including the emitted failure-site catalog.
-doc "Validated actor rendering input; extra annotations belong to the selected execution backend.".
-type spec() :: #{
    failure_sites := [map()],
    source := file:filename(),
    imports := [atom()],
    capacity := 1..255,
    phases := [atom(), ...],
    message_names := [atom(), ...],
    message_words := #{atom() => 0..3},
    output_names := [atom(), ...],
    data_name := atom(),
    data_width := non_neg_integer(),
    record_declarations := iodata(),
    helper_functions := iodata(),
    init := xls_init:lowered(),
    entries := [entry(), ...],
    max_entry_effects := non_neg_integer(),
    casts := [cast_clause()],
    continuations := [atom()],
    internal_steps := [map()],
    retained_calls := none | map(),
    reductions := none | xls_statem_reduction_ir:reduction(),
    direct_actor_debug => boolean(),
    atom() => term()
}.


-doc "Renders checked callback semantics and a supplied execution body into one DSLX module.".
-spec emit(spec(), [atom()], iodata()) -> iolist().
emit(Spec, RuntimeImports, Body) ->
    Reductions = maps:get(reductions, Spec, none),
    Common = [maps:get(record_declarations, Spec), maps:get(helper_functions, Spec),
        xls_statem_reduction_codegen:declarations(Reductions),
        xls_statem_reply_codegen:declarations(Spec), declarations(Spec),
        xls_statem_reduction_codegen:functions(Reductions),
        xls_init:emit("initial_actor_state", "ActorState", maps:get(init, Spec)),
        enter_function(Spec), entry_effects_valid_function(),
        xls_statem_reply_codegen:functions(Spec), dispatch_function(Spec),
        xls_statem_event_codegen:functions(Spec), Body],
    [preamble(Spec, RuntimeImports),
        xls_failure_sites:emit(maps:get(failure_sites, Spec, []), Common)].

%%%
%%% Module declarations
%%%

%% Declares the actor vocabulary and imports optional runtime modules.
-spec preamble(spec(), [atom()]) -> iodata().
preamble(#{
    source := Source,
    imports := Imports,
    capacity := Capacity,
    phases := Phases,
    message_names := MessageNames,
    data_name := DataName
} = Spec, RuntimeImports) ->
    Reductions = maps:get(reductions, Spec, none),
    [
        "// ", Source, ".x\n",
        "// This file is auto-generated by xls_parse. Manual changes will be\n",
        "// overwritten the next time it is generated.\n\n",
        xls_dslx_imports:emit([axis, hls_failure, hls_bits] ++ RuntimeImports ++
            case xls_statem_reply_codegen:enabled(Spec) of true -> [hls_reply]; false -> [] end, Imports),
        "\n",
        "const MAILBOX_CAPACITY = u8:", integer_to_list(Capacity), ";\n",
        "const MAILBOX_DEPTH = u32:", integer_to_list(Capacity), ";\n\n",
        "pub enum Tag : u8 {\n",
        "  NONE = u8:0,\n",
        "  ERROR = u8:1,\n",
        "  ", xls_names:enum_member(DataName), " = u8:2,\n",
        [
            [
                "  ", xls_names:enum_member(Name), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Name} <- lists:enumerate(3, MessageNames)
        ],
        reduction_tag_member(Reductions, MessageNames),
        "}\n\n",
        phase_declaration(Phases),
        "pub enum Directive : u2 {\n",
        "  CONSUME = u2:0,\n",
        "  POSTPONE = u2:1,\n",
        "  FAIL = u2:2,\n",
        "}\n\n"
    ].
%% Defines the typed values exchanged by callbacks and their execution backend.
-spec declarations(spec()) -> iodata().
declarations(#{output_names := OutputNames, max_entry_effects := MaxEntryEffects,
        message_words := MessageWords, entries := Entries, data_name := DataName} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    DataStruct = xls_names:record_type(DataName),
    EffectCapacity = max(1, MaxEntryEffects),
    EffectPayloadBits = max(entry_effect_payload_bits(Entries, MessageWords),
        case xls_statem_reply_codegen:enabled(Spec) of true -> 128; false -> 0 end),
    [
        "pub enum OutputPort : u8 {\n",
        [
            [
                "  ", xls_names:enum_member(Port), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Port} <- lists:enumerate(0, OutputNames)
        ],
        "}\n\n",
        "pub struct Egress {\n",
        "  port: OutputPort,\n",
        "  frame: axis::Frame,\n",
        "}\n\n",
        "pub const EGRESS_DEPTH = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub const ENTRY_EFFECT_CAPACITY = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub const ENTRY_EFFECT_PAYLOAD_BITS = u32:",
        integer_to_list(EffectPayloadBits), ";\n\n",
        "// Sorry: this is a hand-rolled tagged union. DSLX cannot yet express\n",
        "// entry variants whose fields retain their message types.\n",
        "pub struct EntryEffects {\n",
        "  layout: u8,\n",
        "  payloads: bits[", integer_to_list(EffectPayloadBits), "],\n",
        "}\n\n",
        "struct EntryOutcome {\n",
        "  data: ", DataStruct, ",\n",
        "  effects: EntryEffects,\n",
        ?REDUCTION_SERVICE:machine_state_field(Reductions),
        "  failure: hls_failure::Code,\n",
        "}\n\n",
        "struct ActorState {\n",
        "  phase: Phase,\n",
        "  entered_from: Phase,\n",
        "  data: ", DataStruct, ",\n",
        ?REDUCTION_SERVICE:machine_state_field(Reductions),
        xls_statem_reply_codegen:optional(Spec, "  replies: ReplyBook,\n"),
        xls_statem_event_codegen:optional(Spec, "  next_event: u8,\n"),
        "  enter_pending: u1,\n",
        "  failure: hls_failure::Code,\n",
        "}\n\n",
        "struct ActorDispatch {\n",
        xls_statem_reply_codegen:optional(Spec, "  reply: axis::Frame,\n  reply_valid: bool,\n"),
        "  machine: ActorState,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "}\n\n"
    ].

%% Allocates the private completion selector after public message tags, rejecting overflow.
-spec reduction_tag_member(none | xls_statem_reduction_ir:reduction(), [atom()]) -> iodata().
reduction_tag_member(none, _MessageNames) ->
    [];
reduction_tag_member(Reductions, MessageNames)
        when length(MessageNames) =< 252 ->
    xls_statem_reduction_codegen:tag_member(
        Reductions,
        3 + length(MessageNames)
    );
reduction_tag_member(_Reductions, MessageNames) ->
    error({too_many_hls_tags_for_reduction, length(MessageNames), 252}).

%% Assigns stable selectors in declared phase order.
-spec phase_declaration([atom()]) -> iodata().
phase_declaration(Phases) ->
    [
        "enum Phase : u8 {\n",
        [
            [
                "  ", xls_names:enum_member(Name), " = u8:", integer_to_list(Index),
                ",\n"
            ]
            || {Index, Name} <- lists:enumerate(0, Phases)
        ],
        "}\n\n"
    ].

%% Evaluates one checked phase entry and encodes its selected effect layout.
-spec enter_function(spec()) -> iodata().
enter_function(#{data_name := DataName, entries := Entries,
        message_words := MessageWords} = Spec) ->
    Layouts = entry_layouts(Entries),
    [
        "fn enter(old_phase: Phase, phase: Phase, data: ", xls_names:record_type(DataName),
        ") -> EntryOutcome {\n",
        "  match phase {\n",
        [entry_arm(Entry) || Entry <- Entries],
        "  }\n",
        "}\n\n",
        entry_effect_count_function(Layouts, Spec),
        entry_effect_function(Layouts, MessageWords, Spec)
    ].

%% Selects a phase entry and preserves its first evaluated failure.
-spec entry_arm(entry()) -> iodata().
entry_arm(#{phase := Phase,
        evaluation := #{body := Body, result := Result, failed := Failed, failure := Failure}}) ->
    [
        "    Phase::", xls_names:enum_member(Phase), " => {\n",
        xls_parse_io:indent(Body, 6),
        "      if ", Failed, " {\n",
        "        EntryOutcome { data, failure: ", Failure, ", ..zero!<EntryOutcome>() }\n",
        "      } else { ", Result, " }\n",
        "    },\n"
    ].

%% Each selected source leaf becomes the same typed value before control flow
%% rejoins. The expression lowerer still owns branch-local failure predicates.
-doc "Encodes one selected entry result and ordered effects without reevaluating payloads.".
-spec entry_value(iodata(), map(), pos_integer(), map(),
    none | map()) -> iodata().
entry_value(Result, #{phase := Phase, layout := Layout,
        actions := Effects, reduction := Reduction}, PayloadBits,
        MessageWords, Reductions) ->
    [
        "{\n",
        "  let evaluated = ", Result, ";\n",
        [entry_effect_binding(Index) || {Index, _} <- lists:enumerate(0, Effects)],
        "  EntryOutcome {\n",
        "    data: evaluated.0.1,\n",
        entry_reduction_field(Reductions, Reduction =/= none, Phase),
        "    failure: hls_failure::NONE,\n",
        "    effects: EntryEffects {\n",
        "      layout: u8:", integer_to_list(Layout), ",\n",
        "      payloads: ", entry_payload_expression(Effects, PayloadBits, MessageWords), ",\n",
        "    },\n",
        "  }\n",
        "}"
    ].

%% Initializes the selected reduction open or preserves the absence of an open.
-spec entry_reduction_field(term(),boolean(),term()) -> iodata().
entry_reduction_field(none, false, _Phase) -> [];
entry_reduction_field(_Reductions, false, _Phase) ->
    "    reduction: zero!<ReductionState>(),\n";
entry_reduction_field(_Reductions, true, Phase) ->
    ["    reduction: reduction_open_site(ReductionSite::", xls_names:enum_member(Phase),
        ", evaluated.1.0, evaluated.1.1.1),\n"].

%% Collects the finite effect alternatives across all phase entries.
-spec entry_layouts([entry()]) -> [map()].
entry_layouts(Entries) ->
    lists:append([Layouts || #{layouts := Layouts} <- Entries]).

%% Counts the selected entry batch, including a reserved single-reply layout.
-spec entry_effect_count_function([map()], spec()) -> iodata().
entry_effect_count_function(Layouts, Spec) ->
    [
        "fn entry_effect_count(effects: EntryEffects) -> u8 {\n",
        "  match effects.layout {\n",
        [["    u8:", integer_to_list(Layout), " => u8:",
            integer_to_list(length(Actions)), ",\n"]
            || #{layout := Layout, actions := Actions} <- Layouts],
        reply_layout_count(Spec),
        "    _ => u8:0,\n",
        "  }\n",
        "}\n\n"
    ].

%% Decodes a selected effect into its statically routed output frame.
-spec entry_effect_function([map()], map(), spec()) -> iodata().
entry_effect_function(Layouts, MessageWords, Spec) ->
    [
        "fn entry_effect(effects: EntryEffects, index: u8) -> Egress {\n",
        "  match effects.layout {\n",
        [entry_effect_layout_arm(Layout, MessageWords) || Layout <- Layouts],
        reply_layout_effect(Spec),
        "    _ => zero!<Egress>(),\n",
        "  }\n",
        "}\n\n"
    ].

%% Selects the ordered effect list represented by a layout tag.
-spec entry_effect_layout_arm(map(), #{atom() => non_neg_integer()}) -> iodata().
entry_effect_layout_arm(#{layout := Layout, actions := []}, _MessageWords) ->
    ["    u8:", integer_to_list(Layout), " => zero!<Egress>(),\n"];
entry_effect_layout_arm(#{layout := Layout, actions := Effects}, MessageWords) ->
    [
        "    u8:", integer_to_list(Layout), " => match index {\n",
        [entry_effect_index_arm(Index, Effect, Offset, MessageWords)
            || {Index, Effect, Offset} <- effect_offsets(Effects, MessageWords)],
        "      _ => zero!<Egress>(),\n",
        "    },\n"
    ].

%% Recovers one output port and frame from its packed effect offset.
-spec entry_effect_index_arm(non_neg_integer(), map(), non_neg_integer(), #{atom() => non_neg_integer()}) -> iodata().
entry_effect_index_arm(Index, Effect, Offset, MessageWords) ->
    Tag = maps:get(tag, Effect),
    Width = maps:get(Tag, MessageWords) * 32,
    [
        "      u8:", integer_to_list(Index), " => Egress {\n",
        "        port: OutputPort::", xls_names:enum_member(maps:get(port, Effect)), ",\n",
        "        frame: axis::pack(Tag::", xls_names:enum_member(Tag), " as u8,\n",
        "          effects.payloads[", integer_to_list(Offset), ":",
        integer_to_list(Offset + Width), "]),\n",
        "      },\n"
    ].

%% TODO(XLS sum types): replace layout IDs, effect_offsets/2, and the raw-bit
%% payload codecs with a sum of typed ordered-message tuples. Keep storage at
%% the widest alternative (including its tag), not the sum of alternatives.
%% Then entry_effect/2 can pattern-match typed payloads instead of slicing bits.
%% Bounded path analysis and the topology's unconditional-prefix proof remain
%% necessary. See Roadmap.md, "XLS complaints".
-spec entry_payload_expression([map()], pos_integer(), #{atom() => non_neg_integer()}) -> iodata().
entry_payload_expression([], EffectPayloadBits, _MessageWords) ->
    ["zero!<bits[", integer_to_list(EffectPayloadBits), "]>()"];
entry_payload_expression(Effects, EffectPayloadBits, MessageWords) ->
    lists:foldl(
        fun({Index, Effect, Offset}, Acc) ->
            Width = maps:get(maps:get(tag, Effect), MessageWords) * 32,
            ["bit_slice_update(\n",
                "          ", Acc, ",\n",
                "          u32:", integer_to_list(Offset), ",\n",
                "          effect_", integer_to_list(Index),
                ".payload[0:", integer_to_list(Width), "])"]
        end,
        ["zero!<bits[", integer_to_list(EffectPayloadBits), "]>()"],
        effect_offsets(Effects, MessageWords)
    ).

%% Assigns nonoverlapping payload slices in source order.
-spec effect_offsets([map()], #{atom() => non_neg_integer()}) -> [{non_neg_integer(), map(), non_neg_integer()}].
effect_offsets(Effects, MessageWords) ->
    {_End, Reversed} = lists:foldl(
        fun({Index, Effect}, {Offset, Acc}) ->
            Width = maps:get(maps:get(tag, Effect), MessageWords) * 32,
            {Offset + Width, [{Index, Effect, Offset} | Acc]}
        end,
        {0, []},
        lists:enumerate(0, Effects)
    ),
    lists:reverse(Reversed).

%% Sizes storage for the largest alternative, with at least one bit.
-spec entry_effect_payload_bits([entry()], #{atom() => non_neg_integer()}) -> pos_integer().
entry_effect_payload_bits(Entries, MessageWords) ->
    max(1, lists:max([
        lists:sum([
            maps:get(maps:get(tag, Effect), MessageWords) * 32
            || Effect <- maps:get(actions, Layout)
        ])
        || Layout <- entry_layouts(Entries)
    ])).

%% Recognizes batches that contain at least one effect.
-spec entry_effects_valid_function() -> iodata().
entry_effects_valid_function() ->
    [
        """
        fn entry_effects_valid(effects: EntryEffects) -> u1 {
          entry_effect_count(effects) != u8:0
        }

        """,
        "\n"
    ].

%% Captures one evaluated payload as a frame before packing the batch.
-spec entry_effect_binding(integer()) -> iodata().
entry_effect_binding(Index) ->
    Reference = ["evaluated.2.", integer_to_list(Index)],
    [
        "        let effect_", integer_to_list(Index), " = axis::pack(\n",
        "          ", Reference, ".0 as u8, hls_bits::frame_payload(", Reference, ".2));\n"
    ].

%% Dispatches declared input records with optional caller ownership.
-spec dispatch_function(spec()) -> iodata().
dispatch_function(#{
    message_names := MessageNames,
    data_name := DataName,
    casts := Casts
} = Spec) ->
    DataStruct = xls_names:record_type(DataName),
    [
        "fn dispatch(frame: axis::Frame, phase: Phase, data: ", DataStruct,
        xls_statem_reply_codegen:optional(Spec, ", call_from: u64, call_error: u32"),
        ") -> (Phase, ", DataStruct, ", Directive, u1, hls_failure::Code", xls_statem_event_codegen:optional(Spec, ", u8"), xls_statem_reply_codegen:optional(Spec, ", u64, axis::Frame, bool"), ") {\n",
        xls_statem_reply_codegen:optional(Spec, "  if call_error != u32:0 { (phase, data, if call_error == u32:16 { Directive::CONSUME } else { Directive::FAIL }, false, if call_error == u32:16 { hls_failure::NONE } else { hls_failure::INTERNAL }, u8:0, u64:0, zero!<axis::Frame>(), true) } else {\n"),
        "  match frame.header.op as Tag {\n",
        [dispatch_tag_arm(Name, Casts, Spec) || Name <- MessageNames],
        "    _ => (phase, data, Directive::FAIL, u1:0, hls_failure::INVALID_MESSAGE", xls_statem_event_codegen:optional(Spec, ", u8:0"), xls_statem_reply_codegen:optional(Spec, ", u64:0, zero!<axis::Frame>(), true"), "),\n",
        "  }\n",
        xls_statem_reply_codegen:optional(Spec, "  }\n"),
        "}\n\n"
    ].

%% Checks a schema length before invoking its phase-specific callback.
-spec dispatch_tag_arm(atom(), [cast_clause()], spec()) -> iodata().
dispatch_tag_arm(Tag, Casts, Spec) ->
    TagCasts = [Cast || Cast <- Casts, maps:get(tag, Cast) =:= Tag],
    [
        "    Tag::", xls_names:enum_member(Tag), " => {\n",
        xls_statem_reply_codegen:optional(Spec, ["      if frame.header.payload_words != u8:",
            integer_to_list(maps:get(Tag, maps:get(message_words, Spec))),
            " { (phase, data, Directive::FAIL, false, hls_failure::REQUEST_LENGTH, u8:0, u64:0, zero!<axis::Frame>(), true) } else {\n"]),
        "      let message = ", xls_names:record_codec(Tag),
        "_from_bits(frame.payload);\n",
        "      match phase {\n",
        [dispatch_phase_arm(Cast) || Cast <- TagCasts],
        "        _ => (phase, data, Directive::FAIL, u1:0, hls_failure::INVALID_MESSAGE", xls_statem_event_codegen:optional(Spec, ", u8:0"), xls_statem_reply_codegen:optional(Spec, ", u64:0, zero!<axis::Frame>(), true"), "),\n",
        "      }\n",
        xls_statem_reply_codegen:optional(Spec, "      }\n"),
        "    },\n"
    ].

%% Emits the callback branch selected by the actor's current phase.
-spec dispatch_phase_arm(map()) -> iodata().
dispatch_phase_arm(#{
    phase := Phase,
    body := Body,
    result := Result
}) ->
    [
        "        Phase::", xls_names:enum_member(Phase), " => {\n",
        xls_parse_io:indent(Body, 10),
        xls_parse_io:indent(Result, 10),
        "        },\n"
    ].

%% Checks membership in the permitted input schema set.
-spec tag_ok_expression([atom()], spec()) -> iodata().
tag_ok_expression(MessageNames, MessageWords) ->
    join_with(" || ", [
        [
            "(frame.header.op == (Tag::", xls_names:enum_member(Name), " as u8) && ",
            "frame.header.payload_words == u8:",
            integer_to_list(maps:get(Name, MessageWords)), ")"
        ]
        || Name <- MessageNames
    ]).

%% Interleaves a delimiter without adding a leading or trailing separator.
-spec join_with(iodata(), [iodata()]) -> iodata().
join_with(_Separator, []) ->
    [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].

%% Replies use the existing effect sequencer with one reserved frame layout.
-spec reply_layout_count(map()) -> iodata().
reply_layout_count(Spec) -> case xls_statem_reply_codegen:enabled(Spec) of
    false -> [];
    true -> ["    u8:", integer_to_list(xls_statem_reply_codegen:layout(Spec)), " => u8:1,\n"]
end.

%% The reply carries its original transaction ID through ordinary topology routing.
-spec reply_layout_effect(map()) -> iodata().
reply_layout_effect(Spec = #{retained_calls := #{port := Port}}) ->
    ["    u8:", integer_to_list(xls_statem_reply_codegen:layout(Spec)),
     " => Egress { port: OutputPort::", xls_names:enum_member(Port),
     ", frame: axis::frame_from_bits(effects.payloads as bits[128]) },\n"];
reply_layout_effect(_) -> [].

%% Caller-contract faults become actor failures without publishing the invalid reply.
-doc "Checks a pending reply against its declared result schemas.".
-spec reply_failure_binding(map()) -> iodata().
reply_failure_binding(Spec) -> xls_statem_reply_codegen:optional(Spec,
    "    let contract_fault = failure == hls_failure::NONE && reply_book.failure == u32:15;\n"
    "    let failure = hls_failure::first(failure, if reply_book.failure != u32:0 { hls_failure::REPLY_CONTRACT } else { hls_failure::NONE });\n"
    "    let failed = hls_failure::failed(failure);\n").

%% Known calls reserve ownership before length validation, allowing their failure to complete them.
-doc "Renders accepted message selectors, including retained-call reply handling.".
-spec input_tag_ok(map(), [atom()], map()) -> iodata().
input_tag_ok(Spec, Names, Words) -> case xls_statem_reply_codegen:enabled(Spec) of
    false -> tag_ok_expression(Names, Words);
    true -> join_with(" || ", [["frame.header.op == Tag::", xls_names:enum_member(Name), " as u8"] || Name <- Names])
end.
