%%%% xls_statem_codegen
%%%%
%%%% Renders the closed XLS state-machine representation prepared by
%%%% xls_statem_lower. Erlang syntax and parser IR do not cross this boundary.

-module(xls_statem_codegen).
-moduledoc false.

-export([emit/1, shared_machine_width/1]).

-type lowered_clause() :: #{
    body := iodata(),
    result := iodata()
}.
-type entry() :: #{
    phase := atom(),
    data := lowered_clause(),
    effects := [map()]
}.
-type cast_clause() :: #{
    tag := atom(),
    phase := atom(),
    body := iodata(),
    result := iodata()
}.
-type spec() :: #{
    source := file:filename(),
    capacity := 1..255,
    phases := [atom(), ...],
    message_names := [atom(), ...],
    message_words := #{atom() := 1..3},
    output_names := [atom(), ...],
    data_name := atom(),
    data_width := pos_integer(),
    record_declarations := iodata(),
    init := lowered_clause(),
    entries := [entry(), ...],
    casts := [cast_clause()]
}.

-spec emit(spec()) -> iolist().
emit(Spec) ->
    [
        preamble(Spec),
        maps:get(record_declarations, Spec),
        machine_declarations(Spec),
        initial_machine(Spec),
        machine_codec(Spec),
        enter_function(Spec),
        entry_effects_valid_function(),
        dispatch_function(Spec),
        machine_step_function(Spec),
        shared_machine_step_function(Spec),
        service(Spec),
        shared_service(Spec),
        egress_demux(Spec),
        top(Spec)
    ].

%%%
%%% Module declarations
%%%

preamble(#{
    source := Source,
    capacity := Capacity,
    phases := Phases,
    message_names := MessageNames,
    data_name := DataName
}) ->
    [
        "// ", Source, ".x\n",
        "// This file is auto-generated by xls_parse. Manual changes will be\n",
        "// overwritten the next time it is generated.\n\n",
        "import axis;\n",
        "import bram;\n",
        "import mailbox;\n\n",
        "const MAILBOX_CAPACITY = u8:", integer_to_list(Capacity), ";\n",
        "const MAILBOX_DEPTH = u32:", integer_to_list(Capacity), ";\n\n",
        "pub enum Tag : u8 {\n",
        "  NONE = u8:0,\n",
        "  ERROR = u8:1,\n",
        "  ", uppercase(DataName), " = u8:2,\n",
        [
            [
                "  ", uppercase(Name), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Name} <- lists:enumerate(3, MessageNames)
        ],
        "}\n\n",
        phase_declaration(Phases),
        "enum Directive : u2 {\n",
        "  CONSUME = u2:0,\n",
        "  POSTPONE = u2:1,\n",
        "  FAIL = u2:2,\n",
        "}\n\n"
    ].

phase_declaration(Phases) ->
    [
        "enum Phase : u8 {\n",
        [
            [
                "  ", uppercase(Name), " = u8:", integer_to_list(Index),
                ",\n"
            ]
            || {Index, Name} <- lists:enumerate(0, Phases)
        ],
        "}\n\n"
    ].

machine_declarations(#{
    capacity := Capacity,
    output_names := OutputNames,
    max_entry_effects := MaxEntryEffects,
    data_name := DataName,
    data_width := DataWidth
}) ->
    DataStruct = record_struct_name(DataName),
    MachineBits = shared_machine_width(DataWidth),
    EffectCapacity = max(1, MaxEntryEffects),
    [
        "pub enum OutputPort : u8 {\n",
        [
            [
                "  ", uppercase(Port), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Port} <- lists:enumerate(0, OutputNames)
        ],
        "}\n\n",
        "pub struct Egress {\n",
        "  port: OutputPort,\n",
        "  frame: axis::Frame,\n",
        "}\n\n",
        "pub const EGRESS_DEPTH = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub const ENTRY_EFFECT_CAPACITY = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub struct EntryEffects {\n",
        "  count: u8,\n",
        "  valid: bool[", integer_to_list(EffectCapacity), "],\n",
        "  values: Egress[", integer_to_list(EffectCapacity), "],\n",
        "}\n\n",
        "type MailboxSlot = mailbox::Slot;\n\n",
        "struct Machine {\n",
        "  phase: Phase,\n",
        "  entered_from: Phase,\n",
        "  data: ", DataStruct, ",\n",
        "  slots: MailboxSlot[", integer_to_list(Capacity), "],\n",
        "  occupied: u8,\n",
        "  enter_pending: u1,\n",
        "  entry_effect_index: u8,\n",
        "  // Reserves one queue slot for the frame being assembled.\n",
        "  admission_pending: u1,\n",
        "  // A failed service ignores input until reset.\n",
        "  failed: u1,\n",
        "}\n\n",
        "struct SharedMachine {\n",
        "  phase: Phase,\n",
        "  entered_from: Phase,\n",
        "  data: ", DataStruct, ",\n",
        "  enter_pending: u1,\n",
        "  failed: u1,\n",
        "}\n\n",
        "pub type MachineBits = bits[", integer_to_list(MachineBits), "];\n\n",
        "pub type MachineRamReadReq = bram::ReadReq;\n",
        "pub type MachineRamReadResp = bram::ReadResp<u32:",
        integer_to_list(MachineBits), ">;\n",
        "pub type MachineRamWriteReq = bram::WriteReq<u32:",
        integer_to_list(MachineBits), ">;\n",
        "pub type MachineRamWriteResp = bram::WriteResp;\n\n",
        "pub type MailboxRamReadReq = mailbox::RamReadReq;\n",
        "pub type MailboxRamReadResp = mailbox::RamReadResp;\n",
        "pub type MailboxRamWriteReq = mailbox::RamWriteReq;\n",
        "pub type MailboxRamWriteResp = mailbox::RamWriteResp;\n\n",
        "struct MachineStep {\n",
        "  machine: Machine,\n",
        "  egress: Egress,\n",
        "  egress_valid: u1,\n",
        "  admission_valid: u1,\n",
        "}\n\n",
        "pub type ScheduledRequest = mailbox::ScheduledRequest;\n\n",
        "pub struct ScheduledEffects {\n",
        "  slot: u32,\n",
        "  effects: EntryEffects,\n",
        "}\n\n",
        "struct SharedStep {\n",
        "  machine: SharedMachine,\n",
        "  effects: EntryEffects,\n",
        "  effects_valid: u1,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "  egress_blocked: u1,\n",
        "}\n\n",
        "struct SharedDispatch {\n",
        "  machine: SharedMachine,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "}\n\n",
        "type Admission = mailbox::Admission;\n\n",
        "enum SharedPhase : u3 {\n",
        "  BOOT = u3:0,\n",
        "  STARTUP = u3:1,\n",
        "  RUN = u3:2,\n",
        "}\n\n",
        "// XLS channel legalization currently confuses multiple otherwise-\n",
        "// identical SharedService instances connected to different external\n",
        "// RAM ports. INSTANCE_ID distinguishes those specializations; it is\n",
        "// neither actor state nor part of scheduling policy.\n",
        "struct SharedState<ACTOR_COUNT: u32, PRODUCER_COUNT: u32> {\n",
        "  instance_id: u32,\n",
        "  phase: SharedPhase,\n",
        "  next_valid: u1,\n",
        "  next_slot: u32,\n",
        "  older_valid: u1,\n",
        "  older_slot: u32,\n",
        "  older_dispatch: SharedDispatch,\n",
        "  older_received: u1,\n",
        "  older_mailbox_index: u8,\n",
        "  older_order_index: u8,\n",
        "  admission_cursor: u32,\n",
        "  cursor: u32,\n",
        "  startup_seen: u32,\n",
        "  pending: ScheduledRequest[PRODUCER_COUNT],\n",
        "  pending_valid: u1[PRODUCER_COUNT],\n",
        "  occupied: u8[ACTOR_COUNT],\n",
        "  order: u8[", integer_to_list(Capacity), "][ACTOR_COUNT],\n",
        "  postponed: u1[", integer_to_list(Capacity), "][ACTOR_COUNT],\n",
        "  // Mailbox work that has not yet been postponed in this phase.\n",
        "  mail_candidates: u1[ACTOR_COUNT],\n",
        "  // Entry work whose effect batch has not yet been classified.\n",
        "  entry_probes: u1[ACTOR_COUNT],\n",
        "  // Entry work known to need the scheduler's batch sequencer.\n",
        "  egress_waiters: u1[ACTOR_COUNT],\n",
        "  egress_busy: u1,\n",
        "  state_write_pending: u1,\n",
        "  mailbox_write_pending: u1,\n",
        "}\n\n"
    ].

-doc false.
-spec shared_machine_width(non_neg_integer()) -> pos_integer().
shared_machine_width(DataWidth) ->
    18 + DataWidth.

%%%
%%% Lowered callbacks
%%%

initial_machine(#{init := #{body := Body, result := Result}}) ->
    [
        "fn initial_machine() -> Machine {\n",
        Body,
        "  ", Result, "\n",
        "}\n\n",
        "fn shared_machine(machine: Machine) -> SharedMachine {\n",
        "  SharedMachine {\n",
        "    phase: machine.phase,\n",
        "    entered_from: machine.entered_from,\n",
        "    data: machine.data,\n",
        "    enter_pending: machine.enter_pending,\n",
        "    failed: machine.failed,\n",
        "  }\n",
        "}\n\n",
        "fn initial_shared_machine() -> SharedMachine {\n",
        "  shared_machine(initial_machine())\n",
        "}\n\n"
    ].

machine_codec(#{data_name := DataName, data_width := DataWidth}) ->
    DataStart = 16,
    EnterStart = DataStart + DataWidth,
    FailedStart = EnterStart + 1,
    DataFunction = record_function_name(DataName),
    [
        "fn machine_from_bits(raw: MachineBits) -> SharedMachine {\n",
        "  SharedMachine {\n",
        "    phase: raw[0:8] as Phase,\n",
        "    entered_from: raw[8:16] as Phase,\n",
        "    data: ", DataFunction, "_from_bits(raw[",
        integer_to_list(DataStart), ":", integer_to_list(EnterStart), "]),\n",
        "    enter_pending: raw[", integer_to_list(EnterStart), ":",
        integer_to_list(FailedStart), "],\n",
        "    failed: raw[", integer_to_list(FailedStart), ":",
        integer_to_list(FailedStart + 1), "],\n",
        "  }\n",
        "}\n\n",
        "fn bits_from_machine(machine: SharedMachine) -> MachineBits {\n",
        "  machine.failed ++\n",
        "    machine.enter_pending ++\n",
        "    bits_from_", DataFunction, "(machine.data) ++\n",
        "    (machine.entered_from as bits[8]) ++\n",
        "    (machine.phase as bits[8])\n",
        "}\n\n",
        "fn machine_read(slot: u32) -> MachineRamReadReq {\n",
        "  bram::read(slot)\n",
        "}\n\n",
        "fn machine_write(\n",
        "    slot: u32, machine: SharedMachine) -> MachineRamWriteReq {\n",
        "  bram::write(slot, bits_from_machine(machine))\n",
        "}\n\n"
    ].

enter_function(#{
    data_name := DataName,
    max_entry_effects := MaxEntryEffects,
    entries := Entries
}) ->
    DataStruct = record_struct_name(DataName),
    EffectCapacity = max(1, MaxEntryEffects),
    [
        "fn enter(old_phase: Phase, phase: Phase, data: ", DataStruct,
        ") -> (", DataStruct, ", EntryEffects) {\n",
        "  match phase {\n",
        [entry_arm(Entry, EffectCapacity) || Entry <- Entries],
        "  }\n",
        "}\n\n"
    ].

entry_arm(#{
    phase := Phase,
    data := #{body := DataBody, result := DataResult},
    effects := Effects
}, EffectCapacity) ->
    Padding = EffectCapacity - length(Effects),
    [
        "    Phase::", uppercase(Phase), " => {\n",
        "      let entered_data = {\n",
        xls_parse_io:indent(DataBody, 8),
        "        ", DataResult, "\n",
        "      };\n",
        [entry_effect_binding(Index, Effect)
            || {Index, Effect} <- lists:enumerate(0, Effects)],
        "      (entered_data, EntryEffects {\n",
        "        count: u8:", integer_to_list(length(Effects)), ",\n",
        "        valid: [\n",
        [
            ["          effect_", integer_to_list(Index), "_valid,\n"]
            || {Index, _Effect} <- lists:enumerate(0, Effects)
        ],
        lists:duplicate(Padding, "          bool:false,\n"),
        "        ],\n",
        "        values: [\n",
        [
            [
                "          Egress { port: OutputPort::",
                uppercase(maps:get(port, Effect)),
                ", frame: effect_", integer_to_list(Index), " },\n"
            ]
            || {Index, Effect} <- lists:enumerate(0, Effects)
        ],
        lists:duplicate(Padding, "          zero!<Egress>(),\n"),
        "        ],\n",
        "      })\n",
        "    },\n"
    ].

entry_effects_valid_function() ->
    [
        """
        fn entry_effects_valid(effects: EntryEffects) -> u1 {
          unroll_for! (index, found):
              (u32, u1) in u32:0..ENTRY_EFFECT_CAPACITY {
            found || (index < effects.count as u32 && effects.valid[index])
          }(u1:0)
        }

        """,
        "\n"
    ].

entry_effect_binding(Index, #{
    body := Body,
    result := Result,
    valid := #{body := ValidBody, result := ValidResult}
}) ->
    [
        "      let effect_", integer_to_list(Index), "_valid = {\n",
        xls_parse_io:indent(ValidBody, 8),
        "        ", ValidResult, "\n",
        "      };\n",
        "      let effect_", integer_to_list(Index), " = {\n",
        xls_parse_io:indent(Body, 8),
        "        ", Result, "\n",
        "      };\n"
    ].

dispatch_function(#{
    message_names := MessageNames,
    data_name := DataName,
    casts := Casts
}) ->
    DataStruct = record_struct_name(DataName),
    [
        "fn dispatch(frame: axis::Frame, phase: Phase, data: ", DataStruct,
        ") -> (Phase, ", DataStruct, ", Directive, u1) {\n",
        "  match frame.header.op as Tag {\n",
        [dispatch_tag_arm(Name, Casts) || Name <- MessageNames],
        "    _ => (phase, data, Directive::FAIL, u1:0),\n",
        "  }\n",
        "}\n\n"
    ].

dispatch_tag_arm(Tag, Casts) ->
    TagCasts = [Cast || Cast <- Casts, maps:get(tag, Cast) =:= Tag],
    [
        "    Tag::", uppercase(Tag), " => {\n",
        "      let message = ", record_function_name(Tag),
        "_from_bits(frame.payload);\n",
        "      match phase {\n",
        [dispatch_phase_arm(Cast) || Cast <- TagCasts],
        "        _ => (phase, data, Directive::FAIL, u1:0),\n",
        "      }\n",
        "    },\n"
    ].

dispatch_phase_arm(#{
    phase := Phase,
    body := Body,
    result := Result
}) ->
    [
        "        Phase::", uppercase(Phase), " => {\n",
        xls_parse_io:indent(Body, 10),
        xls_parse_io:indent(Result, 10),
        "        },\n"
    ].

%%%
%%% Bounded scheduler
%%%

machine_step_function(#{
    capacity := Capacity,
    message_names := MessageNames,
    message_words := MessageWords
}) ->
    #{
        eligible_bindings := EligibleBindings,
        found_expression := FoundExpression,
        selected_expression := SelectedExpression,
        compaction_bindings := CompactionBindings,
        compacted_array := CompactedArray,
        unblocked_array := UnblockedArray
    } = queue_expansion(Capacity),
    [
        "fn machine_step(\n",
        "    machine: Machine, frame: axis::Frame, received: u1,\n",
        "    egress_ready: u1) -> MachineStep {\n",
        "  if machine.failed {\n",
        "    MachineStep { machine, ..zero!<MachineStep>() }\n",
        "  } else if machine.enter_pending {\n",
        machine_entry_step(),
        "  } else {\n",
        "      let tag_ok = ",
        tag_ok_expression(MessageNames, MessageWords), ";\n",
        "      let accepted = received && tag_ok;\n",
        "      let invalid_input = received && !tag_ok;\n",
        "      let incoming_slot = MailboxSlot {\n",
        "        frame,\n",
        "        ..zero!<MailboxSlot>()\n",
        "      };\n",
        "      let admitted_slots = if accepted {\n",
        "        update(machine.slots, machine.occupied as u32, incoming_slot)\n",
        "      } else { machine.slots };\n",
        "      let admitted_occupied = machine.occupied + (accepted as u8);\n",
        EligibleBindings,
        "      let found = ", FoundExpression, ";\n",
        "      let selected = ", SelectedExpression, ";\n",
        "      let selected_frame = admitted_slots[selected as u32].frame;\n",
        "      let dispatchable = found && !invalid_input;\n",
        "      let (next_phase, next_data, directive, repeat_phase) =\n",
        "        if dispatchable {\n",
        "          dispatch(selected_frame, machine.phase, machine.data)\n",
        "        } else {\n",
        "          (machine.phase, machine.data, Directive::CONSUME, u1:0)\n",
        "        };\n",
        "      let invalid_repeat = dispatchable && repeat_phase &&\n",
        "        (directive != Directive::CONSUME ||\n",
        "         next_phase != machine.phase);\n",
        "      let effective = dispatchable && !invalid_repeat;\n",
        "      let selected_slot = admitted_slots[selected as u32];\n",
        "      let postponed_slot = MailboxSlot {\n",
        "        postponed: u1:1,\n",
        "        ..selected_slot\n",
        "      };\n",
        "      let postponed_slots = update(\n",
        "        admitted_slots, selected as u32, postponed_slot);\n",
        CompactionBindings,
        "      let compacted_slots = ", CompactedArray, ";\n",
        "      let transition_slots = match directive {\n",
        "        Directive::CONSUME => compacted_slots,\n",
        "        Directive::POSTPONE => postponed_slots,\n",
        "        Directive::FAIL => admitted_slots,\n",
        "      };\n",
        "      let candidate_slots = if effective {\n",
        "        transition_slots\n",
        "      } else { admitted_slots };\n",
        "      let candidate_occupied = if effective &&\n",
        "          directive == Directive::CONSUME {\n",
        "        admitted_occupied - u8:1\n",
        "      } else { admitted_occupied };\n",
        "      let candidate_phase = if effective {\n",
        "        next_phase\n",
        "      } else { machine.phase };\n",
        "      let candidate_data = if effective {\n",
        "        next_data\n",
        "      } else { machine.data };\n",
        "      let phase_changed = candidate_phase != machine.phase;\n",
        "      let phase_boundary = phase_changed ||\n",
        "        (effective && repeat_phase);\n",
        "      let unblocked_slots = ", UnblockedArray, ";\n",
        "      let final_slots = if phase_boundary {\n",
        "        unblocked_slots\n",
        "      } else { candidate_slots };\n",
        "      let failed = invalid_input || invalid_repeat ||\n",
        "        (effective && directive == Directive::FAIL);\n",
        "      let admission_pending =\n",
        "        machine.admission_pending && !received;\n",
        "      // Preserve occupied + admission_pending <= capacity.\n",
        "      let reserve = !failed && !received && !admission_pending &&\n",
        "        candidate_occupied < MAILBOX_CAPACITY;\n",
        "      let next_machine = Machine {\n",
        "        phase: candidate_phase,\n",
        "        entered_from: if phase_boundary {\n",
        "          machine.phase\n",
        "        } else { machine.entered_from },\n",
        "        data: candidate_data,\n",
        "        slots: final_slots,\n",
        "        occupied: candidate_occupied,\n",
        "        enter_pending: effective && phase_boundary && !failed,\n",
        "        admission_pending: admission_pending || reserve,\n",
        "        failed,\n",
        "        ..machine\n",
        "      };\n",
        "      MachineStep {\n",
        "        machine: next_machine,\n",
        "        admission_valid: reserve,\n",
        "        ..zero!<MachineStep>()\n",
        "      }\n",
        "  }\n",
        "}\n\n"
    ].

machine_entry_step() ->
    [
        "    let (entered_data, effects) = enter(\n",
        "      machine.entered_from, machine.phase, machine.data);\n",
        "    let has_effect = machine.entry_effect_index < effects.count;\n",
        "    let effect = effects.values[\n",
        "      machine.entry_effect_index as u32];\n",
        "    let emit_effect = has_effect && effects.valid[\n",
        "      machine.entry_effect_index as u32];\n",
        "    let can_advance = !emit_effect || egress_ready;\n",
        "    let next_effect_index = machine.entry_effect_index +\n",
        "      ((has_effect && can_advance) as u8);\n",
        "    let entry_complete = can_advance &&\n",
        "      next_effect_index >= effects.count;\n",
        "    let reserve = entry_complete &&\n",
        "      !machine.admission_pending &&\n",
        "      machine.occupied < MAILBOX_CAPACITY;\n",
        "    let advanced_machine = Machine {\n",
        "      data: if entry_complete { entered_data } else { machine.data },\n",
        "      enter_pending: !entry_complete,\n",
        "      entry_effect_index: if entry_complete {\n",
        "        u8:0\n",
        "      } else { next_effect_index },\n",
        "      admission_pending: machine.admission_pending || reserve,\n",
        "      ..machine\n",
        "    };\n",
        "    MachineStep {\n",
        "      machine: if can_advance { advanced_machine } else { machine },\n",
        "      egress: effect,\n",
        "      egress_valid: emit_effect && can_advance,\n",
        "      admission_valid: reserve,\n",
        "    }\n"
    ].

shared_machine_step_function(#{
    message_names := MessageNames,
    message_words := MessageWords
}) ->
    [
        "fn shared_machine_dispatch(\n",
        "    machine: SharedMachine, frame: axis::Frame, received: u1)\n",
        "    -> SharedDispatch {\n",
        "  if machine.failed {\n",
        "    SharedDispatch { machine, ..zero!<SharedDispatch>() }\n",
        "  } else if machine.enter_pending || !received {\n",
        "    SharedDispatch { machine, ..zero!<SharedDispatch>() }\n",
        "  } else {\n",
        "    let tag_ok = ",
        tag_ok_expression(MessageNames, MessageWords), ";\n",
        "    let (next_phase, next_data, directive, repeat_phase) =\n",
        "      if tag_ok {\n",
        "        dispatch(frame, machine.phase, machine.data)\n",
        "      } else {\n",
        "        (machine.phase, machine.data, Directive::FAIL, u1:0)\n",
        "      };\n",
        "    let invalid_repeat = tag_ok && repeat_phase &&\n",
        "      (directive != Directive::CONSUME ||\n",
        "       next_phase != machine.phase);\n",
        "    let effective = tag_ok && !invalid_repeat;\n",
        "    let phase_changed = effective && next_phase != machine.phase;\n",
        "    let phase_boundary = phase_changed ||\n",
        "      (effective && repeat_phase);\n",
        "    let failed = !tag_ok || invalid_repeat ||\n",
        "      (effective && directive == Directive::FAIL);\n",
        "    let next_machine = SharedMachine {\n",
        "      phase: if effective { next_phase } else { machine.phase },\n",
        "      entered_from: if phase_boundary {\n",
        "        machine.phase\n",
        "      } else { machine.entered_from },\n",
        "      data: if effective { next_data } else { machine.data },\n",
        "      enter_pending: effective && phase_boundary && !failed,\n",
        "      failed,\n",
        "      ..machine\n",
        "    };\n",
        "    SharedDispatch {\n",
        "      machine: next_machine,\n",
        "      dispatched: tag_ok && !invalid_repeat,\n",
        "      directive,\n",
        "      phase_boundary,\n",
        "      ..zero!<SharedDispatch>()\n",
        "    }\n",
        "  }\n",
        "}\n\n",
        "fn shared_machine_enter(machine: SharedMachine, egress_ready: u1)\n",
        "    -> SharedStep {\n",
        "  if machine.failed || !machine.enter_pending {\n",
        "    SharedStep { machine, ..zero!<SharedStep>() }\n",
        "  } else {\n",
        shared_machine_entry_step(),
        "  }\n",
        "}\n\n"
    ].

shared_machine_entry_step() ->
    [
        "    let (entered_data, effects) = enter(\n",
        "      machine.entered_from, machine.phase, machine.data);\n",
        "    let effects_valid = entry_effects_valid(effects);\n",
        "    let can_advance = !effects_valid || egress_ready;\n",
        "    let advanced_machine = SharedMachine {\n",
        "      data: entered_data,\n",
        "      enter_pending: u1:0,\n",
        "      ..machine\n",
        "    };\n",
        "    SharedStep {\n",
        "      machine: if can_advance { advanced_machine } else { machine },\n",
        "      effects,\n",
        "      effects_valid: effects_valid && can_advance,\n",
        "      egress_blocked: effects_valid && !egress_ready,\n",
        "      ..zero!<SharedStep>()\n",
        "    }\n"
    ].

service(_Spec) ->
    [
        "pub proc Service {\n",
        "  req_in: chan<axis::Frame> in;\n",
        "  egress_out: chan<Egress> out;\n",
        "  admission_out: chan<u1> out;\n\n",
        "  config(req_in: chan<axis::Frame> in,\n",
        "         egress_out: chan<Egress> out,\n",
        "         admission_out: chan<u1> out) {\n",
        "    (req_in, egress_out, admission_out)\n",
        "  }\n\n",
        "  init { initial_machine() }\n\n",
        "  next(machine: Machine) {\n",
        "    let receive_enabled = !machine.failed &&\n",
        "      !machine.enter_pending && machine.admission_pending;\n",
        "    let (tok, frame, received) = recv_if_non_blocking(\n",
        "      join(), req_in, receive_enabled, zero!<axis::Frame>());\n",
        "    let stepped = machine_step(machine, frame, received, u1:1);\n",
        "    let egress_tok = send_if(\n",
        "      tok, egress_out, stepped.egress_valid, stepped.egress);\n",
        "    let _admission_tok = send_if(\n",
        "      egress_tok, admission_out, stepped.admission_valid, u1:1);\n",
        "    stepped.machine\n",
        "  }\n",
        "}\n\n"
    ].

shared_service(_Spec) ->
    """
    fn free_mailbox_index<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        slot: u32) -> u8 {
      let (_found, selected) = unroll_for! (candidate, acc):
          (u32, (u1, u8)) in
          u32:0..MAILBOX_DEPTH {
        let used = unroll_for! (position, found):
            (u32, u1) in u32:0..MAILBOX_DEPTH {
          found || (
            position < state.occupied[slot] as u32 &&
            state.order[slot][position] == candidate as u8)
        }(u1:0);
        let take = !acc.0 && !used;
        (
          acc.0 || take,
          if take { candidate as u8 } else { acc.1 }
        )
      }((u1:0, u8:0));
      selected
    }

    fn mailbox_selection<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        slot: u32) -> (u1, u8, u8) {
      unroll_for! (position, acc):
          (u32, (u1, u8, u8)) in
          u32:0..MAILBOX_DEPTH {
        let physical = state.order[slot][position];
        let take = !acc.0 &&
          position < state.occupied[slot] as u32 &&
          !state.postponed[slot][physical as u32];
        (
          acc.0 || take,
          if take { position as u8 } else { acc.1 },
          if take { physical } else { acc.2 }
        )
      }((u1:0, u8:0, u8:0))
    }

    fn compact_order(
        row: u8[MAILBOX_DEPTH],
        selected: u8,
        occupied: u8) -> u8[MAILBOX_DEPTH] {
      unroll_for! (position, result):
          (u32, u8[MAILBOX_DEPTH]) in
          u32:0..MAILBOX_DEPTH {
        let value = if position < selected as u32 {
          row[position]
        } else if position + u32:1 < occupied as u32 {
          row[position + u32:1]
        } else {
          u8:0
        };
        update(result, position, value)
      }(zero!<u8[MAILBOX_DEPTH]>())
    }

    // Finds the first selectable actor at or after the round-robin cursor.
    // The excluded slot has been read but not dispatched, so its next state
    // is not yet visible to another activation.
    fn ready_selection<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        cursor: u32,
        excluded_valid: u1,
        excluded_slot: u32) -> (u1, u32) {
      let (after_found, after_slot, before_found, before_slot) =
          unroll_for! (slot, acc):
              (u32, (u1, u32, u1, u32)) in u32:0..ACTOR_COUNT {
        let entry_active =
          state.entry_probes[slot] || state.egress_waiters[slot];
        let ready =
          state.entry_probes[slot] ||
          (state.mail_candidates[slot] && !entry_active) ||
          (state.egress_waiters[slot] && !state.egress_busy);
        let selectable = ready &&
          (!excluded_valid || slot != excluded_slot);
        let take_after = !acc.0 && slot >= cursor && selectable;
        let take_before = !acc.2 && slot < cursor && selectable;
        (
          acc.0 || take_after,
          if take_after { slot } else { acc.1 },
          acc.2 || take_before,
          if take_before { slot } else { acc.3 }
        )
      }((u1:0, u32:0, u1:0, u32:0));
      (
        after_found || before_found,
        if after_found { after_slot } else { before_slot }
      )
    }

    // Dispatch publishes the actor address and its mailbox action. Entry runs
    // one pipeline interval later and seals the state/effect values for
    // in-order commit.
    fn resolve_entry(step: SharedDispatch, valid: u1, egress_ready: u1) ->
        SharedStep {
      let entered = shared_machine_enter(step.machine, egress_ready);
      if valid {
        SharedStep {
          machine: entered.machine,
          effects: entered.effects,
          effects_valid: entered.effects_valid,
          egress_blocked: entered.egress_blocked,
          dispatched: step.dispatched,
          directive: step.directive,
          phase_boundary: step.phase_boundary,
        }
      } else {
        zero!<SharedStep>()
      }
    }

    // Projects the sealed older activation into scheduler metadata. Its RAM
    // write shares the RUN activation with a distinct younger actor's read.
    fn retire_actor<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        valid: u1,
        slot: u32,
        stepped: SharedStep,
        received: u1,
        mailbox_index: u8,
        order_index: u8) -> SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
      let consumed = valid && received && stepped.dispatched &&
        stepped.directive == Directive::CONSUME;
      let should_postpone = valid && received && stepped.dispatched &&
        stepped.directive == Directive::POSTPONE;
      let old_count = state.occupied[slot];
      let occupied = if valid {
        update(
          state.occupied,
          slot,
          if consumed { old_count - u8:1 } else { old_count })
      } else {
        state.occupied
      };
      let compacted = compact_order(
        state.order[slot], order_index, old_count);
      let order = if consumed {
        update(state.order, slot, compacted)
      } else {
        state.order
      };
      let marked = update(
        state.postponed[slot], mailbox_index as u32, u1:1);
      let postponed_row = if stepped.phase_boundary {
        zero!<u1[MAILBOX_DEPTH]>()
      } else if should_postpone {
        marked
      } else {
        state.postponed[slot]
      };
      let postponed = if valid {
        update(state.postponed, slot, postponed_row)
      } else {
        state.postponed
      };
      let metadata_state = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
        occupied,
        order,
        postponed,
        ..state
      };
      let (mail_remaining, _, _) =
        mailbox_selection(metadata_state, slot);
      let mail_candidates = if valid {
        update(
          state.mail_candidates,
          slot,
          mail_remaining && !stepped.machine.failed)
      } else {
        state.mail_candidates
      };
      let entry_probes = if valid {
        update(
          state.entry_probes,
          slot,
          stepped.machine.enter_pending &&
            !stepped.egress_blocked && !stepped.machine.failed)
      } else {
        state.entry_probes
      };
      let egress_waiters = if valid {
        update(
          state.egress_waiters,
          slot,
          stepped.machine.enter_pending &&
            stepped.egress_blocked && !stepped.machine.failed)
      } else {
        state.egress_waiters
      };
      SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
        occupied,
        order,
        postponed,
        mail_candidates,
        entry_probes,
        egress_waiters,
        ..state
      }
    }

    // Returned batch credits represent completed effect batches, so they
    // update scheduler metadata without carrying another actor context.
    fn collect_credit<PRODUCER_COUNT: u32>(
        pending: ScheduledRequest[PRODUCER_COUNT],
        pending_valid: u1[PRODUCER_COUNT],
        egress_busy: u1) -> (u1[PRODUCER_COUNT], u1) {
      let (credit_found, credit_producer) =
        unroll_for! (candidate, acc):
            (u32, (u1, u32)) in u32:0..PRODUCER_COUNT {
          let take = !acc.0 && pending_valid[candidate] &&
            pending[candidate].credit;
          (acc.0 || take, if take { candidate } else { acc.1 })
        }((u1:0, u32:0));
      let remaining = if credit_found {
        update(pending_valid, credit_producer, u1:0)
      } else {
        pending_valid
      };
      (remaining, egress_busy && !credit_found)
    }

    struct AdmissionResult<ACTOR_COUNT: u32, PRODUCER_COUNT: u32> {
      pending_valid: u1[PRODUCER_COUNT],
      occupied: u8[ACTOR_COUNT],
      order: u8[MAILBOX_DEPTH][ACTOR_COUNT],
      mail_candidates: u1[ACTOR_COUNT],
      admission: Admission,
      cursor: u32,
    }

    // Reserves one producer frame against metadata that already includes the
    // older sealed activation. The younger address is unresolved and stalls
    // only same-address admission for this interval.
    fn reserve_admission<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        pending: ScheduledRequest[PRODUCER_COUNT],
        pending_valid: u1[PRODUCER_COUNT],
        excluded_valid: u1,
        excluded_slot: u32,
        failed_valid: u1,
        failed_slot: u32) ->
        AdmissionResult<ACTOR_COUNT, PRODUCER_COUNT> {
      let (after_found, after_producer, before_found, before_producer) =
          unroll_for! (candidate, acc):
              (u32, (u1, u32, u1, u32)) in u32:0..PRODUCER_COUNT {
        let request = pending[candidate];
        let slot = request.slot;
        let eligible = pending_valid[candidate] && !request.credit &&
          slot < ACTOR_COUNT &&
          state.occupied[slot] < MAILBOX_CAPACITY &&
          (!excluded_valid || slot != excluded_slot) &&
          (!failed_valid || slot != failed_slot);
        let take_after = !acc.0 &&
          candidate >= state.admission_cursor && eligible;
        let take_before = !acc.2 &&
          candidate < state.admission_cursor && eligible;
        (
          acc.0 || take_after,
          if take_after { candidate } else { acc.1 },
          acc.2 || take_before,
          if take_before { candidate } else { acc.3 }
        )
      }((u1:0, u32:0, u1:0, u32:0));
      let found = after_found || before_found;
      let producer = if after_found {
        after_producer
      } else {
        before_producer
      };
      let request = pending[producer];
      let slot = if request.slot < ACTOR_COUNT {
        request.slot
      } else {
        u32:0
      };
      let physical = free_mailbox_index(state, slot);
      let old_count = state.occupied[slot];
      let occupied = if found {
        update(state.occupied, slot, old_count + u8:1)
      } else {
        state.occupied
      };
      let row = update(
        state.order[slot], old_count as u32, physical);
      let order = if found {
        update(state.order, slot, row)
      } else {
        state.order
      };
      let mail_candidates = if found {
        update(state.mail_candidates, slot, u1:1)
      } else {
        state.mail_candidates
      };
      let remaining = if found {
        update(pending_valid, producer, u1:0)
      } else {
        pending_valid
      };
      let cursor = if found {
        if producer + u32:1 == PRODUCER_COUNT {
          u32:0
        } else {
          producer + u32:1
        }
      } else {
        state.admission_cursor
      };
      AdmissionResult<ACTOR_COUNT, PRODUCER_COUNT> {
        pending_valid: remaining,
        occupied,
        order,
        mail_candidates,
        admission: Admission {
          valid: found,
          producer,
          slot,
          physical,
        },
        cursor,
      }
    }

    // One mailbox owner advances a fixed in-order two-stage activation. The
    // older actor enters and commits while a distinct younger actor is read
    // and dispatched. Independent read and write ports sustain one actor
    // initiation per XLS two-clock pipeline interval; slot exclusion prevents
    // a read/write collision without speculative same-slot access.
    pub proc SharedService<
        ACTOR_COUNT: u32,
        PRODUCER_COUNT: u32,
        STARTUP_COUNT: u32,
        INSTANCE_ID: u32
    > {
      request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in;
      startup_in: chan<ScheduledRequest> in;
      egress_out: chan<ScheduledEffects> out;
      ram_read_req_out: chan<MachineRamReadReq> out;
      ram_read_resp_in: chan<MachineRamReadResp> in;
      ram_write_req_out: chan<MachineRamWriteReq> out;
      ram_write_resp_in: chan<MachineRamWriteResp> in;
      mailbox_read_req_out: chan<MailboxRamReadReq> out;
      mailbox_read_resp_in: chan<MailboxRamReadResp> in;
      mailbox_write_req_out: chan<MailboxRamWriteReq> out;
      mailbox_write_resp_in: chan<MailboxRamWriteResp> in;

      config(
          request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in,
          startup_in: chan<ScheduledRequest> in,
          egress_out: chan<ScheduledEffects> out,
          ram_read_req_out: chan<MachineRamReadReq> out,
          ram_read_resp_in: chan<MachineRamReadResp> in,
          ram_write_req_out: chan<MachineRamWriteReq> out,
          ram_write_resp_in: chan<MachineRamWriteResp> in,
          mailbox_read_req_out: chan<MailboxRamReadReq> out,
          mailbox_read_resp_in: chan<MailboxRamReadResp> in,
          mailbox_write_req_out: chan<MailboxRamWriteReq> out,
          mailbox_write_resp_in: chan<MailboxRamWriteResp> in
      ) {
        (
          request_in,
          startup_in,
          egress_out,
          ram_read_req_out,
          ram_read_resp_in,
          ram_write_req_out,
          ram_write_resp_in,
          mailbox_read_req_out,
          mailbox_read_resp_in,
          mailbox_write_req_out,
          mailbox_write_resp_in,
        )
      }

      init {
        SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          instance_id: INSTANCE_ID,
          phase: SharedPhase::BOOT,
          ..zero!<SharedState<ACTOR_COUNT, PRODUCER_COUNT>>()
        }
      }

      next(state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>) {
        let capture_enabled = state.phase == SharedPhase::RUN;
        let (capture_tok, captured_pending, captured_pending_valid) =
          unroll_for! (producer, acc):
              (u32, (
                token,
                ScheduledRequest[PRODUCER_COUNT],
                u1[PRODUCER_COUNT]
              )) in u32:0..PRODUCER_COUNT {
            let (next_tok, request, captured) =
              recv_if_non_blocking(
                acc.0,
                request_in[producer],
                capture_enabled && !acc.2[producer],
                zero!<ScheduledRequest>());
            (
              next_tok,
              if captured {
                update(acc.1, producer, request)
              } else {
                acc.1
              },
              if captured {
                update(acc.2, producer, u1:1)
              } else {
                acc.2
              }
            )
          }((join(), state.pending, state.pending_valid));
        match state.phase {
          SharedPhase::BOOT => {
            let write_tok = send(
              capture_tok,
              ram_write_req_out,
              machine_write(state.cursor, initial_shared_machine()));
            let (_done, _) = recv(write_tok, ram_write_resp_in);
            let entry_probes = update(
              state.entry_probes, state.cursor, u1:1);
            if state.cursor + u32:1 == ACTOR_COUNT {
              SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
                phase: if STARTUP_COUNT == u32:0 {
                  SharedPhase::RUN
                } else {
                  SharedPhase::STARTUP
                },
                next_valid: STARTUP_COUNT == u32:0,
                next_slot: u32:0,
                cursor: u32:0,
                entry_probes,
                ..state
              }
            } else {
              SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
                cursor: state.cursor + u32:1,
                entry_probes,
                ..state
              }
            }
          },
          SharedPhase::STARTUP => {
            let (tok, request) = recv(capture_tok, startup_in);
            let physical = state.occupied[request.slot];
            let write_tok = send(
              tok,
              mailbox_write_req_out,
              mailbox::write(
                request.slot, physical, MAILBOX_DEPTH, request.frame));
            let (_done, _) = recv(write_tok, mailbox_write_resp_in);
            let occupied = update(
              state.occupied, request.slot, physical + u8:1);
            let row = update(
              state.order[request.slot], physical as u32, physical);
            let order = update(state.order, request.slot, row);
            let mail_candidates = update(
              state.mail_candidates, request.slot, u1:1);
            let startup_seen = state.startup_seen + u32:1;
            SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              phase: if startup_seen == STARTUP_COUNT {
                SharedPhase::RUN
              } else {
                SharedPhase::STARTUP
              },
              next_valid: startup_seen == STARTUP_COUNT,
              next_slot: u32:0,
              startup_seen,
              occupied,
              order,
              mail_candidates,
              ..state
            }
          },
          SharedPhase::RUN => {
            let read_slot = if state.next_valid {
              state.next_slot
            } else {
              u32:0
            };
            let entry_active = state.entry_probes[read_slot] ||
              state.egress_waiters[read_slot];
            let read_mailbox =
              state.next_valid &&
              state.mail_candidates[read_slot] && !entry_active;
            let (received, order_index, mailbox_index) =
              mailbox_selection(state, read_slot);
            let (state_completion_tok, _) = recv_if(
              join(), ram_write_resp_in, state.state_write_pending,
              zero!<MachineRamWriteResp>());
            let (mailbox_completion_tok, _) = recv_if(
              join(), mailbox_write_resp_in,
              state.mailbox_write_pending,
              zero!<MailboxRamWriteResp>());
            let state_read_tok = send_if(
              join(),
              ram_read_req_out,
              state.next_valid,
              machine_read(read_slot));
            let mailbox_read_tok = send_if(
              join(),
              mailbox_read_req_out,
              read_mailbox && received,
              mailbox::read(read_slot, mailbox_index, MAILBOX_DEPTH));
            let (state_done, response) = recv_if(
              state_read_tok,
              ram_read_resp_in,
              state.next_valid,
              zero!<MachineRamReadResp>());
            let (mailbox_done, mailbox_response) = recv_if(
              mailbox_read_tok,
              mailbox_read_resp_in,
              read_mailbox && received,
              zero!<MailboxRamReadResp>());
            let (credit_pending_valid, credit_busy) = collect_credit(
              captured_pending,
              captured_pending_valid,
              state.egress_busy);
            let resolved = resolve_entry(
              state.older_dispatch, state.older_valid, !credit_busy);
            let credited = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              pending: captured_pending,
              pending_valid: credit_pending_valid,
              egress_busy: credit_busy ||
                (state.older_valid && resolved.effects_valid),
              ..state
            };
            let retired = retire_actor(
              credited,
              state.older_valid,
              state.older_slot,
              resolved,
              state.older_received,
              state.older_mailbox_index,
              state.older_order_index);
            let reservation = reserve_admission(
              retired,
              captured_pending,
              credit_pending_valid,
              state.next_valid,
              read_slot,
              state.older_valid && resolved.machine.failed,
              state.older_slot);
            let admitted = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              pending: captured_pending,
              pending_valid: reservation.pending_valid,
              occupied: reservation.occupied,
              order: reservation.order,
              mail_candidates: reservation.mail_candidates,
              admission_cursor: reservation.cursor,
              ..retired
            };
            let cursor = if state.next_valid {
              if read_slot + u32:1 == ACTOR_COUNT {
                u32:0
              } else {
                read_slot + u32:1
              }
            } else {
              state.cursor
            };
            let (ready, next_slot) = ready_selection(
              admitted,
              cursor,
              state.next_valid,
              read_slot);
            let machine = machine_from_bits(response.data);
            let frame = axis::frame_from_bits(mailbox_response.data);
            let dispatched = shared_machine_dispatch(
              machine, frame, read_mailbox && received);
            let scheduled = ScheduledEffects {
              slot: state.older_slot,
              effects: resolved.effects,
            };
            let egress_tok = send_if(
              capture_tok,
              egress_out,
              state.older_valid && resolved.effects_valid,
              scheduled);
            let state_write_tok = send_if(
              join(state_read_tok, egress_tok),
              ram_write_req_out,
              state.older_valid,
              machine_write(state.older_slot, resolved.machine));
            let admission_frame =
              captured_pending[reservation.admission.producer].frame;
            let mailbox_write_tok = send_if(
              join(mailbox_read_tok, egress_tok),
              mailbox_write_req_out,
              reservation.admission.valid,
              mailbox::write(
                reservation.admission.slot,
                reservation.admission.physical,
                MAILBOX_DEPTH,
                admission_frame));
            let _done = join(
              state_done,
              mailbox_done,
              state_write_tok,
              mailbox_write_tok,
              state_completion_tok,
              mailbox_completion_tok);
            SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              next_valid: ready,
              next_slot,
              older_valid: state.next_valid,
              older_slot: read_slot,
              older_dispatch: if state.next_valid {
                dispatched
              } else {
                zero!<SharedDispatch>()
              },
              older_received: read_mailbox && received,
              older_mailbox_index: mailbox_index,
              older_order_index: order_index,
              cursor,
              state_write_pending: state.older_valid,
              mailbox_write_pending: reservation.admission.valid,
              ..admitted
            }
          },
        }
      }
    }

    """.

tag_ok_expression(MessageNames, MessageWords) ->
    join_with(" || ", [
        [
            "(frame.header.op == (Tag::", uppercase(Name), " as u8) && ",
            "frame.header.payload_words == u8:",
            integer_to_list(maps:get(Name, MessageWords)), ")"
        ]
        || Name <- MessageNames
    ]).

queue_expansion(Capacity) ->
    Indexes = lists:seq(0, Capacity - 1),
    EligibleBindings = [eligible_binding(Index) || Index <- Indexes],
    FoundExpression = join_with(" || ", [
        ["eligible_", integer_to_list(Index)] || Index <- Indexes
    ]),
    SelectedExpression = lists:foldr(
        fun(Index, Else) ->
            [
                "if eligible_", integer_to_list(Index), " { u8:",
                integer_to_list(Index), " } else { ", Else, " }"
            ]
        end,
        "u8:0",
        Indexes
    ),
    CompactionBindings = [
        compaction_binding(Index, Capacity) || Index <- Indexes
    ],
    CompactedArray = [
        "[",
        join_with(", ", [
            ["compacted_", integer_to_list(Index)] || Index <- Indexes
        ]),
        "]"
    ],
    UnblockedArray = [
        "[",
        join_with(",\n        ", [
            [
                "MailboxSlot { postponed: u1:0, ..candidate_slots[",
                integer_to_list(Index), "] }"
            ]
            || Index <- Indexes
        ]),
        "]"
    ],
    #{
        eligible_bindings => EligibleBindings,
        found_expression => FoundExpression,
        selected_expression => SelectedExpression,
        compaction_bindings => CompactionBindings,
        compacted_array => CompactedArray,
        unblocked_array => UnblockedArray
    }.

eligible_binding(Index) ->
    [
        "      let eligible_", integer_to_list(Index), " = u8:",
        integer_to_list(Index), " < admitted_occupied &&\n",
        "        !admitted_slots[", integer_to_list(Index),
        "].postponed;\n"
    ].

compaction_binding(Index, Capacity) when Index + 1 < Capacity ->
    [
        "      let compacted_", integer_to_list(Index), " = if u8:",
        integer_to_list(Index), " < selected {\n",
        "        admitted_slots[", integer_to_list(Index), "]\n",
        "      } else if u8:", integer_to_list(Index + 1),
        " < admitted_occupied {\n",
        "        admitted_slots[", integer_to_list(Index + 1), "]\n",
        "      } else { zero!<MailboxSlot>() };\n"
    ];
compaction_binding(Index, _Capacity) ->
    [
        "      let compacted_", integer_to_list(Index),
        " = zero!<MailboxSlot>();\n"
    ].

%%%
%%% Top-level streams
%%%

egress_demux(#{output_names := OutputNames}) ->
    [
        "proc EgressDemux {\n",
        "  egress_in: chan<Egress> in;\n",
        [
            ["  ", name(Port), "_out: chan<axis::Frame> out;\n"]
            || Port <- OutputNames
        ],
        "\n  config(egress_in: chan<Egress> in,\n",
        [
            ["         ", name(Port), "_out: chan<axis::Frame> out",
                separator(Index, length(OutputNames)), "\n"]
            || {Index, Port} <- lists:enumerate(0, OutputNames)
        ],
        "  ) {\n",
        "    (egress_in, ",
        join_with(", ", [[name(Port), "_out"] || Port <- OutputNames]),
        ")\n",
        "  }\n\n",
        "  init { () }\n\n",
        "  next(state: ()) {\n",
        "    let (tok, egress) = recv(join(), egress_in);\n",
        "    let _send_tok = match egress.port {\n",
        [
            [
                "      OutputPort::", uppercase(Port), " =>\n",
                "        send(tok, ", name(Port),
                "_out, egress.frame),\n"
            ]
            || Port <- OutputNames
        ],
        "    };\n",
        "    state\n",
        "  }\n",
        "}\n\n"
    ].

top(#{output_names := OutputNames}) ->
    [
        "pub proc Top {\n",
        "  ext_recv: chan<axis::Beat> in;\n",
        [
            ["  ", name(Port), "_send: chan<axis::Beat> out;\n"]
            || Port <- OutputNames
        ],
        "\n  config(ext_recv: chan<axis::Beat> in,\n",
        [
            ["         ", name(Port), "_send: chan<axis::Beat> out,\n"]
            || Port <- lists:droplast(OutputNames)
        ],
        "         ", name(lists:last(OutputNames)),
        "_send: chan<axis::Beat> out) {\n",
        "    let (req_p, req_c) = chan<axis::Frame, u32:1>(\"req\");\n",
        "    let (admit_p, admit_c) = chan<u1, u32:1>(\"admit\");\n",
        "    let (egress_p, egress_c) =\n",
        "      chan<Egress, EGRESS_DEPTH>(\"egress\");\n",
        [
            [
                "    let (", name(Port), "_p, ", name(Port),
                "_c) = chan<axis::Frame, u32:1>(\"", name(Port), "\");\n"
            ]
            || Port <- OutputNames
        ],
        "    spawn axis::ReservedRx(ext_recv, req_p, admit_c);\n",
        "    spawn Service(req_c, egress_p, admit_p);\n",
        "    spawn EgressDemux(egress_c, ",
        join_with(", ", [[name(Port), "_p"] || Port <- OutputNames]),
        ");\n",
        [
            [
                "    spawn axis::Tx(", name(Port), "_c, ", name(Port),
                "_send);\n"
            ]
            || Port <- OutputNames
        ],
        "    (ext_recv, ",
        join_with(", ", [[name(Port), "_send"] || Port <- OutputNames]),
        ")\n",
        "  }\n\n",
        "  init { () }\n",
        "  next(state: ()) { state }\n",
        "}\n"
    ].

%%%
%%% Naming and iodata helpers
%%%

uppercase(Atom) ->
    string:uppercase(atom_to_list(Atom)).

name(Atom) ->
    atom_to_list(Atom).

record_struct_name(Atom) ->
    string:titlecase(record_function_name(Atom)).

record_function_name(Atom) ->
    lists:delete($_, atom_to_list(Atom)).

separator(Index, Count) when Index + 1 < Count -> ",";
separator(_Index, _Count) -> "".

join_with(_Separator, []) ->
    [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].
