%%%% xls_statem_codegen
%%%%
%%%% Renders the closed XLS state-machine representation prepared by
%%%% xls_statem_lower. Erlang syntax and parser IR do not cross this boundary.

-module(xls_statem_codegen).
-moduledoc false.

-export([emit/1, shared_machine_width/1, shared_machine_width/2, shared_machine_layout/2, entry_value/5]).

-define(REDUCTION_SERVICE, xls_statem_reduction_service_codegen).

-type entry() :: #{
    phase := atom(),
    evaluation := #{body := iodata(), result := iodata(), failed := iodata()},
    layouts := [map()]
}.
-type cast_clause() :: #{
    tag := atom(),
    phase := atom(),
    body := iodata(),
    result := iodata()
}.
%% Complete renderer input, including the emitted failure-site catalog.
-type spec() :: #{
    failure_sites := [map()],
    source := file:filename(),
    imports := [atom()],
    capacity := 1..255,
    phases := [atom(), ...],
    message_names := [atom(), ...],
    message_words := #{atom() => 0..3},
    output_names := [atom(), ...],
    data_name := atom(),
    data_width := non_neg_integer(),
    record_declarations := iodata(),
    helper_functions := iodata(),
    init := xls_init:lowered(),
    entries := [entry(), ...],
    max_entry_effects := non_neg_integer(),
    casts := [cast_clause()],
    continuations := [atom()],
    internal_steps := [map()],
    retained_calls := none | map(),
    reductions := none | xls_statem_reduction_ir:reduction(),
    shared_service := ordinary | aggregate_only,
    mailbox_debug => boolean(),
    direct_actor_debug => boolean()
}.

-doc "Renders validated actor callbacks as singleton and shared-scheduler DSLX services.".
-spec emit(spec()) -> iolist().
emit(Spec) ->
    SharedService = maps:get(shared_service, Spec, ordinary),
    Body = [
        maps:get(record_declarations, Spec),
        maps:get(helper_functions, Spec),
        xls_statem_reduction_codegen:declarations(
            maps:get(reductions, Spec, none), SharedService
        ),
        xls_statem_reply_codegen:declarations(Spec),
        machine_declarations(Spec),
        xls_actor_observation:declarations(Spec),
        xls_statem_reduction_codegen:functions(
            maps:get(reductions, Spec, none), SharedService
        ),
        initial_machine(Spec),
        machine_codec(Spec),
        enter_function(Spec),
        entry_effects_valid_function(),
        xls_statem_reply_codegen:functions(Spec),
        dispatch_function(Spec),
        xls_statem_event_codegen:functions(Spec),
        machine_step_function(Spec),
        shared_machine_step_function(Spec),
        shared_executor(Spec),
        service(Spec),
        shared_service(Spec),
        egress_demux(Spec),
        top(Spec)
    ],
    [preamble(Spec), xls_failure_sites:emit(maps:get(failure_sites, Spec, []), Body)].

%%%
%%% Module declarations
%%%

%% Declares the actor vocabulary and imports optional runtime modules.
-spec preamble(spec()) -> iodata().
preamble(#{
    source := Source,
    imports := Imports,
    capacity := Capacity,
    phases := Phases,
    message_names := MessageNames,
    data_name := DataName
} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    [
        "// ", Source, ".x\n",
        "// This file is auto-generated by xls_parse. Manual changes will be\n",
        "// overwritten the next time it is generated.\n\n",
        xls_dslx_imports:emit([axis, bram, mailbox, scheduler, hls_failure, hls_bits] ++
            xls_scheduler_observation:imports(Spec) ++ xls_actor_observation:imports(Spec) ++
            case xls_statem_reply_codegen:enabled(Spec) of true -> [hls_reply]; false -> [] end, Imports),
        "\n",
        "const MAILBOX_CAPACITY = u8:", integer_to_list(Capacity), ";\n",
        "const MAILBOX_DEPTH = u32:", integer_to_list(Capacity), ";\n\n",
        "pub enum Tag : u8 {\n",
        "  NONE = u8:0,\n",
        "  ERROR = u8:1,\n",
        "  ", xls_names:enum_member(DataName), " = u8:2,\n",
        [
            [
                "  ", xls_names:enum_member(Name), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Name} <- lists:enumerate(3, MessageNames)
        ],
        reduction_tag_member(Reductions, MessageNames),
        "}\n\n",
        phase_declaration(Phases),
        "pub enum Directive : u2 {\n",
        "  CONSUME = u2:0,\n",
        "  POSTPONE = u2:1,\n",
        "  FAIL = u2:2,\n",
        "}\n\n"
    ].

reduction_tag_member(none, _MessageNames) ->
    [];
reduction_tag_member(Reductions, MessageNames)
        when length(MessageNames) =< 252 ->
    xls_statem_reduction_codegen:tag_member(
        Reductions,
        3 + length(MessageNames)
    );
reduction_tag_member(_Reductions, MessageNames) ->
    error({too_many_hls_tags_for_reduction, length(MessageNames), 252}).

phase_declaration(Phases) ->
    [
        "enum Phase : u8 {\n",
        [
            [
                "  ", xls_names:enum_member(Name), " = u8:", integer_to_list(Index),
                ",\n"
            ]
            || {Index, Name} <- lists:enumerate(0, Phases)
        ],
        "}\n\n"
    ].

%% Defines state, effects and executor boundaries with only enabled private storage.
-spec machine_declarations(spec()) -> iodata().
machine_declarations(#{
    capacity := Capacity,
    output_names := OutputNames,
    max_entry_effects := MaxEntryEffects,
    message_words := MessageWords,
    entries := Entries,
    data_name := DataName,
    data_width := DataWidth
} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    SharedService = maps:get(shared_service, Spec, ordinary),
    ReductionWidth = xls_statem_reduction_codegen:private_width(Reductions),
    DataStruct = xls_names:record_type(DataName),
    EventWidth = event_width(Spec),
    MachineBits = shared_machine_width(DataWidth, ReductionWidth) + EventWidth + xls_statem_reply_codegen:width(Spec),
    EffectCapacity = max(1, MaxEntryEffects),
    EffectPayloadBits = max(entry_effect_payload_bits(Entries, MessageWords),
        case xls_statem_reply_codegen:enabled(Spec) of true -> 128; false -> 0 end),
    [
        "pub enum OutputPort : u8 {\n",
        [
            [
                "  ", xls_names:enum_member(Port), " = u8:",
                integer_to_list(Index), ",\n"
            ]
            || {Index, Port} <- lists:enumerate(0, OutputNames)
        ],
        "}\n\n",
        "pub struct Egress {\n",
        "  port: OutputPort,\n",
        "  frame: axis::Frame,\n",
        "}\n\n",
        "pub const EGRESS_DEPTH = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub const ENTRY_EFFECT_CAPACITY = u32:",
        integer_to_list(EffectCapacity), ";\n\n",
        "pub const ENTRY_EFFECT_PAYLOAD_BITS = u32:",
        integer_to_list(EffectPayloadBits), ";\n\n",
        "// Sorry: this is a hand-rolled tagged union. DSLX cannot yet express\n",
        "// entry variants whose fields retain their message types.\n",
        "pub struct EntryEffects {\n",
        "  layout: u8,\n",
        "  payloads: bits[", integer_to_list(EffectPayloadBits), "],\n",
        "}\n\n",
        "struct EntryOutcome {\n",
        "  data: ", DataStruct, ",\n",
        "  effects: EntryEffects,\n",
        ?REDUCTION_SERVICE:machine_state_field(Reductions),
        "  failure: hls_failure::Code,\n",
        "}\n\n",
        "type MailboxSlot = mailbox::Slot;\n\n",
        "struct Machine {\n",
        "  phase: Phase,\n",
        "  entered_from: Phase,\n",
        "  data: ", DataStruct, ",\n",
        ?REDUCTION_SERVICE:machine_state_field(Reductions),
        "  slots: MailboxSlot[", integer_to_list(Capacity), "],\n",
        "  occupied: u8,\n",
        xls_statem_reply_codegen:optional(Spec, "  replies: ReplyBook,\n"),
        xls_statem_event_codegen:optional(Spec, "  next_event: u8,\n"),
        "  enter_pending: u1,\n",
        "  entry_effect_index: u8,\n",
        "  // Reserves one queue slot for the frame being assembled.\n",
        "  admission_pending: u1,\n",
        "  // A failed service ignores input until reset.\n",
        "  failure: hls_failure::Code,\n",
        "}\n\n",
        "struct SharedMachine {\n",
        "  phase: Phase,\n",
        "  entered_from: Phase,\n",
        "  data: ", DataStruct, ",\n",
        ?REDUCTION_SERVICE:machine_state_field(Reductions),
        xls_statem_reply_codegen:optional(Spec, "  replies: ReplyBook,\n"),
        xls_statem_event_codegen:optional(Spec, "  next_event: u8,\n"),
        "  enter_pending: u1,\n",
        "  failure: hls_failure::Code,\n",
        "}\n\n",
        "pub type MachineBits = bits[", integer_to_list(MachineBits), "];\n\n",
        "pub type MachineRamReadReq = bram::ReadReq;\n",
        "pub type MachineRamReadResp = bram::ReadResp<u32:",
        integer_to_list(MachineBits), ">;\n",
        "pub type MachineRamWriteReq = bram::WriteReq<u32:",
        integer_to_list(MachineBits), ">;\n",
        "pub type MachineRamWriteResp = bram::WriteResp;\n\n",
        "pub type MailboxRamReadReq = mailbox::RamReadReq;\n",
        "pub type MailboxRamReadResp = mailbox::RamReadResp;\n",
        "pub type MailboxRamWriteReq = mailbox::RamWriteReq;\n",
        "pub type MailboxRamWriteResp = mailbox::RamWriteResp;\n\n",
        "struct MachineStep {\n",
        "  machine: Machine,\n",
        "  egress: Egress,\n",
        "  egress_valid: u1,\n",
        "  admission_valid: u1,\n",
        "}\n\n",
        "pub type ScheduledRequest = mailbox::ScheduledRequest;\n\n",
        "pub struct ScheduledEffects {\n",
        "  slot: u32,\n",
        "  effects: EntryEffects,\n",
        "}\n\n",
        "struct SharedStep {\n",
        "  machine: SharedMachine,\n",
        "  effects: EntryEffects,\n",
        "  effects_valid: u1,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "  egress_blocked: u1,\n",
        "}\n\n",
        "struct SharedDispatch {\n",
        xls_statem_reply_codegen:optional(Spec, "  reply: axis::Frame,\n  reply_valid: bool,\n"),
        "  machine: SharedMachine,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "}\n\n",
        "pub struct SharedExecutorRequest {\n",
        "  slot: u32,\n",
        "  machine: MachineBits,\n",
        "  frame: axis::Frame,\n",
        ?REDUCTION_SERVICE:shared_executor_request_field(
            Reductions, SharedService
        ),
        "  received: u1,\n",
        "  mailbox_index: u8,\n",
        "  order_index: u8,\n",
        "  egress_ready: u1,\n",
        "}\n\n",
        "pub struct SharedExecutorResult {\n",
        "  slot: u32,\n",
        "  machine: MachineBits,\n",
        "  effects: EntryEffects,\n",
        "  effects_valid: u1,\n",
        "  dispatched: u1,\n",
        "  directive: Directive,\n",
        "  phase_boundary: u1,\n",
        "  egress_blocked: u1,\n",
        "  received: u1,\n",
        "  mailbox_index: u8,\n",
        "  order_index: u8,\n",
        "}\n\n",
        "enum SharedPhase : u3 {\n",
        "  BOOT = u3:0,\n",
        "  STARTUP = u3:1,\n",
        "  RUN = u3:2,\n",
        "}\n\n",
        "// XLS channel legalization currently confuses multiple otherwise-\n",
        "// identical SharedService instances connected to different external\n",
        "// RAM ports. INSTANCE_ID distinguishes those specializations; it is\n",
        "// neither actor state nor part of scheduling policy.\n",
        "struct SharedState<ACTOR_COUNT: u32, PRODUCER_COUNT: u32> {\n",
        "  instance_id: u32,\n",
        "  phase: SharedPhase,\n",
        "  next_valid: u1,\n",
        "  next_slot: u32,\n",
        "  in_flight: u1[ACTOR_COUNT],\n",
        ?REDUCTION_SERVICE:shared_state_fields(Reductions, SharedService),
        "  completed_valid: u1,\n",
        "  completed: SharedExecutorResult,\n",
        "  admission_cursor: u32,\n",
        "  cursor: u32,\n",
        "  startup_seen: u32,\n",
        "  pending: ScheduledRequest[PRODUCER_COUNT],\n",
        "  pending_valid: u1[PRODUCER_COUNT],\n",
        "  occupied: u8[ACTOR_COUNT],\n",
        "  order: u8[", integer_to_list(Capacity), "][ACTOR_COUNT],\n",
        "  postponed: u1[", integer_to_list(Capacity), "][ACTOR_COUNT],\n",
        "  // Mailbox work that has not yet been postponed in this phase.\n",
        "  mail_candidates: u1[ACTOR_COUNT],\n",
        "  // Entry work whose effect batch has not yet been classified.\n",
        "  entry_probes: u1[ACTOR_COUNT],\n",
        "  // Entry work known to need the scheduler's batch sequencer.\n",
        "  egress_waiters: u1[ACTOR_COUNT],\n",
        "  egress_busy: u1,\n",
        "  state_write_pending: u1,\n",
        "  mailbox_write_pending: u1,\n",
        "}\n\n"
    ].

-doc false.
-spec shared_machine_width(non_neg_integer()) -> pos_integer().
shared_machine_width(DataWidth) ->
    shared_machine_width(DataWidth, 0).

-doc false.
-spec shared_machine_width(non_neg_integer(), non_neg_integer()) ->
    pos_integer().
shared_machine_width(DataWidth, ReductionWidth) ->
    maps:get(width, shared_machine_layout(DataWidth, ReductionWidth)).

%% Low-to-high packed RAM layout, shared by the codec and passive debug taps.
-spec shared_machine_layout(non_neg_integer(), non_neg_integer()) -> map().
shared_machine_layout(DataWidth, ReductionWidth) ->
    {Width, Fields} = lists:foldl(fun({Name, Bits}, {Offset, Acc}) ->
        {Offset + Bits, Acc#{Name => #{offset => Offset, width => Bits}}}
    end, {0, #{}}, [{phase, 8}, {entered_from, 8}, {data, DataWidth},
        {enter_pending, 1}, {failure, 16}, {reduction, ReductionWidth}]),
    Fields#{width => Width}.

%%%
%%% Lowered callbacks
%%%

%% Initializes direct and shared actors from the same checked callback.
-spec initial_machine(spec()) -> iodata().
initial_machine(#{init := Init} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    [
        xls_init:emit("initial_machine", "Machine", Init),
        "fn shared_machine(machine: Machine) -> SharedMachine {\n",
        "  SharedMachine {\n",
        "    phase: machine.phase,\n",
        "    entered_from: machine.entered_from,\n",
        "    data: machine.data,\n",
        ?REDUCTION_SERVICE:machine_state_copy_field(Reductions),
        xls_statem_reply_codegen:optional(Spec, "    replies: machine.replies,\n"),
        xls_statem_event_codegen:optional(Spec, "    next_event: machine.next_event,\n"),
        "    enter_pending: machine.enter_pending,\n",
        "    failure: machine.failure,\n",
        "  }\n",
        "}\n\n",
        "fn initial_shared_machine() -> SharedMachine {\n",
        "  shared_machine(initial_machine())\n",
        "}\n\n"
    ].

%% Packs shared RAM rows; optional private fields follow the stable observation offsets.
-spec machine_codec(spec()) -> iodata().
machine_codec(#{data_name := DataName, data_width := DataWidth} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    ReductionWidth = xls_statem_reduction_codegen:private_width(Reductions),
    #{data := #{offset := DataStart}, enter_pending := #{offset := EnterStart},
        failure := #{offset := FailureStart}, reduction := #{offset := ReductionStart},
        width := ReductionEnd} = shared_machine_layout(DataWidth, ReductionWidth),
    DataFunction = xls_names:record_codec(DataName),
    [
        "fn machine_from_bits(raw: MachineBits) -> SharedMachine {\n",
        "  SharedMachine {\n",
        "    phase: raw[0:8] as Phase,\n",
        "    entered_from: raw[8:16] as Phase,\n",
        "    data: ", DataFunction, "_from_bits(raw[",
        integer_to_list(DataStart), ":", integer_to_list(EnterStart), "]),\n",
        xls_statem_reply_codegen:optional(Spec, ["    replies: hls_reply::from_bits<REPLY_CAPACITY>(raw[",
            integer_to_list(ReductionEnd + event_width(Spec)), ":",
            integer_to_list(ReductionEnd + event_width(Spec) + xls_statem_reply_codegen:width(Spec)), "]),\n"]),
        xls_statem_event_codegen:optional(Spec, ["    next_event: raw[", integer_to_list(ReductionEnd), ":", integer_to_list(ReductionEnd + 8), "],\n"]),
        "    enter_pending: raw[", integer_to_list(EnterStart), ":",
        integer_to_list(FailureStart), "],\n",
        "    failure: raw[", integer_to_list(FailureStart), ":",
        integer_to_list(FailureStart + 16), "],\n",
        ?REDUCTION_SERVICE:machine_decode_field(
            Reductions,
            ReductionStart,
            ReductionEnd
        ),
        "  }\n",
        "}\n\n",
        "fn bits_from_machine(machine: SharedMachine) -> MachineBits {\n",
        xls_statem_reply_codegen:optional(Spec, "  hls_reply::to_bits(machine.replies) ++\n"),
        xls_statem_event_codegen:optional(Spec, "  machine.next_event ++\n"),
        ?REDUCTION_SERVICE:machine_encode_prefix(Reductions),
        "  machine.failure ++\n",
        "    machine.enter_pending ++\n",
        "    bits_from_", DataFunction, "(machine.data) ++\n",
        "    (machine.entered_from as bits[8]) ++\n",
        "    (machine.phase as bits[8])\n",
        "}\n\n",
        "fn machine_read(slot: u32) -> MachineRamReadReq {\n",
        "  bram::read(slot)\n",
        "}\n\n",
        "fn machine_write(\n",
        "    slot: u32, machine: SharedMachine) -> MachineRamWriteReq {\n",
        "  bram::write(slot, bits_from_machine(machine))\n",
        "}\n\n"
    ].

%% Evaluates one checked phase entry and encodes its selected effect layout.
-spec enter_function(spec()) -> iodata().
enter_function(#{data_name := DataName, entries := Entries,
        message_words := MessageWords} = Spec) ->
    Layouts = entry_layouts(Entries),
    [
        "fn enter(old_phase: Phase, phase: Phase, data: ", xls_names:record_type(DataName),
        ") -> EntryOutcome {\n",
        "  match phase {\n",
        [entry_arm(Entry) || Entry <- Entries],
        "  }\n",
        "}\n\n",
        entry_effect_count_function(Layouts, Spec),
        entry_effect_function(Layouts, MessageWords, Spec),
        scheduled_effect_function(Spec)
    ].

entry_arm(#{phase := Phase,
        evaluation := #{body := Body, result := Result, failed := Failed, failure := Failure}}) ->
    [
        "    Phase::", xls_names:enum_member(Phase), " => {\n",
        xls_parse_io:indent(Body, 6),
        "      if ", Failed, " {\n",
        "        EntryOutcome { data, failure: ", Failure, ", ..zero!<EntryOutcome>() }\n",
        "      } else { ", Result, " }\n",
        "    },\n"
    ].

%% Each selected source leaf becomes the same typed value before control flow
%% rejoins. The expression lowerer still owns branch-local failure predicates.
-spec entry_value(iodata(), map(), pos_integer(), map(),
    none | map()) -> iodata().
entry_value(Result, #{phase := Phase, layout := Layout,
        actions := Effects, reduction := Reduction}, PayloadBits,
        MessageWords, Reductions) ->
    [
        "{\n",
        "  let evaluated = ", Result, ";\n",
        [entry_effect_binding(Index) || {Index, _} <- lists:enumerate(0, Effects)],
        "  EntryOutcome {\n",
        "    data: evaluated.0.1,\n",
        entry_reduction_field(Reductions, Reduction =/= none, Phase),
        "    failure: hls_failure::NONE,\n",
        "    effects: EntryEffects {\n",
        "      layout: u8:", integer_to_list(Layout), ",\n",
        "      payloads: ", entry_payload_expression(Effects, PayloadBits, MessageWords), ",\n",
        "    },\n",
        "  }\n",
        "}"
    ].

entry_reduction_field(none, false, _Phase) -> [];
entry_reduction_field(_Reductions, false, _Phase) ->
    "    reduction: zero!<ReductionState>(),\n";
entry_reduction_field(_Reductions, true, Phase) ->
    ["    reduction: reduction_open_site(ReductionSite::", xls_names:enum_member(Phase),
        ", evaluated.1.0, evaluated.1.1.1),\n"].

entry_layouts(Entries) ->
    lists:append([Layouts || #{layouts := Layouts} <- Entries]).

%% Counts the selected entry batch, including a reserved single-reply layout.
-spec entry_effect_count_function([map()], spec()) -> iodata().
entry_effect_count_function(Layouts, Spec) ->
    [
        "fn entry_effect_count(effects: EntryEffects) -> u8 {\n",
        "  match effects.layout {\n",
        [["    u8:", integer_to_list(Layout), " => u8:",
            integer_to_list(length(Actions)), ",\n"]
            || #{layout := Layout, actions := Actions} <- Layouts],
        reply_layout_count(Spec),
        "    _ => u8:0,\n",
        "  }\n",
        "}\n\n"
    ].

%% Decodes a selected effect into its statically routed output frame.
-spec entry_effect_function([map()], map(), spec()) -> iodata().
entry_effect_function(Layouts, MessageWords, Spec) ->
    [
        "fn entry_effect(effects: EntryEffects, index: u8) -> Egress {\n",
        "  match effects.layout {\n",
        [entry_effect_layout_arm(Layout, MessageWords) || Layout <- Layouts],
        reply_layout_effect(Spec),
        "    _ => zero!<Egress>(),\n",
        "  }\n",
        "}\n\n"
    ].

entry_effect_layout_arm(#{layout := Layout, actions := []}, _MessageWords) ->
    ["    u8:", integer_to_list(Layout), " => zero!<Egress>(),\n"];
entry_effect_layout_arm(#{layout := Layout, actions := Effects}, MessageWords) ->
    [
        "    u8:", integer_to_list(Layout), " => match index {\n",
        [entry_effect_index_arm(Index, Effect, Offset, MessageWords)
            || {Index, Effect, Offset} <- effect_offsets(Effects, MessageWords)],
        "      _ => zero!<Egress>(),\n",
        "    },\n"
    ].

entry_effect_index_arm(Index, Effect, Offset, MessageWords) ->
    Tag = maps:get(tag, Effect),
    Width = maps:get(Tag, MessageWords) * 32,
    [
        "      u8:", integer_to_list(Index), " => Egress {\n",
        "        port: OutputPort::", xls_names:enum_member(maps:get(port, Effect)), ",\n",
        "        frame: axis::pack(Tag::", xls_names:enum_member(Tag), " as u8,\n",
        "          effects.payloads[", integer_to_list(Offset), ":",
        integer_to_list(Offset + Width), "]),\n",
        "      },\n"
    ].

scheduled_effect_function(Spec) ->
    ["""
    pub fn scheduled_effect(
        scheduled: ScheduledEffects, index: u8) -> (Egress, u1, u1) {
      let count = entry_effect_count(scheduled.effects);
      let emit = index < count;
      let last = index + u8:1 >= count;
      (entry_effect(scheduled.effects, index), emit, last)
    }

    """, scheduled_reduction_prefix_function(Spec)].

scheduled_reduction_prefix_function(#{shared_service := aggregate_only,
        reductions := #{sites := Sites}, entries := Entries}) ->
    [
        "pub fn scheduled_reduction_prefix(\n",
        "    scheduled: ScheduledEffects) -> (u1, u8, u1) {\n",
        "  let count = entry_effect_count(scheduled.effects);\n",
        "  match scheduled.effects.layout {\n",
        [scheduled_reduction_prefix_arm(Site, Layout)
            || Site = #{phase := Phase} <- Sites,
                Layout = #{phase := LayoutPhase} <- entry_layouts(Entries),
                LayoutPhase =:= Phase],
        "    _ => (u1:0, u8:0, u1:0),\n",
        "  }\n",
        "}\n\n"
    ];
scheduled_reduction_prefix_function(_Spec) -> [].

scheduled_reduction_prefix_arm(#{population := #{size := Size}},
        #{layout := Layout, actions := Effects}) ->
    Valid = case length(Effects) >= Size of
        true -> "u1:1";
        false -> "u1:0"
    end,
    ["    u8:", integer_to_list(Layout), " => (", Valid, ", u8:",
        integer_to_list(Size), ", count == u8:", integer_to_list(Size), "),\n"].

%% TODO(XLS sum types): replace layout IDs, effect_offsets/2, and the raw-bit
%% payload codecs with a sum of typed ordered-message tuples. Keep storage at
%% the widest alternative (including its tag), not the sum of alternatives.
%% Then entry_effect/2 can pattern-match typed payloads instead of slicing bits.
%% Bounded path analysis and the topology's unconditional-prefix proof remain
%% necessary. See Roadmap.md, "XLS complaints".
entry_payload_expression([], EffectPayloadBits, _MessageWords) ->
    ["zero!<bits[", integer_to_list(EffectPayloadBits), "]>()"];
entry_payload_expression(Effects, EffectPayloadBits, MessageWords) ->
    lists:foldl(
        fun({Index, Effect, Offset}, Acc) ->
            Width = maps:get(maps:get(tag, Effect), MessageWords) * 32,
            ["bit_slice_update(\n",
                "          ", Acc, ",\n",
                "          u32:", integer_to_list(Offset), ",\n",
                "          effect_", integer_to_list(Index),
                ".payload[0:", integer_to_list(Width), "])"]
        end,
        ["zero!<bits[", integer_to_list(EffectPayloadBits), "]>()"],
        effect_offsets(Effects, MessageWords)
    ).

effect_offsets(Effects, MessageWords) ->
    {_End, Reversed} = lists:foldl(
        fun({Index, Effect}, {Offset, Acc}) ->
            Width = maps:get(maps:get(tag, Effect), MessageWords) * 32,
            {Offset + Width, [{Index, Effect, Offset} | Acc]}
        end,
        {0, []},
        lists:enumerate(0, Effects)
    ),
    lists:reverse(Reversed).

entry_effect_payload_bits(Entries, MessageWords) ->
    max(1, lists:max([
        lists:sum([
            maps:get(maps:get(tag, Effect), MessageWords) * 32
            || Effect <- maps:get(actions, Layout)
        ])
        || Layout <- entry_layouts(Entries)
    ])).

entry_effects_valid_function() ->
    [
        """
        fn entry_effects_valid(effects: EntryEffects) -> u1 {
          entry_effect_count(effects) != u8:0
        }

        """,
        "\n"
    ].

entry_effect_binding(Index) ->
    Reference = ["evaluated.2.", integer_to_list(Index)],
    [
        "        let effect_", integer_to_list(Index), " = axis::pack(\n",
        "          ", Reference, ".0 as u8, hls_bits::frame_payload(", Reference, ".2));\n"
    ].

%% Dispatches declared input records with optional caller ownership.
-spec dispatch_function(spec()) -> iodata().
dispatch_function(#{
    message_names := MessageNames,
    data_name := DataName,
    casts := Casts
} = Spec) ->
    DataStruct = xls_names:record_type(DataName),
    [
        "fn dispatch(frame: axis::Frame, phase: Phase, data: ", DataStruct,
        xls_statem_reply_codegen:optional(Spec, ", call_from: u64, call_error: u32"),
        ") -> (Phase, ", DataStruct, ", Directive, u1, hls_failure::Code", xls_statem_event_codegen:optional(Spec, ", u8"), xls_statem_reply_codegen:optional(Spec, ", u64, axis::Frame, bool"), ") {\n",
        xls_statem_reply_codegen:optional(Spec, "  if call_error != u32:0 { (phase, data, if call_error == u32:16 { Directive::CONSUME } else { Directive::FAIL }, false, if call_error == u32:16 { hls_failure::NONE } else { hls_failure::INTERNAL }, u8:0, u64:0, zero!<axis::Frame>(), true) } else {\n"),
        "  match frame.header.op as Tag {\n",
        [dispatch_tag_arm(Name, Casts, Spec) || Name <- MessageNames],
        "    _ => (phase, data, Directive::FAIL, u1:0, hls_failure::INVALID_MESSAGE", xls_statem_event_codegen:optional(Spec, ", u8:0"), xls_statem_reply_codegen:optional(Spec, ", u64:0, zero!<axis::Frame>(), true"), "),\n",
        "  }\n",
        xls_statem_reply_codegen:optional(Spec, "  }\n"),
        "}\n\n"
    ].

%% Checks a schema length before invoking its phase-specific callback.
-spec dispatch_tag_arm(atom(), [cast_clause()], spec()) -> iodata().
dispatch_tag_arm(Tag, Casts, Spec) ->
    TagCasts = [Cast || Cast <- Casts, maps:get(tag, Cast) =:= Tag],
    [
        "    Tag::", xls_names:enum_member(Tag), " => {\n",
        xls_statem_reply_codegen:optional(Spec, ["      if frame.header.payload_words != u8:",
            integer_to_list(maps:get(Tag, maps:get(message_words, Spec))),
            " { (phase, data, Directive::FAIL, false, hls_failure::REQUEST_LENGTH, u8:0, u64:0, zero!<axis::Frame>(), true) } else {\n"]),
        "      let message = ", xls_names:record_codec(Tag),
        "_from_bits(frame.payload);\n",
        "      match phase {\n",
        [dispatch_phase_arm(Cast) || Cast <- TagCasts],
        "        _ => (phase, data, Directive::FAIL, u1:0, hls_failure::INVALID_MESSAGE", xls_statem_event_codegen:optional(Spec, ", u8:0"), xls_statem_reply_codegen:optional(Spec, ", u64:0, zero!<axis::Frame>(), true"), "),\n",
        "      }\n",
        xls_statem_reply_codegen:optional(Spec, "      }\n"),
        "    },\n"
    ].

dispatch_phase_arm(#{
    phase := Phase,
    body := Body,
    result := Result
}) ->
    [
        "        Phase::", xls_names:enum_member(Phase), " => {\n",
        xls_parse_io:indent(Body, 10),
        xls_parse_io:indent(Result, 10),
        "        },\n"
    ].

%%%
%%% Bounded scheduler
%%%

%% Advances one singleton activation without committing a blocked reply.
-spec machine_step_function(spec()) -> iodata().
machine_step_function(#{
    capacity := Capacity,
    message_names := MessageNames,
    message_words := MessageWords
} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    #{
        eligible_bindings := EligibleBindings,
        found_expression := FoundExpression,
        selected_expression := SelectedExpression,
        compaction_bindings := CompactionBindings,
        compacted_array := CompactedArray,
        unblocked_array := UnblockedArray
    } = queue_expansion(Capacity),
    [
        "fn machine_step(\n",
        "    machine: Machine, frame: axis::Frame, received: u1,\n",
        "    egress_ready: u1) -> MachineStep {\n",
        "  if hls_failure::failed(machine.failure) {\n",
        direct_failure_step(Spec),
        ?REDUCTION_SERVICE:direct_after_failed(Reductions, Capacity),
        machine_entry_step(Reductions),
        xls_statem_event_codegen:direct_step(Spec),
        "  } else {\n",
        "      let tag_ok = ",
        input_tag_ok(Spec, MessageNames, MessageWords), ";\n",
        "      let accepted = received && tag_ok;\n",
        "      let invalid_input = received && !tag_ok;\n",
        "      let incoming_slot = MailboxSlot {\n",
        "        frame,\n",
        "        ..zero!<MailboxSlot>()\n",
        "      };\n",
        "      let admitted_slots = if accepted {\n",
        "        update(machine.slots, machine.occupied as u32, incoming_slot)\n",
        "      } else { machine.slots };\n",
        "      let admitted_occupied = machine.occupied + (accepted as u8);\n",
        EligibleBindings,
        "      let found = ", FoundExpression, ";\n",
        "      let selected = ", SelectedExpression, ";\n",
        "      let selected_frame = admitted_slots[selected as u32].frame;\n",
        "      let dispatchable = found && !invalid_input;\n",
        xls_statem_reply_codegen:admit(Spec, direct),
        ?REDUCTION_SERVICE:direct_dispatch_bindings(Reductions, Spec),
        "      let invalid_repeat = ", xls_statem_reply_codegen:optional(Spec, "(dispatchable && is_call(selected_frame.header.op) && directive == Directive::POSTPONE) || "), "dispatchable && repeat_phase &&\n",
        "        (directive != Directive::CONSUME ||\n",
        "         next_phase != machine.phase);\n",
        ?REDUCTION_SERVICE:direct_effective_binding(Reductions),
        "      let selected_slot = admitted_slots[selected as u32];\n",
        "      let postponed_slot = MailboxSlot {\n",
        "        postponed: u1:1,\n",
        "        ..selected_slot\n",
        "      };\n",
        "      let postponed_slots = update(\n",
        "        admitted_slots, selected as u32, postponed_slot);\n",
        CompactionBindings,
        "      let compacted_slots = ", CompactedArray, ";\n",
        "      let transition_slots = match directive {\n",
        "        Directive::CONSUME => compacted_slots,\n",
        "        Directive::POSTPONE => postponed_slots,\n",
        "        Directive::FAIL => admitted_slots,\n",
        "      };\n",
        "      let candidate_slots = if effective {\n",
        "        transition_slots\n",
        "      } else { admitted_slots };\n",
        "      let candidate_occupied = if effective &&\n",
        "          directive == Directive::CONSUME {\n",
        "        admitted_occupied - u8:1\n",
        "      } else { admitted_occupied };\n",
        "      let candidate_phase = if effective {\n",
        "        next_phase\n",
        "      } else { machine.phase };\n",
        "      let candidate_data = if effective {\n",
        "        next_data\n",
        "      } else { machine.data };\n",
        "      let phase_changed = candidate_phase != machine.phase;\n",
        "      let phase_boundary = phase_changed ||\n",
        "        (effective && repeat_phase);\n",
        "      let unblocked_slots = ", UnblockedArray, ";\n",
        "      let final_slots = if phase_boundary {\n",
        "        unblocked_slots\n",
        "      } else { candidate_slots };\n",
        ?REDUCTION_SERVICE:direct_failed_binding(Reductions),
        xls_statem_reply_codegen:finish(Spec, direct),
        reply_failure_binding(Spec),
        "      let admission_pending =\n",
        "        machine.admission_pending && !received;\n",
        "      // Preserve occupied + admission_pending <= capacity.\n",
        "      let reserve = !failed && !received && !admission_pending &&\n",
        "        candidate_occupied < MAILBOX_CAPACITY;\n",
        "      let next_machine = Machine {\n",
        "        phase: ", xls_statem_reply_codegen:optional(Spec, "if contract_fault { machine.phase } else { "), "candidate_phase", xls_statem_reply_codegen:optional(Spec, " }"), ",\n",
        "        entered_from: if phase_boundary {\n",
        "          machine.phase\n",
        "        } else { machine.entered_from },\n",
        "        data: ", xls_statem_reply_codegen:optional(Spec, "if contract_fault { machine.data } else { "), "candidate_data", xls_statem_reply_codegen:optional(Spec, " }"), ",\n",
        xls_statem_reply_codegen:optional(Spec, "        replies: reply_book,\n"),
        xls_statem_event_codegen:optional(Spec, "        next_event: if effective && !failed { next_event } else { u8:0 },\n"),
        ?REDUCTION_SERVICE:direct_reduction_field(Reductions),
        "        slots: ", xls_statem_reply_codegen:optional(Spec, "if failed && dispatchable { compacted_slots } else { "), "final_slots", xls_statem_reply_codegen:optional(Spec, " }"), ",\n",
        "        occupied: ", xls_statem_reply_codegen:optional(Spec, "if failed && dispatchable { admitted_occupied - u8:1 } else { "), "candidate_occupied", xls_statem_reply_codegen:optional(Spec, " }"), ",\n",
        "        enter_pending: effective && phase_boundary && !failed,\n",
        "        admission_pending: admission_pending || reserve,\n",
        "        failure,\n",
        "        ..machine\n",
        "      };\n",
        xls_statem_reply_codegen:optional(Spec, ["      if response_valid && !egress_ready {\n",
            "        MachineStep { machine: Machine { slots: admitted_slots, occupied: admitted_occupied,\n",
            "          admission_pending: machine.admission_pending && !received, ..machine }, ..zero!<MachineStep>() }\n",
            "      } else {\n"]),
        "      MachineStep {\n",
        "        machine: next_machine,\n",
        "        admission_valid: reserve,\n",
        direct_reply_effect(Spec),
        "        ..zero!<MachineStep>()\n",
        "      }\n",
        xls_statem_reply_codegen:optional(Spec, "      }\n"),
        "  }\n",
        "}\n\n"
    ].

machine_entry_step(Reductions) ->
    [
        "    let outcome = enter(\n",
        "      machine.entered_from, machine.phase, machine.data);\n",
        "    let effects = outcome.effects;\n",
        "    let effect_count = entry_effect_count(effects);\n",
        "    let has_effect = machine.entry_effect_index < effect_count;\n",
        "    let effect = entry_effect(\n",
        "      effects, machine.entry_effect_index);\n",
        ?REDUCTION_SERVICE:direct_entry_bindings(Reductions),
        "    let can_advance = !entry_failed && (!has_effect || egress_ready);\n",
        "    let next_effect_index = machine.entry_effect_index +\n",
        "      ((has_effect && can_advance) as u8);\n",
        "    let entry_complete = can_advance &&\n",
        "      next_effect_index >= effect_count;\n",
        "    let reserve = entry_complete &&\n",
        "      !machine.admission_pending &&\n",
        "      machine.occupied < MAILBOX_CAPACITY;\n",
        "    let advanced_machine = Machine {\n",
        "      data: if entry_complete { outcome.data } else { machine.data },\n",
        ?REDUCTION_SERVICE:direct_entry_reduction_field(Reductions),
        "      enter_pending: !entry_complete && !entry_failed,\n",
        "      entry_effect_index: if entry_complete {\n",
        "        u8:0\n",
        "      } else { next_effect_index },\n",
        "      admission_pending: machine.admission_pending || reserve,\n",
        "      failure: entry_failure,\n",
        "      ..machine\n",
        "    };\n",
        "    MachineStep {\n",
        "      machine: if can_advance || entry_failed { advanced_machine }\n",
        "        else { machine },\n",
        "      egress: effect,\n",
        "      egress_valid: has_effect && can_advance,\n",
        "      admission_valid: reserve,\n",
        "    }\n"
    ].

%% Evaluates mailbox and entry callbacks for scheduler-owned state.
-spec shared_machine_step_function(spec()) -> iodata().
shared_machine_step_function(#{
    message_names := MessageNames,
    message_words := MessageWords
} = Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    SharedService = maps:get(shared_service, Spec, ordinary),
    [
        ?REDUCTION_SERVICE:shared_machine_support(
            Reductions, SharedService
        ),
        "fn shared_machine_dispatch(\n",
        "    machine: SharedMachine, frame: axis::Frame, received: u1)\n",
        "    -> SharedDispatch {\n",
        "  if hls_failure::failed(machine.failure) {\n",
        "    SharedDispatch { machine, ..zero!<SharedDispatch>() }\n",
        "  } else if machine.enter_pending || !received {\n",
        "    SharedDispatch { machine, ..zero!<SharedDispatch>() }\n",
        "  } else {\n",
        "    let tag_ok = ",
        input_tag_ok(Spec, MessageNames, MessageWords), ";\n",
        xls_statem_reply_codegen:admit(Spec, shared),
        ?REDUCTION_SERVICE:shared_dispatch_bindings(
            Reductions, SharedService, Spec
        ),
        "    let invalid_repeat = ", xls_statem_reply_codegen:optional(Spec, "(tag_ok && is_call(frame.header.op) && directive == Directive::POSTPONE) || "), "tag_ok && repeat_phase &&\n",
        "      (directive != Directive::CONSUME ||\n",
        "       next_phase != machine.phase);\n",
        ?REDUCTION_SERVICE:shared_dispatch_effective_binding(
            Reductions, SharedService
        ),
        "    let phase_changed = effective && next_phase != machine.phase;\n",
        "    let phase_boundary = phase_changed ||\n",
        "      (effective && repeat_phase);\n",
        ?REDUCTION_SERVICE:shared_dispatch_failed_binding(
            Reductions, SharedService
        ),
        xls_statem_reply_codegen:finish(Spec, shared),
        reply_failure_binding(Spec),
        "    let next_machine = SharedMachine {\n",
        "      phase: if effective", xls_statem_reply_codegen:optional(Spec, " && !contract_fault"), " { next_phase } else { machine.phase },\n",
        "      entered_from: if phase_boundary {\n",
        "        machine.phase\n",
        "      } else { machine.entered_from },\n",
        "      data: if effective", xls_statem_reply_codegen:optional(Spec, " && !contract_fault"), " { next_data } else { machine.data },\n",
        xls_statem_reply_codegen:optional(Spec, "      replies: reply_book,\n"),
        xls_statem_event_codegen:optional(Spec, "      next_event: if effective && !failed { next_event } else { u8:0 },\n"),
        ?REDUCTION_SERVICE:shared_dispatch_reduction_field(
            Reductions, SharedService
        ),
        "      enter_pending: effective && phase_boundary && !failed,\n",
        "      failure,\n",
        "      ..machine\n",
        "    };\n",
        "    SharedDispatch {\n",
        "      machine: next_machine,\n",
        xls_statem_reply_codegen:optional(Spec, "      reply: response, reply_valid: response_valid,\n"),
        case xls_statem_reply_codegen:enabled(Spec) of
            true -> "      dispatched: failed || effective,\n      directive: if failed { Directive::CONSUME } else { directive },\n";
            false -> [?REDUCTION_SERVICE:shared_dispatch_dispatched_field(Reductions, SharedService), "      directive,\n"]
        end,
        "      phase_boundary,\n",
        "      ..zero!<SharedDispatch>()\n",
        "    }\n",
        "  }\n",
        "}\n\n",
        "fn shared_machine_enter(machine: SharedMachine, egress_ready: u1)\n",
        "    -> SharedStep {\n",
        "  if hls_failure::failed(machine.failure) || !machine.enter_pending {\n",
        "    SharedStep { machine, ..zero!<SharedStep>() }\n",
        "  } else {\n",
        ?REDUCTION_SERVICE:shared_entry_step(Reductions),
        "  }\n",
        "}\n\n"
    ].

%% A shared scheduler owns mailbox ordering and actor state. This stateless
%% boundary contains only the actor-specific work, allowing XLS to pipeline
%% several distinct actor activations without putting either RAM in the
%% recurrence.
%% Returns one atomic activation outcome to the shared scheduler.
-spec shared_executor(spec()) -> iodata().
shared_executor(Spec) ->
    ["""
    pub fn shared_execute(request: SharedExecutorRequest) ->
        SharedExecutorResult {
      let machine = machine_from_bits(request.machine);
    """,
      "\n",
      xls_statem_event_codegen:shared_dispatch(Spec),
      xls_statem_reply_codegen:optional(Spec, ["  let dispatched = if dispatched.reply_valid && !request.egress_ready {\n",
          "    SharedDispatch { machine, ..zero!<SharedDispatch>() }\n  } else { dispatched };\n"]),
    """
    """, "  let entered = ", shared_reply_effect(Spec), "shared_machine_enter(\n",
        "    dispatched.machine, request.egress_ready)", xls_statem_reply_codegen:optional(Spec, " }"), ";\n", """
      SharedExecutorResult {
        slot: request.slot,
        machine: bits_from_machine(entered.machine),
        effects: entered.effects,
        effects_valid: entered.effects_valid,
        dispatched: dispatched.dispatched,
        directive: dispatched.directive,
        phase_boundary: dispatched.phase_boundary,
        egress_blocked: entered.egress_blocked,
        received: request.received,
        mailbox_index: request.mailbox_index,
        order_index: request.order_index,
      }
    }

    pub proc SharedExecutor {
      request_in: chan<SharedExecutorRequest> in;
      result_out: chan<SharedExecutorResult> out;

      config(
          request_in: chan<SharedExecutorRequest> in,
          result_out: chan<SharedExecutorResult> out
      ) {
        (request_in, result_out)
      }

      init { () }

      next(state: ()) {
        let (tok, request) = recv(join(), request_in);
        let _done = send(tok, result_out, shared_execute(request));
        state
      }
    }

    """].

%% Connects singleton admissions and output readiness to the actor step.
-spec service(spec()) -> iodata().
service(Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    [
        "pub proc Service {\n",
        "  req_in: chan<axis::Frame> in;\n",
        "  egress_out: chan<Egress> out;\n",
        "  admission_out: chan<u1> out;\n",
        xls_actor_observation:proc_field(Spec),
        "\n",
        "  config(req_in: chan<axis::Frame> in,\n",
        "         egress_out: chan<Egress> out,\n",
        "         admission_out: chan<u1> out",
        xls_actor_observation:config_parameter(Spec), ") {\n",
        "    (req_in, egress_out, admission_out",
        xls_actor_observation:config_value(Spec), ")\n",
        "  }\n\n",
        "  init { (initial_machine(), u1:0) }\n\n",
        "  next(state: (Machine, u1)) {\n",
        "    let (machine, admission_valid) = state;\n",
        xls_actor_observation:sample(Spec),
        "    // Reserve capacity in machine_step, then publish its credit\n",
        "    // from registered state to break receive/admission feedback.\n",
        "    // Its token is independent of the current receive and egress.\n",
        "    let _admission_tok = send_if(\n",
        "      join(), admission_out, admission_valid, u1:1);\n",
        case xls_statem_reply_codegen:enabled(Spec) of
            true -> ["    let receive_enabled = machine.admission_pending && (hls_failure::failed(machine.failure) || (!machine.enter_pending && machine.next_event == u8:0", ?REDUCTION_SERVICE:direct_receive_gate(Reductions), "));\n"];
            false -> [
        "    let receive_enabled = !hls_failure::failed(machine.failure) &&\n",
        "      !machine.enter_pending && machine.admission_pending",
        xls_statem_event_codegen:optional(Spec, " && machine.next_event == u8:0"),
        ?REDUCTION_SERVICE:direct_receive_gate(Reductions), ";\n"
            ]
        end,
        "    let (tok, frame, received) = recv_if_non_blocking(\n",
        "      join(), req_in, receive_enabled, zero!<axis::Frame>());\n",
        "    let stepped = machine_step(machine, frame, received, u1:1);\n",
        "    let _egress_tok = send_if(\n",
        "      tok, egress_out, stepped.egress_valid, stepped.egress);\n",
        "    (stepped.machine, stepped.admission_valid)\n",
        "  }\n",
        "}\n\n"
    ].

%% Emits RAM-backed scheduling, retaining one pending request per producer.
-spec shared_service(spec()) -> iodata().
shared_service(Spec) ->
    Reductions = maps:get(reductions, Spec, none),
    SharedService = maps:get(shared_service, Spec, ordinary),
    RamParameters = xls_scheduler_ram_dslx:parameters([], []),
    RamNames = xls_scheduler_ram_dslx:names([]),
    [
    ?REDUCTION_SERVICE:shared_service_helpers(Reductions, SharedService),
    """
    fn ready_selection<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        cursor: u32,
        in_flight: u1[ACTOR_COUNT]) -> (u1, u32) {
      scheduler::select(
        scheduler::Candidates<ACTOR_COUNT> {
          entry: state.entry_probes,
          mail: state.mail_candidates,
          egress: state.egress_waiters,
          ..zero!<scheduler::Candidates<ACTOR_COUNT>>()
        }, state.egress_busy, in_flight, cursor)
    }

    // Translate actor-specific results into the shared metadata transition.
    fn retire_actor<ACTOR_COUNT: u32, PRODUCER_COUNT: u32>(
        state: SharedState<ACTOR_COUNT, PRODUCER_COUNT>,
        valid: u1,
        slot: u32,
        stepped: SharedStep,
        received: u1,
        mailbox_index: u8,
        order_index: u8) -> SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
      let metadata = mailbox::retire(
        mailbox::Metadata<ACTOR_COUNT, MAILBOX_DEPTH> {
          occupied: state.occupied,
          order: state.order,
          postponed: state.postponed,
          mail_candidates: state.mail_candidates,
          entry_probes: state.entry_probes,
          egress_waiters: state.egress_waiters,
        }, slot, order_index, mailbox_index,
        mailbox::Retirement {
          valid,
          consume: received && stepped.dispatched &&
            stepped.directive == Directive::CONSUME,
          postpone: received && stepped.dispatched &&
            stepped.directive == Directive::POSTPONE,
    """, "\n      phase_boundary: stepped.phase_boundary",
        xls_statem_reply_codegen:optional(Spec, " || hls_failure::failed(stepped.machine.failure)"), ",\n",
        "      failed: ", case xls_statem_reply_codegen:enabled(Spec) of
            true -> "false"; false -> "hls_failure::failed(stepped.machine.failure)" end, ",\n",
        "      enter_pending: stepped.machine.enter_pending",
        xls_statem_event_codegen:optional(Spec, " || stepped.machine.next_event != u8:0"),
        xls_statem_reply_codegen:optional(Spec, " || (hls_failure::failed(stepped.machine.failure) && hls_reply::first(stepped.machine.replies.slots, true).0)"), ",\n", """
          egress_blocked: stepped.egress_blocked,
        });
      SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
        occupied: metadata.occupied,
        order: metadata.order,
        postponed: metadata.postponed,
        mail_candidates: metadata.mail_candidates,
        entry_probes: metadata.entry_probes,
        egress_waiters: metadata.egress_waiters,
        ..state
      }
    }

    // One mailbox owner issues loaded activations to a stateless executor and
    // retires completed results. In-flight slot exclusion prevents stale
    // same-actor reads; a one-result skid slot lets credit collection continue
    // when an effect batch temporarily blocks retirement. A token carried
    // beside the metadata orders each activation's RAM writes before the next
    // activation's reads, independently of metadata pipeline placement.
    pub proc SharedService<
        ACTOR_COUNT: u32,
        PRODUCER_COUNT: u32,
        STARTUP_COUNT: u32,
        INSTANCE_ID: u32
    > {
      request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in;
      startup_in: chan<ScheduledRequest> in;
      egress_out: chan<ScheduledEffects> out;
    """,
        "\n", lists:join("\n", [["  ", Parameter, ";"]
            || Parameter <- RamParameters]),
        ?REDUCTION_SERVICE:shared_proc_field(Reductions, SharedService),
        xls_scheduler_observation:proc_field(Spec),
    """
      executor_request_out: chan<SharedExecutorRequest> out;
      executor_result_in: chan<SharedExecutorResult> in;

      config(
          request_in: chan<ScheduledRequest>[PRODUCER_COUNT] in,
          startup_in: chan<ScheduledRequest> in,
          egress_out: chan<ScheduledEffects> out,
    """,
        "\n", lists:join(",\n", [["      ", Parameter]
            || Parameter <- RamParameters]),
        ?REDUCTION_SERVICE:shared_config_parameter(
            Reductions, SharedService
        ),
        xls_scheduler_observation:config_parameter(Spec),
    """
      ) {
        let (executor_request_p, executor_request_c) =
          chan<SharedExecutorRequest, u32:1>("executor_request");
        let (executor_result_p, executor_result_c) =
          chan<SharedExecutorResult, u32:1>("executor_result");
        spawn SharedExecutor(executor_request_c, executor_result_p);
        (
          request_in,
          startup_in,
          egress_out,
    """,
        "\n", lists:join("\n", [["      ", Name, ","]
            || Name <- RamNames]),
        ?REDUCTION_SERVICE:shared_config_endpoint(Reductions, SharedService),
        xls_scheduler_observation:config_value(Spec),
    """
          executor_request_p,
          executor_result_c,
        )
      }

      init {
        (join(), SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
          instance_id: INSTANCE_ID,
          phase: SharedPhase::BOOT,
          ..zero!<SharedState<ACTOR_COUNT, PRODUCER_COUNT>>()
        })
      }

      next(prior: (token, SharedState<ACTOR_COUNT, PRODUCER_COUNT>)) {
        let (memory_tok, state) = prior;
    """,
        "\n", xls_scheduler_observation:sample(Spec),
    """
        // Each producer is visited once. Select one slot's value before
        // updating the array, keeping unrolled type inference linear.
        let capture_enabled = state.phase == SharedPhase::RUN;
        let (capture_tok, captured_pending, captured_pending_valid) =
          unroll_for! (producer, acc):
              (u32, (
                token,
                ScheduledRequest[PRODUCER_COUNT],
                u1[PRODUCER_COUNT]
              )) in u32:0..PRODUCER_COUNT {
            let (next_tok, request, captured) =
              recv_if_non_blocking(
                acc.0,
                request_in[producer],
                capture_enabled && !state.pending_valid[producer],
                zero!<ScheduledRequest>());
            (
              next_tok,
              update(acc.1, producer,
                if captured { request } else { state.pending[producer] }),
              update(acc.2, producer, state.pending_valid[producer] || captured)
            )
          }((memory_tok, state.pending, state.pending_valid));
    """,
        ?REDUCTION_SERVICE:shared_capture(Reductions, SharedService),
    """
        match state.phase {
          SharedPhase::BOOT => {
            let write_tok = send(
    """,
        "\n          ",
        ?REDUCTION_SERVICE:shared_capture_token(Reductions, SharedService),
        ",\n",
    """
              ram_write_req_out,
              machine_write(state.cursor, initial_shared_machine()));
            let (_done, _) = recv(write_tok, ram_write_resp_in);
            let entry_probes = update(
              state.entry_probes, state.cursor, u1:1);
            let next_state = if state.cursor + u32:1 == ACTOR_COUNT {
              SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
                phase: if STARTUP_COUNT == u32:0 {
                  SharedPhase::RUN
                } else {
                  SharedPhase::STARTUP
                },
                next_valid: STARTUP_COUNT == u32:0,
                next_slot: u32:0,
                cursor: u32:0,
                entry_probes,
                ..state
              }
            } else {
              SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
                cursor: state.cursor + u32:1,
                entry_probes,
                ..state
              }
            };
            (write_tok, next_state)
          },
          SharedPhase::STARTUP => {
            let (tok, request) = recv(
    """,
        ?REDUCTION_SERVICE:shared_capture_token(Reductions, SharedService),
        ", startup_in);\n",
    """
            let physical = state.occupied[request.slot];
            let write_tok = send(
              tok,
              mailbox_write_req_out,
              mailbox::write(
                request.slot, physical, MAILBOX_DEPTH, request.frame));
            let (_done, _) = recv(write_tok, mailbox_write_resp_in);
            let occupied = update(
              state.occupied, request.slot, physical + u8:1);
            let row = update(
              state.order[request.slot], physical as u32, physical);
            let order = update(state.order, request.slot, row);
            let mail_candidates = update(
              state.mail_candidates, request.slot, u1:1);
            let startup_seen = state.startup_seen + u32:1;
            let next_state = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              phase: if startup_seen == STARTUP_COUNT {
                SharedPhase::RUN
              } else {
                SharedPhase::STARTUP
              },
              next_valid: startup_seen == STARTUP_COUNT,
              next_slot: u32:0,
              startup_seen,
              occupied,
              order,
              mail_candidates,
              ..state
            };
            (write_tok, next_state)
          },
          SharedPhase::RUN => {
            // Return credits must already occupy a pending receptacle.
            // Using a newly captured credit here closes a combinational path
            // through result retirement, the router, and its credit output.
            let (credit_pending_valid, credit_busy) = mailbox::collect_credit(
              state.pending,
              state.pending_valid,
              captured_pending_valid,
              state.egress_busy);
            let buffered_can_retire = state.completed_valid &&
              (!state.completed.effects_valid || !credit_busy);
            let accept_executor_result =
              !state.completed_valid || buffered_can_retire;
            let (executor_result_tok, incoming_result, incoming_valid) =
              recv_if_non_blocking(
    """,
        "\n            ",
        ?REDUCTION_SERVICE:shared_capture_token(Reductions, SharedService),
        ",\n",
    """
                executor_result_in,
                accept_executor_result,
                zero!<SharedExecutorResult>());
            let result = if state.completed_valid {
              state.completed
            } else {
              incoming_result
            };
            let result_valid = state.completed_valid || incoming_valid;
            let retire_valid = result_valid &&
              (!result.effects_valid || !credit_busy);
            let resolved = SharedStep {
              machine: machine_from_bits(result.machine),
              effects: result.effects,
              effects_valid: result.effects_valid,
              dispatched: result.dispatched,
              directive: result.directive,
              phase_boundary: result.phase_boundary,
              egress_blocked: result.egress_blocked,
            };
            let credited = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              pending: captured_pending,
              pending_valid: credit_pending_valid,
              egress_busy: credit_busy ||
                (retire_valid && result.effects_valid),
    """,
        "\n          ..",
        ?REDUCTION_SERVICE:shared_state_source(Reductions, SharedService),
        "\n        };\n",
            ?REDUCTION_SERVICE:shared_retire_binding(Reductions),
    """
            let retired_in_flight = if retire_valid {
              update(retired.in_flight, result.slot, u1:0)
            } else {
              retired.in_flight
            };
            let completed_valid = if state.completed_valid {
              if buffered_can_retire { incoming_valid } else { u1:1 }
            } else {
              incoming_valid && !retire_valid
            };
            let completed = if state.completed_valid {
              if buffered_can_retire { incoming_result } else { state.completed }
            } else {
              incoming_result
            };
            let completion_blocked = completed_valid &&
              completed.effects_valid && retired.egress_busy;
    """,
            "\n",
            ?REDUCTION_SERVICE:shared_issue_bindings(
                Reductions, SharedService
            ),
    """
            let (received, order_index, mailbox_index) =
              mailbox::select(
                state.order[read_slot], state.occupied[read_slot],
                state.postponed[read_slot]);
            let (state_completion_tok, _) = recv_if(
              join(), ram_write_resp_in, state.state_write_pending,
              zero!<MachineRamWriteResp>());
            let (mailbox_completion_tok, _) = recv_if(
              join(), mailbox_write_resp_in,
              state.mailbox_write_pending,
              zero!<MailboxRamWriteResp>());
            let state_read_tok = send_if(
              memory_tok,
              ram_read_req_out,
              issue_valid,
              machine_read(read_slot));
            let mailbox_read_tok = send_if(
              memory_tok,
              mailbox_read_req_out,
              read_mailbox && received,
              mailbox::read(read_slot, mailbox_index, MAILBOX_DEPTH));
            let (state_done, response) = recv_if(
              state_read_tok,
              ram_read_resp_in,
              issue_valid,
              zero!<MachineRamReadResp>());
            let (mailbox_done, mailbox_response) = recv_if(
              mailbox_read_tok,
              mailbox_read_resp_in,
              read_mailbox && received,
              zero!<MailboxRamReadResp>());
            let reservation = mailbox::reserve_admission(
              retired.occupied,
              retired.order,
              retired.mail_candidates,
              retired.admission_cursor,
              captured_pending,
              credit_pending_valid,
              issue_valid,
              read_slot,
              retire_valid && hls_failure::failed(resolved.machine.failure),
              result.slot);
            let admitted = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              pending: captured_pending,
              pending_valid: reservation.pending_valid,
              occupied: reservation.occupied,
              order: reservation.order,
              mail_candidates: reservation.mail_candidates,
              admission_cursor: reservation.cursor,
              ..retired
            };
    """,
            ?REDUCTION_SERVICE:shared_post_issue_state(
                Reductions, SharedService
            ),
    """
            let issued_in_flight = if issue_valid {
              update(retired_in_flight, read_slot, u1:1)
            } else {
              retired_in_flight
            };
            let cursor = if issue_valid {
              if read_slot + u32:1 == ACTOR_COUNT {
                u32:0
              } else {
                read_slot + u32:1
              }
            } else {
              state.cursor
            };
            let selection_state = SharedState<
                ACTOR_COUNT, PRODUCER_COUNT> {
              in_flight: issued_in_flight,
    """,
            "\n          ..",
            ?REDUCTION_SERVICE:shared_post_issue_state_name(
                Reductions, SharedService
            ),
            "\n",
    """
            };
            let (selected_ready, selected_slot) =
    """,
            ?REDUCTION_SERVICE:shared_ready_selection_call(
                Reductions, SharedService
            ),
    """
            let ready = if completion_blocked {
              state.next_valid
            } else {
              selected_ready
            };
            let next_slot = if completion_blocked {
              state.next_slot
            } else {
              selected_slot
            };
            let frame = axis::frame_from_bits(mailbox_response.data);
            let executor_request = SharedExecutorRequest {
              slot: read_slot,
              machine: response.data,
              frame,
    """,
            "\n",
            ?REDUCTION_SERVICE:shared_executor_request_value(
                Reductions, SharedService
            ),
    """
              received: read_mailbox && received,
              mailbox_index,
              order_index,
              egress_ready: u1:1,
            };
            let executor_request_tok = send_if(
              join(state_done, mailbox_done),
              executor_request_out,
              issue_valid,
              executor_request);
            let scheduled = ScheduledEffects {
              slot: result.slot,
              effects: result.effects,
            };
            let egress_tok = send_if(
              executor_result_tok,
              egress_out,
              retire_valid && result.effects_valid,
              scheduled);
            let state_write_tok = send_if(
              join(state_read_tok, egress_tok),
              ram_write_req_out,
              retire_valid,
              machine_write(result.slot, resolved.machine));
            let admission_frame =
              captured_pending[reservation.admission.producer].frame;
            let mailbox_write_tok = send_if(
              join(mailbox_read_tok, egress_tok),
              mailbox_write_req_out,
              reservation.admission.valid,
              mailbox::write(
                reservation.admission.slot,
                reservation.admission.physical,
                MAILBOX_DEPTH,
                admission_frame));
            let _done = join(
              state_done,
              mailbox_done,
              state_write_tok,
              mailbox_write_tok,
              executor_request_tok,
              state_completion_tok,
              mailbox_completion_tok);
            let next_state = SharedState<ACTOR_COUNT, PRODUCER_COUNT> {
              next_valid: ready,
              next_slot,
              in_flight: issued_in_flight,
              completed_valid,
              completed,
              cursor,
              state_write_pending: retire_valid,
              mailbox_write_pending: reservation.admission.valid,
              ..selection_state
            };
            (join(state_write_tok, mailbox_write_tok), next_state)
          },
        }
      }
    }

    """
    ].

tag_ok_expression(MessageNames, MessageWords) ->
    join_with(" || ", [
        [
            "(frame.header.op == (Tag::", xls_names:enum_member(Name), " as u8) && ",
            "frame.header.payload_words == u8:",
            integer_to_list(maps:get(Name, MessageWords)), ")"
        ]
        || Name <- MessageNames
    ]).

queue_expansion(Capacity) ->
    Indexes = lists:seq(0, Capacity - 1),
    EligibleBindings = [eligible_binding(Index) || Index <- Indexes],
    FoundExpression = join_with(" || ", [
        ["eligible_", integer_to_list(Index)] || Index <- Indexes
    ]),
    SelectedExpression = lists:foldr(
        fun(Index, Else) ->
            [
                "if eligible_", integer_to_list(Index), " { u8:",
                integer_to_list(Index), " } else { ", Else, " }"
            ]
        end,
        "u8:0",
        Indexes
    ),
    CompactionBindings = [
        compaction_binding(Index, Capacity) || Index <- Indexes
    ],
    CompactedArray = [
        "[",
        join_with(", ", [
            ["compacted_", integer_to_list(Index)] || Index <- Indexes
        ]),
        "]"
    ],
    UnblockedArray = [
        "[",
        join_with(",\n        ", [
            [
                "MailboxSlot { postponed: u1:0, ..candidate_slots[",
                integer_to_list(Index), "] }"
            ]
            || Index <- Indexes
        ]),
        "]"
    ],
    #{
        eligible_bindings => EligibleBindings,
        found_expression => FoundExpression,
        selected_expression => SelectedExpression,
        compaction_bindings => CompactionBindings,
        compacted_array => CompactedArray,
        unblocked_array => UnblockedArray
    }.

eligible_binding(Index) ->
    [
        "      let eligible_", integer_to_list(Index), " = u8:",
        integer_to_list(Index), " < admitted_occupied &&\n",
        "        !admitted_slots[", integer_to_list(Index),
        "].postponed;\n"
    ].

compaction_binding(Index, Capacity) when Index + 1 < Capacity ->
    [
        "      let compacted_", integer_to_list(Index), " = if u8:",
        integer_to_list(Index), " < selected {\n",
        "        admitted_slots[", integer_to_list(Index), "]\n",
        "      } else if u8:", integer_to_list(Index + 1),
        " < admitted_occupied {\n",
        "        admitted_slots[", integer_to_list(Index + 1), "]\n",
        "      } else { zero!<MailboxSlot>() };\n"
    ];
compaction_binding(Index, _Capacity) ->
    [
        "      let compacted_", integer_to_list(Index),
        " = zero!<MailboxSlot>();\n"
    ].

%%%
%%% Top-level streams
%%%

egress_demux(#{output_names := OutputNames}) ->
    [
        "proc EgressDemux {\n",
        "  egress_in: chan<Egress> in;\n",
        [
            ["  ", name(Port), "_out: chan<axis::Frame> out;\n"]
            || Port <- OutputNames
        ],
        "\n  config(egress_in: chan<Egress> in,\n",
        [
            ["         ", name(Port), "_out: chan<axis::Frame> out",
                separator(Index, length(OutputNames)), "\n"]
            || {Index, Port} <- lists:enumerate(0, OutputNames)
        ],
        "  ) {\n",
        "    (egress_in, ",
        join_with(", ", [[name(Port), "_out"] || Port <- OutputNames]),
        ")\n",
        "  }\n\n",
        "  init { () }\n\n",
        "  next(state: ()) {\n",
        "    let (tok, egress) = recv(join(), egress_in);\n",
        "    let _send_tok = match egress.port {\n",
        [
            [
                "      OutputPort::", xls_names:enum_member(Port), " =>\n",
                "        send(tok, ", name(Port),
                "_out, egress.frame),\n"
            ]
            || Port <- OutputNames
        ],
        "    };\n",
        "    state\n",
        "  }\n",
        "}\n\n"
    ].

top(Spec = #{output_names := OutputNames}) ->
    [
        "pub proc Top {\n",
        "  ext_recv: chan<axis::Beat> in;\n",
        [
            ["  ", name(Port), "_send: chan<axis::Beat> out;\n"]
            || Port <- OutputNames
        ],
        xls_actor_observation:proc_field(Spec),
        "\n  config(ext_recv: chan<axis::Beat> in,\n",
        [
            ["         ", name(Port), "_send: chan<axis::Beat> out,\n"]
            || Port <- lists:droplast(OutputNames)
        ],
        "         ", name(lists:last(OutputNames)),
        "_send: chan<axis::Beat> out",
        xls_actor_observation:config_parameter(Spec), ") {\n",
        "    let (req_p, req_c) = chan<axis::Frame, u32:1>(\"req\");\n",
        "    let (admit_p, admit_c) = chan<u1, u32:1>(\"admit\");\n",
        "    let (egress_p, egress_c) =\n",
        "      chan<Egress, EGRESS_DEPTH>(\"egress\");\n",
        [
            [
                "    let (", name(Port), "_p, ", name(Port),
                "_c) = chan<axis::Frame, u32:1>(\"", name(Port), "\");\n"
            ]
            || Port <- OutputNames
        ],
        "    spawn axis::ReservedRx(ext_recv, req_p, admit_c);\n",
        "    spawn Service(req_c, egress_p, admit_p",
        xls_actor_observation:spawn_argument(Spec, "actor_debug_out"), ");\n",
        "    spawn EgressDemux(egress_c, ",
        join_with(", ", [[name(Port), "_p"] || Port <- OutputNames]),
        ");\n",
        [
            [
                "    spawn axis::Tx(", name(Port), "_c, ", name(Port),
                "_send);\n"
            ]
            || Port <- OutputNames
        ],
        "    (ext_recv, ",
        join_with(", ", [[name(Port), "_send"] || Port <- OutputNames]),
        xls_actor_observation:config_value(Spec),
        ")\n",
        "  }\n\n",
        "  init { () }\n",
        "  next(state: ()) { state }\n",
        "}\n"
    ].

%%%
%%% Naming and iodata helpers
%%%

name(Atom) ->
    atom_to_list(Atom).

separator(Index, Count) when Index + 1 < Count -> ",";
separator(_Index, _Count) -> "".

join_with(_Separator, []) ->
    [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].

%% The selector is present for finite events and for the shared retained-call outcome.
-spec event_width(map()) -> 0 | 8.
event_width(Spec) -> case maps:get(continuations, Spec, []) =/= [] orelse xls_statem_reply_codegen:enabled(Spec) of true -> 8; false -> 0 end.

%% Replies use the existing effect sequencer with one reserved frame layout.
-spec reply_layout_count(map()) -> iodata().
reply_layout_count(Spec) -> case xls_statem_reply_codegen:enabled(Spec) of
    false -> [];
    true -> ["    u8:", integer_to_list(xls_statem_reply_codegen:layout(Spec)), " => u8:1,\n"]
end.

%% The reply carries its original transaction ID through ordinary topology routing.
-spec reply_layout_effect(map()) -> iodata().
reply_layout_effect(Spec = #{retained_calls := #{port := Port}}) ->
    ["    u8:", integer_to_list(xls_statem_reply_codegen:layout(Spec)),
     " => Egress { port: OutputPort::", xls_names:enum_member(Port),
     ", frame: axis::frame_from_bits(effects.payloads as bits[128]) },\n"];
reply_layout_effect(_) -> [].

%% Caller-contract faults become actor failures without publishing the invalid reply.
-spec reply_failure_binding(map()) -> iodata().
reply_failure_binding(Spec) -> xls_statem_reply_codegen:optional(Spec,
    "    let contract_fault = failure == hls_failure::NONE && reply_book.failure == u32:15;\n"
    "    let failure = hls_failure::first(failure, if reply_book.failure != u32:0 { hls_failure::REPLY_CONTRACT } else { hls_failure::NONE });\n"
    "    let failed = hls_failure::failed(failure);\n").

%% Singleton outputs commit together with their checked callback state.
-spec direct_reply_effect(map()) -> iodata().
direct_reply_effect(Spec = #{retained_calls := #{port := Port}}) ->
    xls_statem_reply_codegen:optional(Spec, ["      egress: Egress { port: OutputPort::", xls_names:enum_member(Port),
        ", frame: response }, egress_valid: response_valid,\n"]);
direct_reply_effect(_) -> [].

%% A reply precedes phase entry; that entry remains pending for the next activation.
-spec shared_reply_effect(map()) -> iodata().
shared_reply_effect(Spec) -> case xls_statem_reply_codegen:enabled(Spec) of
    false -> [];
    true -> ["if dispatched.reply_valid { SharedStep { machine: dispatched.machine, effects: ",
        xls_statem_reply_codegen:effect(Spec), ", effects_valid: true, ..zero!<SharedStep>() } } else { "]
end.

%% Failed actors retire outstanding callers serially without executing application code.
-spec direct_failure_step(map()) -> iodata().
direct_failure_step(#{retained_calls := #{port := Port}}) ->
    ["    let admitted_slots = if received { update(machine.slots, machine.occupied as u32, MailboxSlot { frame, ..zero!<MailboxSlot>() }) } else { machine.slots };\n",
     "    let occupied = machine.occupied + received as u8;\n",
     "    let step = shared_machine_reply_failure(shared_machine(machine), admitted_slots[u32:0].frame, occupied != u8:0);\n",
     "    let commit = !step.reply_valid || egress_ready;\n",
     "    let consume = step.dispatched && commit;\n",
     "    let remaining = occupied - consume as u8;\n",
     "    let slots = unroll_for! (i, slots): (u32, MailboxSlot[MAILBOX_DEPTH]) in u32:0..MAILBOX_DEPTH {\n",
     "      update(slots, i, if consume && i + u32:1 < occupied as u32 { admitted_slots[i + u32:1] } else { admitted_slots[i] })\n",
     "    }(admitted_slots);\n",
     "    let pending = machine.admission_pending && !received;\n",
     "    let reserve = !pending && !received && remaining < MAILBOX_CAPACITY;\n",
     "    MachineStep { machine: Machine { replies: if commit { step.machine.replies } else { machine.replies },\n",
     "        occupied: remaining, slots, next_event: u8:0, enter_pending: false, admission_pending: pending || reserve, ..machine },\n",
     "      egress: Egress { port: OutputPort::", xls_names:enum_member(Port), ", frame: step.reply },\n",
     "      egress_valid: step.reply_valid && commit, admission_valid: reserve, ..zero!<MachineStep>() }\n"];
direct_failure_step(_) -> "    MachineStep { machine, ..zero!<MachineStep>() }\n".

%% Known calls reserve ownership before length validation, allowing their failure to complete them.
-spec input_tag_ok(map(), [atom()], map()) -> iodata().
input_tag_ok(Spec, Names, Words) -> case xls_statem_reply_codegen:enabled(Spec) of
    false -> tag_ok_expression(Names, Words);
    true -> join_with(" || ", [["frame.header.op == Tag::", xls_names:enum_member(Name), " as u8"] || Name <- Names])
end.
