%%%% xls_parse
%%%%
%%%% TODO:
%%%%    + erl_syntax might be a little more ergonomic, have a look

-module(xls_parse).
-module_doc """
Transforms the Erlang source for an `xls_gs` instance into a corresponding XLS
module.
""".
-export([to_xls/1]).
-export([reference/2, reference/1, instr/2, anonymous_variable/1]).
-export_type([ir/0, printable/0, static/0, phantom/0]).
-export_type([clause_state/0]).
-compile([export_all, nowarn_export_all]).  % TODO: remove export_all

-define(debug(X), begin io:format("~w@~w: ~p~n", [?FUNCTION_NAME, ?LINE, X]), X end).

-spec to_xls(string()) -> iolist().
-doc "Transpiles a supported Erlang actor module to a corresponding XLS module.".
to_xls(Filename) ->
    {ok, Forms} = parse_file(Filename),
    case find_optional_attribute(Forms, xls_states) of
        none -> to_xls_gs(Filename, Forms);
        {ok, StateNames} -> to_xls_statem(Filename, Forms, StateNames)
    end.

to_xls_gs(Filename, Forms) ->
    PublicStructNames = find_attribute(Forms, xls_tags),
    StateName = state(Forms),
    StateRecord = find_record(Forms, StateName),
    StateStructName = string:titlecase(lists:delete($_, atom_to_list(StateName))),
    ok = lists:foreach(
        fun(Name) ->
            validate_record_defaults(find_record(Forms, Name))
        end,
        [StateName | PublicStructNames]
    ),

    Emitted = ["// ", Filename, ".x\n",
    """
    // This file is auto-generated by xls_parse. Manual changes will be over-
    // written the next time it is generated. Better to modify the Erlang input.

    import axis;

    const NOREPLY = u1:0;  // some standard erlang tokens
    const REPLY = u1:1;
    const OK = u1:0;
    const ERROR_FUNCTION_CLAUSE = u32:1;
    const ERROR_MATCH_FAILURE = u32:2;


    """,
    "const MAX_PAYLOAD = u32:3;\n\n",  % TODO: don't bake this in.
    "pub enum Tag : u8 {\n",
    "  NONE = u8:0,\n",
    [
        ["  ", string:uppercase(atom_to_list(Atom)), " = u8:", integer_to_list(Index), ",\n"]
        ||  {Index, Atom} <- lists:enumerate([error, StateName | PublicStructNames])
    ],
    "}\n\n",
    [
        [struct_from_record(Record), "\n",
         structfrombits_from_record(Record), "\n",
         bitsfromstruct_from_record(Record), "\n"]
        ||  Op <- PublicStructNames,
            Record <- [find_record(Forms, Op)]
    ],
    struct_from_record(StateRecord), "\n",
    structfrombits_from_record(StateRecord), "\n",
    bitsfromstruct_from_record(StateRecord), "\n",
    """
    proc Service {
      req_in:   chan<axis::Frame> in;
      resp_out: chan<axis::Frame> out;
    """, "\n",
    ["  config(req_in: chan<axis::Frame> in, resp_out: chan<axis::Frame> out) {\n",
     "    (req_in, resp_out)\n",
     "  }\n\n"],
    % TODO: actually look at the code here and do nontrivial init
    ["  init { zero!<", StateStructName, ">() }\n\n"],
    ["  next(state: ", StateStructName, ") {\n",
    """
        let (tok1, frame) = recv(join(), req_in);
    """, "\n",
    ["    let state_record = (Tag::", string:uppercase(atom_to_list(StateName)),
     ", state);\n\n"],
    """
        // cognate to {reply, Reply, State}
        let (resp, new_state) = match frame.header.op as Tag {

    """],
    [
        ["\n", "Tag::", string:uppercase(Op), " => {\n",
        "let request = ", lists:delete($_, Op), "_from_bits(frame.payload);\n",
        Body,
        RetVal, "\n",
        "},\n"]
        ||  Clause <- handle_call(Forms),
            Op <- [atom_to_list(op_from_clause(Clause))],
            {Body, RetVal} <- [branch_from_clause(Clause, ["request", "state_record"], StateName,
                fun(R) -> ["(axis::pack(", R, ".1.0 as u8, ", R, ".1.2), ", R, ".2)"] end)]
    ],
    [
        ["\n", "Tag::", string:uppercase(TagName), " => {\n",
        "let request = ", StructFunctionName, "_from_bits(frame.payload);\n",
        Body,
        RetVal, "\n",
        "},\n"]
        ||  Clause <- handle_cast(Forms),
            TagName <- [atom_to_list(op_from_clause(Clause))],
            StructFunctionName <- [lists:delete($_, TagName)],
            {Body, RetVal} <- [branch_from_clause(
                Clause,
                ["request", "state_record"],
                StateName,
                fun(R) -> ["(zero!<axis::Frame>(), ", R, ".1)"] end)]
    ],
    """

        _ => {
          let s = zero!<State>();
          (axis::pack(Tag::ERROR as u8, ERROR_FUNCTION_CLAUSE),
           (Tag::STATE, s))
        }

        };

        let txid = frame.header.txid;
        let resp2 = axis::Frame { header: axis::Header { txid, ..resp.header }, ..resp };
        send_if(tok1, resp_out, resp2.header.op != (Tag::NONE as u8), resp2);
        new_state.1
      }
    }


    """,
    """
    proc Top {
      ext_recv:  chan<axis::Beat> in;
      ext_send:  chan<axis::Beat> out;
    """, "\n",
    ["  config(ext_recv: chan<axis::Beat> in, ext_send: chan<axis::Beat> out) {\n"],
    """
        let (req_p,  req_c ) = chan<axis::Frame, u32:1>("req");
        let (resp_p, resp_c) = chan<axis::Frame, u32:1>("resp");

        spawn axis::Rx(ext_recv, req_p);
        spawn Service(req_c, resp_p);
        spawn axis::Tx(resp_c, ext_send);

        (ext_recv, ext_send)
      }

      init { () }

      next(state: ()) { state }
    }

    """],

    print(Emitted).

to_xls_statem(Filename, Forms, StateNames) ->
    [MessageName] = find_attribute(Forms, xls_tags),
    Capacity = find_attribute(Forms, xls_mailbox_capacity),
    true = is_integer(Capacity) andalso Capacity > 0 andalso Capacity =< 255,
    StateName = state(Forms),
    MessageRecord = find_record(Forms, MessageName),
    StateRecord = find_record(Forms, StateName),
    ok = validate_record_defaults(MessageRecord),
    ok = validate_record_defaults(StateRecord),

    MessageStruct = record_struct_name(MessageName),
    StateStruct = record_struct_name(StateName),
    EnumAtoms = enum_atoms(StateNames),
    [InitClause] = find_function(Forms, init, 1),
    [TransitionClause] = find_function(Forms, transition, 2),
    InitPostprocessor = fun(R) -> [
        "Machine {\n",
        "  boot_pending: ", R, ".0.0,\n",
        "  boot: ", R, ".0.1.1,\n",
        "  phase: ", R, ".1.0,\n",
        "  data: ", R, ".1.1.1,\n",
        "  ..zero!<Machine>()\n",
        "}"
    ] end,
    {InitBody, InitResult} = branch_from_clause(
        InitClause,
        [],
        StateName,
        InitPostprocessor,
        "zero!<Machine>()",
        EnumAtoms
    ),
    TransitionPostprocessor = fun(R) -> [
        "(if ", R, ".0.0 {\n",
        "    axis::pack(Tag::", uppercase(MessageName), " as u8, ",
        R, ".0.1.2)\n",
        "  } else { zero!<axis::Frame>() },\n",
        "  ", R, ".1.0, ", R, ".1.1.1, ", R, ".2)"
    ] end,
    TransitionFailure = [
        "(zero!<axis::Frame>(), phase, data, Directive::FAIL)"
    ],
    {TransitionBody, TransitionResult} = branch_from_clause(
        TransitionClause,
        ["message", "(phase, (Tag::STATE, data))"],
        StateName,
        TransitionPostprocessor,
        TransitionFailure,
        EnumAtoms
    ),

    Indexes = lists:seq(0, Capacity - 1),
    EligibleBindings = [
        [
            "    let eligible_", integer_to_list(Index), " = u8:",
            integer_to_list(Index), " < admitted_occupied &&\n",
            "      (!admitted_slots[", integer_to_list(Index),
            "].postponed || admitted_slots[", integer_to_list(Index),
            "].blocked_phase != machine.phase);\n"
        ]
        || Index <- Indexes
    ],
    FoundExpression = join_with(" || ", [
        ["eligible_", integer_to_list(Index)] || Index <- Indexes
    ]),
    SelectedExpression = lists:foldr(
        fun(Index, Else) ->
            [
                "if eligible_", integer_to_list(Index), " { u8:",
                integer_to_list(Index), " } else { ", Else, " }"
            ]
        end,
        "u8:0",
        Indexes
    ),
    CompactionBindings = [
        compaction_binding(Index, Capacity) || Index <- Indexes
    ],
    CompactedArray = [
        "[",
        join_with(", ", [
            ["compacted_", integer_to_list(Index)] || Index <- Indexes
        ]),
        "]"
    ],
    UnblockedArray = [
        "[",
        join_with(",\n      ", [
            [
                "MailboxSlot { postponed: u1:0, ..candidate_slots[",
                integer_to_list(Index), "] }"
            ]
            || Index <- Indexes
        ]),
        "]"
    ],

    Emitted = [
        "// ", Filename, ".x\n",
        """
        // This file is auto-generated by xls_parse. Manual changes will be
        // overwritten the next time it is generated.

        import axis;

        const MAILBOX_CAPACITY = u8:
        """,
        integer_to_list(Capacity),
        ";\n\n",
        "pub enum Tag : u8 {\n",
        "  NONE = u8:0,\n",
        "  ERROR = u8:1,\n",
        "  STATE = u8:2,\n",
        "  ", uppercase(MessageName), " = u8:3,\n",
        "}\n\n",
        "enum Phase : u8 {\n",
        [
            [
                "  ", uppercase(Name), " = u8:", integer_to_list(Index),
                ",\n"
            ]
            || {Index, Name} <- lists:enumerate(0, StateNames)
        ],
        "}\n\n",
        "enum Directive : u2 {\n",
        "  CONSUME = u2:0,\n",
        "  POSTPONE = u2:1,\n",
        "  FAIL = u2:2,\n",
        "}\n\n",
        struct_from_record(MessageRecord), "\n",
        structfrombits_from_record(MessageRecord), "\n",
        bitsfromstruct_from_record(MessageRecord), "\n",
        struct_from_record(StateRecord), "\n",
        structfrombits_from_record(StateRecord), "\n",
        bitsfromstruct_from_record(StateRecord), "\n",
        "struct MailboxSlot {\n",
        "  postponed: u1,\n",
        "  blocked_phase: Phase,\n",
        "  message: ", MessageStruct, ",\n",
        "}\n\n",
        "struct Machine {\n",
        "  phase: Phase,\n",
        "  data: ", StateStruct, ",\n",
        "  slots: MailboxSlot[", integer_to_list(Capacity), "],\n",
        "  occupied: u8,\n",
        "  boot_pending: u1,\n",
        "  boot: ", MessageStruct, ",\n",
        "  // Reserves one queue slot for the frame being assembled.\n",
        "  admission_pending: u1,\n",
        "  dead: u1,\n",
        "}\n\n",
        "fn initial_machine() -> Machine {\n",
        InitBody,
        "  ", InitResult, "\n",
        "}\n\n",
        "fn dispatch(message: ", MessageStruct, ", phase: Phase, data: ",
        StateStruct, ") -> (axis::Frame, Phase, ", StateStruct,
        ", Directive) {\n",
        TransitionBody,
        "  ", TransitionResult, "\n",
        "}\n\n",
        "proc Service {\n",
        "  req_in: chan<axis::Frame> in;\n",
        "  resp_out: chan<axis::Frame> out;\n",
        "  admission_out: chan<u1> out;\n\n",
        "  config(req_in: chan<axis::Frame> in,\n",
        "         resp_out: chan<axis::Frame> out,\n",
        "         admission_out: chan<u1> out) {\n",
        "    (req_in, resp_out, admission_out)\n",
        "  }\n\n",
        "  init { initial_machine() }\n\n",
        "  next(machine: Machine) {\n",
        "    if machine.boot_pending {\n",
        "      let response = axis::pack(Tag::", uppercase(MessageName),
        " as u8, bits_from_", record_function_name(MessageName),
        "(machine.boot));\n",
        "      send(join(), resp_out, response);\n",
        "      Machine { boot_pending: u1:0, ..machine }\n",
        "    } else if machine.dead {\n",
        "      machine\n",
        "    } else {\n",
        "      let (tok, frame, received) = recv_if_non_blocking(\n",
        "        join(), req_in, machine.admission_pending,\n",
        "        zero!<axis::Frame>());\n",
        "      let tag_ok = frame.header.op == (Tag::",
        uppercase(MessageName), " as u8);\n",
        "      let accepted = received && tag_ok;\n",
        "      let invalid_input = received && !tag_ok;\n",
        "      let incoming = ", record_function_name(MessageName),
        "_from_bits(frame.payload);\n",
        "      let incoming_slot = MailboxSlot {\n",
        "        message: incoming,\n",
        "        ..zero!<MailboxSlot>()\n",
        "      };\n",
        "      let admitted_slots = if accepted {\n",
        "        update(machine.slots, machine.occupied as u32, incoming_slot)\n",
        "      } else { machine.slots };\n",
        "      let admitted_occupied = machine.occupied + (accepted as u8);\n",
        EligibleBindings,
        "    let found = ", FoundExpression, ";\n",
        "    let selected = ", SelectedExpression, ";\n",
        "    let message = admitted_slots[selected as u32].message;\n",
        "    let dispatchable = found && !invalid_input;\n",
        "    let (response, next_phase, next_data, directive) =\n",
        "      if dispatchable {\n",
        "        dispatch(message, machine.phase, machine.data)\n",
        "      } else {\n",
        "        (zero!<axis::Frame>(), machine.phase, machine.data,\n",
        "         Directive::CONSUME)\n",
        "      };\n",
        "    let emits = response.header.op != (Tag::NONE as u8);\n",
        "    let invalid_conclusion = dispatchable &&\n",
        "      directive != Directive::CONSUME && emits;\n",
        "    let effective = dispatchable && !invalid_conclusion;\n",
        "    let selected_slot = admitted_slots[selected as u32];\n",
        "    let postponed_slot = MailboxSlot {\n",
        "      postponed: u1:1,\n",
        "      blocked_phase: machine.phase,\n",
        "      ..selected_slot\n",
        "    };\n",
        "    let postponed_slots = update(\n",
        "      admitted_slots, selected as u32, postponed_slot);\n",
        CompactionBindings,
        "    let compacted_slots = ", CompactedArray, ";\n",
        "    let transition_slots = match directive {\n",
        "      Directive::CONSUME => compacted_slots,\n",
        "      Directive::POSTPONE => postponed_slots,\n",
        "      Directive::FAIL => admitted_slots,\n",
        "    };\n",
        "    let candidate_slots = if effective {\n",
        "      transition_slots\n",
        "    } else { admitted_slots };\n",
        "    let candidate_occupied = if effective &&\n",
        "        directive == Directive::CONSUME {\n",
        "      admitted_occupied - u8:1\n",
        "    } else { admitted_occupied };\n",
        "    let candidate_phase = if effective {\n",
        "      next_phase\n",
        "    } else { machine.phase };\n",
        "    let candidate_data = if effective {\n",
        "      next_data\n",
        "    } else { machine.data };\n",
        "    let phase_changed = candidate_phase != machine.phase;\n",
        "    let unblocked_slots = ", UnblockedArray, ";\n",
        "    let final_slots = if phase_changed {\n",
        "      unblocked_slots\n",
        "    } else { candidate_slots };\n",
        "    let should_send = effective &&\n",
        "      directive == Directive::CONSUME &&\n",
        "      emits;\n",
        "    let response_tok = send_if(\n",
        "      tok, resp_out, should_send, response);\n",
        "    let dead = invalid_input || invalid_conclusion ||\n",
        "      (effective && directive == Directive::FAIL);\n",
        "    let admission_pending = machine.admission_pending && !received;\n",
        "    // Preserve occupied + admission_pending <= MAILBOX_CAPACITY.\n",
        "    let reserve = !dead && !received && !admission_pending &&\n",
        "      candidate_occupied < MAILBOX_CAPACITY;\n",
        "    let _admission_tok = send_if(\n",
        "      response_tok, admission_out, reserve, u1:1);\n",
        "    Machine {\n",
        "      phase: candidate_phase,\n",
        "      data: candidate_data,\n",
        "      slots: final_slots,\n",
        "      occupied: candidate_occupied,\n",
        "      admission_pending: admission_pending || reserve,\n",
        "      dead,\n",
        "      ..machine\n",
        "    }\n",
        "    }\n",
        "  }\n",
        "}\n\n",
        "pub proc Top {\n",
        "  ext_recv: chan<axis::Beat> in;\n",
        "  ext_send: chan<axis::Beat> out;\n\n",
        "  config(ext_recv: chan<axis::Beat> in,\n",
        "         ext_send: chan<axis::Beat> out) {\n",
        "    let (req_p, req_c) = chan<axis::Frame, u32:1>(\"req\");\n",
        "    let (resp_p, resp_c) = chan<axis::Frame, u32:1>(\"resp\");\n",
        "    let (admit_p, admit_c) = chan<u1, u32:1>(\"admit\");\n",
        "    spawn axis::ReservedRx(ext_recv, req_p, admit_c);\n",
        "    spawn Service(req_c, resp_p, admit_p);\n",
        "    spawn axis::Tx(resp_c, ext_send);\n",
        "    (ext_recv, ext_send)\n",
        "  }\n\n",
        "  init { () }\n",
        "  next(state: ()) { state }\n",
        "}\n"
    ],
    print(Emitted).

enum_atoms(StateNames) ->
    PhaseAtoms = [
        {Name, ["Phase::", uppercase(Name)]} || Name <- StateNames
    ],
    DirectiveAtoms = [
        {consume, "Directive::CONSUME"},
        {postpone, "Directive::POSTPONE"},
        {fail, "Directive::FAIL"}
    ],
    maps:from_list(PhaseAtoms ++ DirectiveAtoms).

uppercase(Atom) ->
    string:uppercase(atom_to_list(Atom)).

record_struct_name(Atom) ->
    string:titlecase(record_function_name(Atom)).

record_function_name(Atom) ->
    lists:delete($_, atom_to_list(Atom)).

compaction_binding(Index, Capacity) when Index + 1 < Capacity ->
    [
        "    let compacted_", integer_to_list(Index), " = if u8:",
        integer_to_list(Index), " < selected {\n",
        "      admitted_slots[", integer_to_list(Index), "]\n",
        "    } else if u8:", integer_to_list(Index + 1),
        " < admitted_occupied {\n",
        "      admitted_slots[", integer_to_list(Index + 1), "]\n",
        "    } else { zero!<MailboxSlot>() };\n"
    ];
compaction_binding(Index, _Capacity) ->
    [
        "    let compacted_", integer_to_list(Index),
        " = zero!<MailboxSlot>();\n"
    ].

join_with(_Separator, []) ->
    [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].

%% We employ a limited IR with three kinds of objects:
%%  + static objects which admit expression in terms of the XLS runtime,
%%  + phantom objects which do not admit expression in terms of the XLS runtime,
%%  + snippets of XLS code.
%%
%% "Closed" IR generally only contains static objects and snippets; phantoms
%% appear temporarily during code generation, e.g., when "passing" the "result"
%% of an Erlang type constructor to XLS's `zero!`.
-type static() :: {static, integer, integer()}.
-type phantom() :: {phantom, type, xls_type:descriptor()}.
-type printable() :: [printable()] | string() | static().
-type ir() :: [ir()] | string() | phantom() | static().

-spec print(printable()) -> iolist().
print(List) when is_list(List) ->
    lists:map(fun print/1, List);
print(Char) when is_integer(Char) ->
    Char;
print({static, integer, Integer}) ->
    integer_to_list(Integer).
%% NOTE: We deliberately fail through on (unprintable!) phantom objects.

-doc """
 
""".
-record(clause_state, {
    anonymous_counter = 0 :: integer(),
    match_counter = 0 :: integer(),
    named_counters = #{} :: #{atom() => integer()},
    statements = [] :: printable(),
    reference = none :: none | ir(),
    state_name = undefined :: undefined | atom(),
    enum_atoms = #{} :: #{atom() => printable()}
}).
-type clause_state() :: #clause_state{}.

-spec branch_from_clause(
    erl_parse:af_clause(),
    [atom()],
    atom(),
    fun((printable()) -> printable())
) -> {printable(), string()}.
-doc "Processes an Erlang clause from handle_*/2 into XLS.".
branch_from_clause(Clause, ArgVals, StateName, Postprocessor) ->
    Failure = [
        "let s = zero!<State>();\n",
        "    (axis::pack(Tag::ERROR as u8, ERROR_MATCH_FAILURE), ",
        "(Tag::STATE, s))"
    ],
    branch_from_clause(
        Clause,
        ArgVals,
        StateName,
        Postprocessor,
        Failure,
        #{}
    ).

branch_from_clause(
    Clause,
    ArgVals,
    StateName,
    Postprocessor,
    Failure,
    EnumAtoms
) ->
    {clause, _1, ArgPatterns, _2, Body} = Clause,
    InjectMatch = fun
        F({{match, LineNo, LHS, RHS}, Arg}) ->
            {match, LineNo, LHS, F({RHS, Arg})};
        F({X, Arg}) ->
            {match, element(2, X), X, Arg}
    end,
    BigBody = case ArgPatterns of
        [{nil, _L}] -> Body;
        _ -> lists:map(InjectMatch, lists:zip(ArgPatterns, ArgVals)) ++ Body
    end,
    ComputeState = lists:foldl(
        fun(Statement, State) ->
            statement_from_statement(Statement, State#clause_state{reference = none})
        end,
        #clause_state{state_name = StateName, enum_atoms = EnumAtoms}, BigBody
    ),

    OutState = instr(ComputeState, [
        "if (", [
            ["(", Name, "_1 != ", Name, "_", integer_to_list(VV), ") || "]
            ||  K := V <- ComputeState#clause_state.named_counters,
                V > 1,
                VV <- lists:seq(2, V),
                Name <- [if is_atom(K) -> atom_to_list(K) ; true -> K end]
        ], "bool:false) {\n",
        "    ", Failure, "\n",
        "} else {\n",
            %% TODO: it would be preferable to branch on the REPLY/NOREPLY tag,
            %% but we have to wait for the XLS type system to allow tagged sums,
            %% so that {reply, Reply, State} unifies with {noreply, State}.
        "    ", Postprocessor(reference(ComputeState)), "\n",
        "}"
    ]),

    {lists:reverse(OutState#clause_state.statements), OutState#clause_state.reference}.

-spec statement_from_statement(erl_parse:abstract_expression(), clause_state()) -> clause_state().
-doc """
Main transpiler workhorse.  Recursively converts a complex `erl_parse`
expression into a sequence of simple emitted XLS expressions.
""".
statement_from_statement(String, State) when is_list(String) ->
    reference(State, String);
statement_from_statement({atom, _L, true}, State) ->
    reference(State, "bool:1");
statement_from_statement({atom, _L, false}, State) ->
    reference(State, "bool:0");
statement_from_statement({atom, _L, Atom}, State = #clause_state{
    enum_atoms = EnumAtoms
}) ->
    reference(
        State,
        maps:get(Atom, EnumAtoms, string:uppercase(atom_to_list(Atom)))
    );
statement_from_statement({var, _L, Atom}, State) ->
    reference(State, get_name(State, Atom));
statement_from_statement({integer, _L, Integer}, State) ->
    reference(State, {static, integer, Integer});
statement_from_statement(X, State) when is_tuple(X) andalso op == element(1, X) ->
    [op, _L, Op | Args] = tuple_to_list(X),
    {BwdArgRefs, IntermediateState} = lists:foldl(
        fun(Arg, {ArgRefs, ThisState}) ->
            NewState = statement_from_statement(Arg, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | ArgRefs], NewState}
        end,
        {[], State}, Args
    ),
    instr(IntermediateState, op(Op, lists:reverse(BwdArgRefs)));
statement_from_statement({tuple, _L, Slots}, State) ->
    {BwdReferences, IntermediateState} = lists:foldl(
        fun(Slot, {References, ThisState}) ->
            NewState = statement_from_statement(Slot, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | References], NewState}
        end,
        {[], State}, Slots
    ),
    instr(IntermediateState, ["(", [[Ref, ", "] || Ref <- lists:reverse(BwdReferences)], ")"]);
statement_from_statement({record, _L, NameAtom, Fields}, State) ->
    {Assignments, IntermediateState} = lists:foldl(
        fun({record_field, _1, {atom, _2, FieldAtom}, RHS}, {Assignments, ThisState}) ->
            NewState = statement_from_statement(RHS, ThisState#clause_state{reference = none}),
            {Assignments#{FieldAtom => NewState#clause_state.reference}, NewState}
        end,
        {#{}, State}, Fields
    ),
    SecondState = instr(IntermediateState, [
        string:titlecase(lists:delete($_, atom_to_list(NameAtom))), " {\n",
        [["  ", atom_to_list(FieldAtom), ": ", Reference, ",\n"]
            || FieldAtom := Reference <- Assignments],
        "  ..zero!<", string:titlecase(lists:delete($_, atom_to_list(NameAtom))), ">()\n",
        "}"
    ]),
    instr(SecondState, record_value(NameAtom, reference(SecondState), SecondState));
statement_from_statement({record, _L, ToUpdate, NameAtom, UpdateFields}, State) ->
    InputState = statement_from_statement(ToUpdate, State),
    {Assignments, IntermediateState} = lists:foldl(
        fun({record_field, _1, {atom, _2, FieldAtom}, RHS}, {Assignments, ThisState}) ->
            NewState = statement_from_statement(RHS, ThisState#clause_state{reference = none}),
            {Assignments#{FieldAtom => NewState#clause_state.reference}, NewState}
        end,
        {#{}, InputState}, UpdateFields
    ),
    SecondState = instr(IntermediateState, [
        string:titlecase(lists:delete($_, atom_to_list(NameAtom))), " {\n",
            [["  ", atom_to_list(FieldAtom), ": ", Reference, ",\n"] || FieldAtom := Reference <- Assignments],
        "  ..(", InputState#clause_state.reference, ").1\n",
        "}"
    ]),
    instr(SecondState, record_value(NameAtom, reference(SecondState), SecondState));
statement_from_statement({call, _L, MF, Args}, State) ->
    {remote, _1, {atom, _2, Module}, {atom, _3, FAtom}} = MF,

    {BwdArgRefs, ArgState} = lists:foldl(
        fun(Arg, {ArgRefs, ThisState}) ->
            NewState = statement_from_statement(Arg, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | ArgRefs], NewState}
        end,
        {[], State}, Args
    ),
    case Module:transpile(FAtom, lists:reverse(BwdArgRefs), ArgState) of
        X = #clause_state{} -> X;
        X -> instr(ArgState, X)
    end;
statement_from_statement({record_field, _L, Object, _RecordAtom, {atom, _LL, SlotAtom}}, State) ->
    IntermediateState = statement_from_statement(Object, State),
    instr(IntermediateState, [reference(IntermediateState), ".1.", atom_to_list(SlotAtom)]);
statement_from_statement({match, _L, LHS, RHS}, State) ->
    RHSState = statement_from_statement(RHS, State),
    destructure_lhs(LHS, RHSState).

-spec record_value(atom(), ir(), clause_state()) -> iolist().
record_value(NameAtom, Struct, #clause_state{state_name = NameAtom}) ->
    ["(Tag::", string:uppercase(atom_to_list(NameAtom)), ", ", Struct, ")"];
record_value(NameAtom, Struct, _State) ->
    [
        "(Tag::", string:uppercase(atom_to_list(NameAtom)), ", ", Struct, ", ",
        "bits_from_", lists:delete($_, atom_to_list(NameAtom)), "(", Struct, "))"
    ].

-spec destructure_lhs(erl_parse:af_pattern(), clause_state()) -> clause_state().
-doc """
Converts an assignment from an opaque RHS to a structured LHS into a sequence of
accessors into the RHS being assigned to slots inside of the LHS.
""".
destructure_lhs({var, _L, NameAtom}, State) ->
    %% TODO: need to record time-order data to report correct error
    %% TODO: also want to report eg line number on error, other present state
    {Name, NewState} = uniquify(State, NameAtom),

    %% TODO: make this more gensym-y, rather than just reserving a name class
    case Name of
        "static_match" ++ _Rest ->
            error(illegal);
        _ -> ok
    end,

    RHS = NewState#clause_state.reference,
    Bind = ["let ", Name, " = ", RHS, ";\n"],
    NewState#clause_state{statements = [Bind | NewState#clause_state.statements]};
destructure_lhs({record, _L, _Atom, Slots}, State) ->
    RecordRef = State#clause_state.reference,
    IntermediateState = lists:foldl(
        fun({record_field, _1, {atom, _2, SlotAtom}, LHS}, ThisState) ->
            Slot = atom_to_list(SlotAtom),
            Substate = ThisState#clause_state{reference = [RecordRef, ".", Slot]},
            destructure_lhs(LHS, Substate)
        end,
        State, Slots
    ),
    IntermediateState#clause_state{reference = RecordRef};
destructure_lhs({tuple, _L, Slots}, State) ->
    TupleRef = State#clause_state.reference,
    IntermediateState = lists:foldl(
        fun({Index, LHS}, ThisState) ->
            Substate = ThisState#clause_state{
                reference = [TupleRef, ".", integer_to_list(Index)]
            },
            destructure_lhs(LHS, Substate)
        end,
        State,
        lists:enumerate(0, Slots)
    ),
    IntermediateState#clause_state{reference = TupleRef};
%% constant cases
destructure_lhs({atom, _L, Atom}, State) when Atom == true orelse Atom == false ->
    EncodedValue = case Atom of
        true -> "bool:1";
        false -> "bool:0"
    end,
    #clause_state{match_counter = OldMatchCounter} = State,
    MatchCounter = OldMatchCounter + 1,
    CounterState = State#clause_state{match_counter = MatchCounter},

    BaseName = "static_match_" ++ integer_to_list(MatchCounter),
    {StaticName, StaticState} = uniquify(CounterState, BaseName),
    {RHSName, RHSState} = uniquify(StaticState, BaseName),

    RHSValue = RHSState#clause_state.reference,

    RHSState#clause_state{
        reference = RHSName,
        statements = [
            ["let ", RHSName, " = ", RHSValue, " ;\n"],
            ["let ", StaticName, " = ", EncodedValue, " ;\n"]
            | CounterState#clause_state.statements
    ]}.
%% TODO: tuple
%% TODO: badmatch on constant

%%%
%%% Erlang record / XLS struct munging.
%%%
%%% XLS does not support `(struct) as bits` and `(bits) as struct` conversions,
%%% so we have to emit manual un/packers.
%%%

-spec struct_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Translates an Erlang record definition to an XLS struct definition.".
struct_from_record(RecordForm) ->
    {attribute, _L, record, {NameAtom, Fields}} = RecordForm,
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["struct ", StructName, " {\n",
        [io_lib:format("  ~w : ~s,~n", [
                element(3, element(3, Field)),
                xls_type:print_type(xls_type:descriptor(Type))
            ])
            ||  {typed_record_field, Field, Type} <- Fields
        ],
    "}\n"].

-spec structfrombits_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Builds an XLS-side unpacker for the Erlang record definition.".
structfrombits_from_record(RecordForm) ->
    {attribute, _L, record, {NameAtom, Fields}} = RecordForm,
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["fn ", string:lowercase(StructName), "_from_bits<N: u32>(raw: bits[N]) -> ", StructName, " {\n",
    "  ", StructName, " {\n",
    lists:reverse(element(1, lists:foldl(
        fun(
            {typed_record_field, Field, Type},
            {Body, Offset}
        ) ->
            Slot = record_field_name(Field),
            Descriptor = xls_type:descriptor(Type),
            NextOffset = Offset + xls_type:width(Descriptor),
            Line = io_lib:format(
                "    ~w: raw[~w:~w] as ~s,~n",
                [
                    Slot,
                    Offset,
                    NextOffset,
                    xls_type:print_type(Descriptor)
                ]
            ),
            {[Line | Body], NextOffset}
        end,
        {[], 0}, Fields
    ))),
    "  }\n",
    "}\n"].

-spec bitsfromstruct_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Builds an XLS-side packer for the Erlang record definition.".
bitsfromstruct_from_record(_RecordForm = {attribute, _L, record, {NameAtom, Fields}}) ->
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["fn bits_from_", string:lowercase(StructName), "(s: ", StructName, ") -> bits[bit_count<", StructName, ">()] {\n",
        ["  ", lists:foldl(
            fun({typed_record_field, Field, Type}, Body) ->
                Slot = record_field_name(Field),
                Line = io_lib:format("(s.~w as bits[~w]) ++ ", [Slot, xls_type:width(xls_type:descriptor(Type))]),
                [Line | Body]  % implicit lists:reverse with this join order
            end,
            [" zero!<bits[0]>()\n"], Fields
        )],
    "}\n"].

-spec record_width(erl_parse:af_record_decl()) -> non_neg_integer().
-doc "Calculates the packed width of an Erlang record's XLS struct.".
record_width({attribute, _L, record, {_NameAtom, Fields}}) ->
    lists:sum([
        xls_type:width(xls_type:descriptor(Type))
        || {typed_record_field, _Field, Type} <- Fields
    ]).

-spec record_field_name(erl_parse:af_record_field()) -> atom().
-doc "Extracts a field name from record declarations with or without a default.".
record_field_name({record_field, _L, {atom, _AtomL, Name}}) ->
    Name;
record_field_name({record_field, _L, {atom, _AtomL, Name}, _Default}) ->
    Name.

-spec validate_record_defaults(erl_parse:af_record_decl()) -> ok.
-doc """
Requires every field in a translated record to use the type-directed
`xls_type:zero()` marker, keeping Erlang defaults consistent with XLS `zero!`.
""".
validate_record_defaults({attribute, _L, record, {RecordName, Fields}}) ->
    lists:foreach(
        fun({
            typed_record_field,
            {record_field, Line, {atom, _AtomLine, FieldName}, Default},
            _Type
        }) ->
            case is_zero_default(Default) of
                true -> ok;
                false ->
                    error({invalid_xls_record_default, RecordName, FieldName, Line})
            end;
           ({
            typed_record_field,
            {record_field, Line, {atom, _AtomLine, FieldName}},
            _Type
        }) ->
            error({missing_xls_record_default, RecordName, FieldName, Line});
           (Field) ->
            error({untyped_xls_record_field, RecordName, Field})
        end,
        Fields
    ),
    ok.

-spec is_zero_default(erl_parse:abstract_expr()) -> boolean().
-doc "Recognizes the type-directed zero marker in a record declaration.".
is_zero_default({
    call,
    _Line,
    {remote, _RemoteLine, {atom, _ModuleLine, xls_type}, {atom, _NameLine, zero}},
    []
}) ->
    true;
is_zero_default(_Default) ->
    false.

%%%
%%% clause_state utilities
%%%

-spec anonymous_variable(clause_state()) -> {clause_state(), VarName :: string()}.
anonymous_variable(State = #clause_state{anonymous_counter = Counter}) ->
    {State#clause_state{anonymous_counter = Counter + 1}, [$_ | integer_to_list(Counter)]}.

-spec get_name(clause_state(), atom()) -> string().
-doc "Maps Erlang variable names onto emitted XLS names.".
get_name(_State, Name) ->
    %% XLS wants names to be lower case, and we affix the _1 to avoid collisions
    %% with names hard-coded into the template (e.g., state, request).
    string:lowercase(atom_to_list(Name)) ++ "_1".

%% TODO: explain why this is needed
-spec uniquify(clause_state(), atom() | string()) -> string().
-doc "Rewrites NameAtom in a way that guarantees no collision with previous uses.".
uniquify(State, NameAtom) when is_atom(NameAtom) ->
    Name = string:lowercase(atom_to_list(NameAtom)),
    uniquify(State, Name);
uniquify(State = #clause_state{named_counters = Counters}, Name) ->
    Counter = maps:get(Name, Counters, 0) + 1,
    NamedCounters = Counters#{Name => Counter},
    NewName = Name ++ [$_ | integer_to_list(Counter)],
    {NewName, State#clause_state{named_counters = NamedCounters}}.

-spec reference(clause_state()) -> none | ir().
reference(ClauseState) ->
    ClauseState#clause_state.reference.

-spec reference(clause_state(), ir()) -> clause_state().
reference(ClauseState, Reference) ->
    ClauseState#clause_state{reference = Reference}.

-spec instr(clause_state(), ir()) -> clause_state().
instr(#clause_state{anonymous_counter = Counter} = ClauseState, Expr) ->
    instr(
        ClauseState#clause_state{anonymous_counter = Counter + 1},
        [$_ | integer_to_list(Counter)],
        Expr
    ).

-spec instr(clause_state(), ir(), ir()) -> clause_state().
instr(ClauseState, Place, Expr) ->
    % TODO: we should admit structured `Place`s in reference and print them in statements
    ClauseState#clause_state{
        reference = Place,
        statements = [["let ", Place, " = ", Expr, ";\n"] | ClauseState#clause_state.statements]
    }.

%%%
%%% Dictionaries for built-in calls
%%%

-spec op(Op :: atom(), Args :: [any()]) -> iolist().
-doc "Translates a built-in Erlang op to an XLS op.".
op('+', [Left, Right]) -> [Left, " + ", Right];
op('bsl', [Left, Right]) -> [Left, " << ", Right];
op('bsr', [Left, Right]) -> [Left, " >> ", Right];
op('band', [Left, Right]) -> [Left, " & ", Right];
op('bor', [Left, Right]) -> [Left, " | ", Right];
op('bnot', [Operand]) -> ["!", Operand];
op('<', [Left, Right]) -> [Left, " < ", Right];
op('=:=', [Left, Right]) -> [Left, " == ", Right];
op('andalso', [Left, Right]) -> [Left, " && ", Right];
op('orelse', [Left, Right]) -> [Left, " || ", Right].

%%%
%%% Search / selection tools
%%%

%% TODO: be more consistent about whether you return un/packed abstract forms

-spec op_from_clause(erl_parse:af_clause()) -> atom().
-doc "Extracts the record type name being matched against in this Clause.".
op_from_clause(Clause) ->
    {clause, _1, [{record, _2, Atom, _Contents} | _Rest], _3, _Body} = Clause,
    Atom.

-spec handle_cast([erl_parse:abstract_form()]) -> erl_parse:af_clause_seq().
-doc "Picks out the handle_cast/2 function from the set of Forms.".
handle_cast(Forms) ->
    find_function(Forms, handle_cast, 2).

-spec handle_call([erl_parse:abstract_form()]) -> erl_parse:af_clause_seq().
-doc "Picks out the handle_call/2 function from the set of Forms.".
handle_call(Forms) ->
    find_function(Forms, handle_call, 2).

-spec init([erl_parse:abstract_form()]) -> erl_parse:af_clause().
-doc "Picks out the init/1 function from the set of Forms.".
init(Forms) ->
    [Value] = find_function(Forms, init, 1),
    [Value].

-spec state([erl_parse:abstract_form()]) -> atom().
-doc "Finds the record name which carries process state.".
state(Forms) ->
    case find_optional_attribute(Forms, xls_state) of
        {ok, StateAtom} ->
            StateAtom;
        none ->
            InitSpec = find_spec(Forms, init, 1),
            {attribute, _1, spec, {
                {init, 1},
                [{type, _2, 'fun', [
                    _3,
                    {type, _4, record, [{atom, _5, StateAtom}]}
                ]}]
            }} = InitSpec,
            StateAtom
    end.

-spec find_record([erl_parse:abstract_form()], atom()) -> erl_parse:af_record_decl().
-doc "Find the record definition with the indicated name from the set of Forms.".
find_record(Forms, Name) ->
    {value, Record} = lists:search(
        fun ({attribute, _L, record, {NameAtom, _Fields}}) -> NameAtom == Name;
            (_) -> false
        end, Forms
    ),
    Record.

-spec find_function([erl_parse:abstract_form()], atom(), integer()) -> erl_parse:af_clause_seq().
-doc "Find the function definition with the indicated F/A from the set of Forms.".
find_function(Forms, F, A) ->
    {value, {function, _LineNo, F, A, Clauses}} = lists:search(
        fun ({function, _LineNo, FF, AA, _Clauses}) ->
                F == FF andalso A == AA;
            (_) -> false
        end,
        Forms
    ),
    Clauses.

-spec find_attribute([erl_parse:abstract_form()], atom()) -> erl_parse:af_wild_attribute().
-doc "Finds the attribute with the indicated name from the set of Forms.".
find_attribute(Forms, Atom) ->
    {value, {attribute, _L, _A, Value}} = lists:search(
        fun ({attribute, _L, A, _Value}) -> A == Atom;
            (_) -> false
        end,
        Forms
    ),
    Value.

-spec find_optional_attribute([erl_parse:abstract_form()], atom()) ->
    none | {ok, term()}.
find_optional_attribute(Forms, Atom) ->
    case lists:search(
        fun
            ({attribute, _Line, Name, _Value}) -> Name =:= Atom;
            (_Form) -> false
        end,
        Forms
    ) of
        {value, {attribute, _Line, Atom, Value}} -> {ok, Value};
        false -> none
    end.

-spec find_spec([erl_parse:abstract_form()], atom(), integer()) -> erl_parse:af_function_spec().
-doc "Finds the function type declaration with the given F/A from the set of Forms.".
find_spec(Forms, F, A) ->
    {value, Spec} = lists:search(
        fun ({attribute, _LineNo, spec, {{FF, AA}, _Data}}) ->
                F == FF andalso A == AA;
            (_) -> false
        end,
        Forms
    ),
    Spec.

%%%
%%% Other utilities
%%%

-spec parse_file(string()) -> [erl_parse:abstract_form()].
-doc "Helper routine for reading an entire .erl source file into memory.".
parse_file(Filename) ->
    {ok, Epp} = epp:open([{name, Filename}]),
    try
        {ok, epp:parse_file(Epp)}
    after
        epp:close(Epp),
        err
    end.
