%%%% xls_parse
%%%%
%%%% TODO:
%%%%    + erl_syntax might be a little more ergonomic, have a look

-module(xls_parse).
-moduledoc """
Transforms supported Erlang actor modules into corresponding XLS modules.
""".
-export([to_xls/1]).
%% Internal API shared by the actor-specific lowerers while this module is
%% split into smaller compiler passes.
-export([
    bitsfromstruct_from_record/1,
    branch_from_clause/4,
    branch_from_clause/6,
    find_attribute/2,
    find_function/3,
    find_record/2,
    mismatch_expression/2,
    print/1,
    record_width/1,
    statement_from_statement/2,
    struct_from_record/1,
    structfrombits_from_record/1,
    uniquify/2,
    validate_record_defaults/1
]).
-export([
    reference/2,
    reference/1,
    instr/2,
    instr/3,
    anonymous_variable/1
]).
-export_type([ir/0, printable/0, static/0, phantom/0]).
-export_type([clause_state/0]).
-compile([export_all, nowarn_export_all]).  % TODO: remove export_all

-include("xls_parse.hrl").

-define(debug(X), begin io:format("~w@~w: ~p~n", [?FUNCTION_NAME, ?LINE, X]), X end).

-spec to_xls(string()) -> iolist().
-doc "Transpiles a supported Erlang actor module to a corresponding XLS module.".
to_xls(Filename) ->
    {ok, Forms} = parse_file(Filename),
    case find_optional_attribute(Forms, xls_phases) of
        none -> to_xls_gs(Filename, Forms);
        {ok, PhaseNames} -> to_xls_statem(Filename, Forms, PhaseNames)
    end.

to_xls_gs(Filename, Forms) ->
    PublicStructNames = find_attribute(Forms, xls_tags),
    StateName = state(Forms),
    StateRecord = find_record(Forms, StateName),
    StateStructName = string:titlecase(lists:delete($_, atom_to_list(StateName))),
    ok = lists:foreach(
        fun(Name) ->
            validate_record_defaults(find_record(Forms, Name))
        end,
        [StateName | PublicStructNames]
    ),

    Emitted = ["// ", Filename, ".x\n",
    """
    // This file is auto-generated by xls_parse. Manual changes will be over-
    // written the next time it is generated. Better to modify the Erlang input.

    import axis;

    const NOREPLY = u1:0;  // some standard erlang tokens
    const REPLY = u1:1;
    const OK = u1:0;
    const ERROR_FUNCTION_CLAUSE = u32:1;
    const ERROR_MATCH_FAILURE = u32:2;


    """,
    "const MAX_PAYLOAD = u32:3;\n\n",  % TODO: don't bake this in.
    "pub enum Tag : u8 {\n",
    "  NONE = u8:0,\n",
    [
        ["  ", string:uppercase(atom_to_list(Atom)), " = u8:", integer_to_list(Index), ",\n"]
        ||  {Index, Atom} <- lists:enumerate([error, StateName | PublicStructNames])
    ],
    "}\n\n",
    [
        [struct_from_record(Record), "\n",
         structfrombits_from_record(Record), "\n",
         bitsfromstruct_from_record(Record), "\n"]
        ||  Op <- PublicStructNames,
            Record <- [find_record(Forms, Op)]
    ],
    struct_from_record(StateRecord), "\n",
    structfrombits_from_record(StateRecord), "\n",
    bitsfromstruct_from_record(StateRecord), "\n",
    """
    proc Service {
      req_in:   chan<axis::Frame> in;
      resp_out: chan<axis::Frame> out;
    """, "\n",
    ["  config(req_in: chan<axis::Frame> in, resp_out: chan<axis::Frame> out) {\n",
     "    (req_in, resp_out)\n",
     "  }\n\n"],
    % TODO: actually look at the code here and do nontrivial init
    ["  init { zero!<", StateStructName, ">() }\n\n"],
    ["  next(state: ", StateStructName, ") {\n",
    """
        let (tok1, frame) = recv(join(), req_in);
    """, "\n",
    ["    let state_record = (Tag::", string:uppercase(atom_to_list(StateName)),
     ", state);\n\n"],
    """
        // cognate to {reply, Reply, State}
        let (resp, new_state) = match frame.header.op as Tag {

    """],
    xls_gs_lower:callback_arms(Forms, StateName),
    """

        _ => {
          let s = zero!<State>();
          (axis::pack(Tag::ERROR as u8, ERROR_FUNCTION_CLAUSE),
           (Tag::STATE, s))
        }

        };

        let txid = frame.header.txid;
        let resp2 = axis::Frame { header: axis::Header { txid, ..resp.header }, ..resp };
        send_if(tok1, resp_out, resp2.header.op != (Tag::NONE as u8), resp2);
        new_state.1
      }
    }


    """,
    """
    proc Top {
      ext_recv:  chan<axis::Beat> in;
      ext_send:  chan<axis::Beat> out;
    """, "\n",
    ["  config(ext_recv: chan<axis::Beat> in, ext_send: chan<axis::Beat> out) {\n"],
    """
        let (req_p,  req_c ) = chan<axis::Frame, u32:1>("req");
        let (resp_p, resp_c) = chan<axis::Frame, u32:1>("resp");

        spawn axis::Rx(ext_recv, req_p);
        spawn Service(req_c, resp_p);
        spawn axis::Tx(resp_c, ext_send);

        (ext_recv, ext_send)
      }

      init { () }

      next(state: ()) { state }
    }

    """],

    print(Emitted).

to_xls_statem(Filename, Forms, PhaseNames) ->
    xls_statem_lower:lower(Filename, Forms, PhaseNames).

%% We employ a limited IR with three kinds of objects:
%%  + static objects which admit expression in terms of the XLS runtime,
%%  + phantom objects which do not admit expression in terms of the XLS runtime,
%%  + snippets of XLS code.
%%
%% "Closed" IR generally only contains static objects and snippets; phantoms
%% appear temporarily during code generation, e.g., when "passing" the "result"
%% of an Erlang type constructor to XLS's `zero!`.
-type static() :: {static, integer, integer()}.
-type phantom() :: {phantom, type, xls_type:descriptor()}.
-type printable() :: [printable()] | string() | static().
-type ir() :: [ir()] | string() | phantom() | static().

-spec print(printable()) -> iolist().
print(List) when is_list(List) ->
    lists:map(fun print/1, List);
print(Char) when is_integer(Char) ->
    Char;
print({static, integer, Integer}) ->
    integer_to_list(Integer).
%% NOTE: We deliberately fail through on (unprintable!) phantom objects.

-doc """
 
""".
-type clause_state() :: #clause_state{}.

-spec branch_from_clause(
    erl_parse:af_clause(),
    [atom()],
    atom(),
    fun((printable()) -> printable())
) -> {printable(), string()}.
-doc "Processes an Erlang clause from handle_*/2 into XLS.".
branch_from_clause(Clause, ArgVals, StateName, Postprocessor) ->
    Failure = [
        "let s = zero!<State>();\n",
        "    (axis::pack(Tag::ERROR as u8, ERROR_MATCH_FAILURE), ",
        "(Tag::STATE, s))"
    ],
    branch_from_clause(
        Clause,
        ArgVals,
        StateName,
        Postprocessor,
        Failure,
        #{}
    ).

branch_from_clause(
    Clause,
    ArgVals,
    StateName,
    Postprocessor,
    Failure,
    EnumAtoms
) ->
    {clause, _1, ArgPatterns, _2, Body} = Clause,
    InjectMatch = fun
        F({{match, LineNo, LHS, RHS}, Arg}) ->
            {match, LineNo, LHS, F({RHS, Arg})};
        F({X, Arg}) ->
            {match, element(2, X), X, Arg}
    end,
    BigBody = case ArgPatterns of
        [{nil, _L}] -> Body;
        _ -> lists:map(InjectMatch, lists:zip(ArgPatterns, ArgVals)) ++ Body
    end,
    ComputeState = lists:foldl(
        fun(Statement, State) ->
            statement_from_statement(Statement, State#clause_state{reference = none})
        end,
        #clause_state{state_name = StateName, enum_atoms = EnumAtoms}, BigBody
    ),

    OutState = instr(ComputeState, [
        "if (", mismatch_expression(
            ComputeState#clause_state.named_counters,
            #{}
        ), ") {\n",
        "    ", Failure, "\n",
        "} else {\n",
            %% TODO: it would be preferable to branch on the REPLY/NOREPLY tag,
            %% but we have to wait for the XLS type system to allow tagged sums,
            %% so that {reply, Reply, State} unifies with {noreply, State}.
        "    ", Postprocessor(reference(ComputeState)), "\n",
        "}"
    ]),

    {lists:reverse(OutState#clause_state.statements), OutState#clause_state.reference}.

-spec statement_from_statement(erl_parse:abstract_expression(), clause_state()) -> clause_state().
-doc """
Main transpiler workhorse.  Recursively converts a complex `erl_parse`
expression into a sequence of simple emitted XLS expressions.
""".
statement_from_statement(String, State) when is_list(String) ->
    reference(State, String);
statement_from_statement({atom, _L, true}, State) ->
    reference(State, "bool:1");
statement_from_statement({atom, _L, false}, State) ->
    reference(State, "bool:0");
statement_from_statement({atom, _L, Atom}, State = #clause_state{
    enum_atoms = EnumAtoms
}) ->
    reference(
        State,
        maps:get(Atom, EnumAtoms, string:uppercase(atom_to_list(Atom)))
    );
statement_from_statement({var, _L, Atom}, State) ->
    reference(State, get_name(State, Atom));
statement_from_statement({integer, _L, Integer}, State) ->
    reference(State, {static, integer, Integer});
statement_from_statement(X, State) when is_tuple(X) andalso op == element(1, X) ->
    [op, _L, Op | Args] = tuple_to_list(X),
    {BwdArgRefs, IntermediateState} = lists:foldl(
        fun(Arg, {ArgRefs, ThisState}) ->
            NewState = statement_from_statement(Arg, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | ArgRefs], NewState}
        end,
        {[], State}, Args
    ),
    instr(IntermediateState, op(Op, lists:reverse(BwdArgRefs)));
statement_from_statement({tuple, _L, Slots}, State) ->
    {BwdReferences, IntermediateState} = lists:foldl(
        fun(Slot, {References, ThisState}) ->
            NewState = statement_from_statement(Slot, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | References], NewState}
        end,
        {[], State}, Slots
    ),
    instr(IntermediateState, ["(", [[Ref, ", "] || Ref <- lists:reverse(BwdReferences)], ")"]);
statement_from_statement({record, _L, NameAtom, Fields}, State) ->
    {BwdAssignments, IntermediateState} = lists:foldl(
        fun({record_field, _1, {atom, _2, FieldAtom}, RHS}, {Assignments, ThisState}) ->
            NewState = statement_from_statement(RHS, ThisState#clause_state{reference = none}),
            {[{FieldAtom, NewState#clause_state.reference} | Assignments], NewState}
        end,
        {[], State}, Fields
    ),
    Assignments = lists:reverse(BwdAssignments),
    SecondState = instr(IntermediateState, [
        string:titlecase(lists:delete($_, atom_to_list(NameAtom))), " {\n",
        [["  ", atom_to_list(FieldAtom), ": ", Reference, ",\n"]
            || {FieldAtom, Reference} <- Assignments],
        "  ..zero!<", string:titlecase(lists:delete($_, atom_to_list(NameAtom))), ">()\n",
        "}"
    ]),
    instr(SecondState, record_value(NameAtom, reference(SecondState), SecondState));
statement_from_statement({record, _L, ToUpdate, NameAtom, UpdateFields}, State) ->
    InputState = statement_from_statement(ToUpdate, State),
    {BwdAssignments, IntermediateState} = lists:foldl(
        fun({record_field, _1, {atom, _2, FieldAtom}, RHS}, {Assignments, ThisState}) ->
            NewState = statement_from_statement(RHS, ThisState#clause_state{reference = none}),
            {[{FieldAtom, NewState#clause_state.reference} | Assignments], NewState}
        end,
        {[], InputState}, UpdateFields
    ),
    Assignments = lists:reverse(BwdAssignments),
    SecondState = instr(IntermediateState, [
        string:titlecase(lists:delete($_, atom_to_list(NameAtom))), " {\n",
            [["  ", atom_to_list(FieldAtom), ": ", Reference, ",\n"]
                || {FieldAtom, Reference} <- Assignments],
        "  ..(", InputState#clause_state.reference, ").1\n",
        "}"
    ]),
    instr(SecondState, record_value(NameAtom, reference(SecondState), SecondState));
statement_from_statement({'case', _L, Condition, Clauses}, State) ->
    lower_boolean_case(Condition, Clauses, State);
statement_from_statement({call, _L, MF, Args}, State) ->
    {remote, _1, {atom, _2, Module}, {atom, _3, FAtom}} = MF,

    {BwdArgRefs, ArgState} = lists:foldl(
        fun(Arg, {ArgRefs, ThisState}) ->
            NewState = statement_from_statement(Arg, ThisState#clause_state{reference = none}),
            {[NewState#clause_state.reference | ArgRefs], NewState}
        end,
        {[], State}, Args
    ),
    case Module:transpile(FAtom, lists:reverse(BwdArgRefs), ArgState) of
        X = #clause_state{} -> X;
        X -> instr(ArgState, X)
    end;
statement_from_statement({record_field, _L, Object, _RecordAtom, {atom, _LL, SlotAtom}}, State) ->
    IntermediateState = statement_from_statement(Object, State),
    instr(IntermediateState, [reference(IntermediateState), ".1.", atom_to_list(SlotAtom)]);
statement_from_statement({match, _L, LHS, RHS}, State) ->
    RHSState = statement_from_statement(RHS, State),
    destructure_lhs(LHS, RHSState).

%% XLS requires all branches of an expression to have one type.  This is the
%% directly representable subset of Erlang case: a boolean scrutinee, two
%% unguarded branches, and branch-local bindings whose final expressions have
%% the same XLS type.  This subset does not implement Erlang's rule for a
%% variable bound in every branch to become available after the case, so each
%% branch is emitted as its own lexical block.
lower_boolean_case(Condition, Clauses, State0) ->
    {TrueBody, FalseBody} = boolean_case_bodies(Clauses),
    ConditionState = statement_from_statement(
        Condition,
        State0#clause_state{reference = none}
    ),
    BranchBase = ConditionState#clause_state{
        statements = [],
        reference = none
    },
    TrueState = lower_expression_sequence(TrueBody, BranchBase),
    FalseState = lower_expression_sequence(FalseBody, BranchBase),
    AnonymousCounter = erlang:max(
        TrueState#clause_state.anonymous_counter,
        FalseState#clause_state.anonymous_counter
    ),
    CaseMatchCounter = erlang:max(
        TrueState#clause_state.match_counter,
        FalseState#clause_state.match_counter
    ) + 1,
    BaseCounters = BranchBase#clause_state.named_counters,
    MergedState = ConditionState#clause_state{
        anonymous_counter = AnonymousCounter,
        match_counter = CaseMatchCounter,
        reference = none
    },
    CaseState = instr(MergedState, [
        "if ", reference(ConditionState), " {\n",
        xls_parse_io:indent(print(
            lists:reverse(TrueState#clause_state.statements)
        ), 2),
        "  (", reference(TrueState), ", ", mismatch_expression(
            TrueState#clause_state.named_counters,
            BaseCounters
        ), ")\n",
        "} else {\n",
        xls_parse_io:indent(print(
            lists:reverse(FalseState#clause_state.statements)
        ), 2),
        "  (", reference(FalseState), ", ", mismatch_expression(
            FalseState#clause_state.named_counters,
            BaseCounters
        ), ")\n",
        "}"
    ]),
    CaseReference = reference(CaseState),
    MatchBase = "case_match_" ++ integer_to_list(CaseMatchCounter),
    {ExpectedName, ExpectedState} = uniquify(CaseState, MatchBase),
    {ActualName, ActualState} = uniquify(ExpectedState, MatchBase),
    ActualState#clause_state{
        reference = [CaseReference, ".0"],
        statements = [
            ["let ", ActualName, " = ", CaseReference, ".1;\n"],
            ["let ", ExpectedName, " = bool:false;\n"]
            | ActualState#clause_state.statements
        ]
    }.

boolean_case_bodies(Clauses) ->
    case lists:foldl(
        fun
            ({clause, _Line, [{atom, _PatternLine, true}], [], Body},
                    {none, False}) ->
                {Body, False};
            ({clause, Line, [{atom, _PatternLine, true}], [], _Body},
                    {_True, _False}) ->
                error({duplicate_xls_boolean_case_branch, Line, true});
            ({clause, _Line, [{atom, _PatternLine, false}], [], Body},
                    {True, none}) ->
                {True, Body};
            ({clause, Line, [{atom, _PatternLine, false}], [], _Body},
                    {_True, _False}) ->
                error({duplicate_xls_boolean_case_branch, Line, false});
            (Clause, _Bodies) ->
                error({unsupported_xls_case_clause, Clause})
        end,
        {none, none},
        Clauses
    ) of
        {none, _} -> error({missing_xls_boolean_case_branch, true});
        {_, none} -> error({missing_xls_boolean_case_branch, false});
        Bodies -> Bodies
    end.

lower_expression_sequence(Expressions, State0) ->
    lists:foldl(
        fun(Expression, State) ->
            statement_from_statement(
                Expression,
                State#clause_state{reference = none}
            )
        end,
        State0,
        Expressions
    ).

-spec mismatch_expression(map(), map()) -> printable().
mismatch_expression(Counters, Baseline) ->
    [
        [
            [
                "(", counter_name(Key), "_1 != ", counter_name(Key), "_",
                integer_to_list(Index), ") || "
            ]
            || Index <- rebound_indexes(
                maps:get(Key, Baseline, 0),
                Final
            )
        ]
        || Key := Final <- Counters
    ] ++ ["bool:false"].

rebound_indexes(Baseline, Final) ->
    First = erlang:max(2, Baseline + 1),
    case First =< Final of
        true -> lists:seq(First, Final);
        false -> []
    end.

counter_name(Key) when is_atom(Key) ->
    atom_to_list(Key);
counter_name(Key) ->
    Key.

-spec record_value(atom(), ir(), clause_state()) -> iolist().
record_value(NameAtom, Struct, #clause_state{state_name = NameAtom}) ->
    ["(Tag::", string:uppercase(atom_to_list(NameAtom)), ", ", Struct, ")"];
record_value(NameAtom, Struct, _State) ->
    [
        "(Tag::", string:uppercase(atom_to_list(NameAtom)), ", ", Struct, ", ",
        "bits_from_", lists:delete($_, atom_to_list(NameAtom)), "(", Struct, "))"
    ].

-spec destructure_lhs(erl_parse:af_pattern(), clause_state()) -> clause_state().
-doc """
Converts an assignment from an opaque RHS to a structured LHS into a sequence of
accessors into the RHS being assigned to slots inside of the LHS.
""".
destructure_lhs({var, _L, NameAtom}, State) ->
    %% TODO: need to record time-order data to report correct error
    %% TODO: also want to report eg line number on error, other present state
    {Name, NewState} = uniquify(State, NameAtom),
    RHS = NewState#clause_state.reference,
    Bind = ["let ", Name, " = ", RHS, ";\n"],
    NewState#clause_state{statements = [Bind | NewState#clause_state.statements]};
destructure_lhs({record, _L, _Atom, Slots}, State) ->
    RecordRef = State#clause_state.reference,
    IntermediateState = lists:foldl(
        fun({record_field, _1, {atom, _2, SlotAtom}, LHS}, ThisState) ->
            Slot = atom_to_list(SlotAtom),
            Substate = ThisState#clause_state{reference = [RecordRef, ".", Slot]},
            destructure_lhs(LHS, Substate)
        end,
        State, Slots
    ),
    IntermediateState#clause_state{reference = RecordRef};
destructure_lhs({tuple, _L, Slots}, State) ->
    TupleRef = State#clause_state.reference,
    IntermediateState = lists:foldl(
        fun({Index, LHS}, ThisState) ->
            Substate = ThisState#clause_state{
                reference = [TupleRef, ".", integer_to_list(Index)]
            },
            destructure_lhs(LHS, Substate)
        end,
        State,
        lists:enumerate(0, Slots)
    ),
    IntermediateState#clause_state{reference = TupleRef};
%% constant cases
destructure_lhs({atom, _L, Atom}, State) when Atom == true orelse Atom == false ->
    EncodedValue = case Atom of
        true -> "bool:1";
        false -> "bool:0"
    end,
    #clause_state{match_counter = OldMatchCounter} = State,
    MatchCounter = OldMatchCounter + 1,
    CounterState = State#clause_state{match_counter = MatchCounter},

    BaseName = "static_match_" ++ integer_to_list(MatchCounter),
    {StaticName, StaticState} = uniquify(CounterState, BaseName),
    {RHSName, RHSState} = uniquify(StaticState, BaseName),

    RHSValue = RHSState#clause_state.reference,

    RHSState#clause_state{
        reference = RHSName,
        statements = [
            ["let ", RHSName, " = ", RHSValue, " ;\n"],
            ["let ", StaticName, " = ", EncodedValue, " ;\n"]
            | CounterState#clause_state.statements
    ]}.
%% TODO: tuple
%% TODO: badmatch on constant

%%%
%%% Erlang record / XLS struct munging.
%%%
%%% XLS does not support `(struct) as bits` and `(bits) as struct` conversions,
%%% so we have to emit manual un/packers.
%%%

-spec struct_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Translates an Erlang record definition to an XLS struct definition.".
struct_from_record(RecordForm) ->
    {attribute, _L, record, {NameAtom, Fields}} = RecordForm,
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["struct ", StructName, " {\n",
        [io_lib:format("  ~w : ~s,~n", [
                element(3, element(3, Field)),
                xls_type:print_type(xls_type:descriptor(Type))
            ])
            ||  {typed_record_field, Field, Type} <- Fields
        ],
    "}\n"].

-spec structfrombits_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Builds an XLS-side unpacker for the Erlang record definition.".
structfrombits_from_record(RecordForm) ->
    {attribute, _L, record, {NameAtom, Fields}} = RecordForm,
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["fn ", string:lowercase(StructName), "_from_bits<N: u32>(raw: bits[N]) -> ", StructName, " {\n",
    "  ", StructName, " {\n",
    lists:reverse(element(1, lists:foldl(
        fun(
            {typed_record_field, Field, Type},
            {Body, Offset}
        ) ->
            Slot = record_field_name(Field),
            Descriptor = xls_type:descriptor(Type),
            NextOffset = Offset + xls_type:width(Descriptor),
            Line = io_lib:format(
                "    ~w: raw[~w:~w] as ~s,~n",
                [
                    Slot,
                    Offset,
                    NextOffset,
                    xls_type:print_type(Descriptor)
                ]
            ),
            {[Line | Body], NextOffset}
        end,
        {[], 0}, Fields
    ))),
    "  }\n",
    "}\n"].

-spec bitsfromstruct_from_record(erl_parse:af_record_decl()) -> iolist().
-doc "Builds an XLS-side packer for the Erlang record definition.".
bitsfromstruct_from_record(_RecordForm = {attribute, _L, record, {NameAtom, Fields}}) ->
    Name = lists:delete($_, atom_to_list(NameAtom)),
    StructName = string:titlecase(Name),
    ["fn bits_from_", string:lowercase(StructName), "(s: ", StructName, ") -> bits[bit_count<", StructName, ">()] {\n",
        ["  ", lists:foldl(
            fun({typed_record_field, Field, Type}, Body) ->
                Slot = record_field_name(Field),
                Line = io_lib:format("(s.~w as bits[~w]) ++ ", [Slot, xls_type:width(xls_type:descriptor(Type))]),
                [Line | Body]  % implicit lists:reverse with this join order
            end,
            [" zero!<bits[0]>()\n"], Fields
        )],
    "}\n"].

-spec record_width(erl_parse:af_record_decl()) -> non_neg_integer().
-doc "Calculates the packed width of an Erlang record's XLS struct.".
record_width({attribute, _L, record, {_NameAtom, Fields}}) ->
    lists:sum([
        xls_type:width(xls_type:descriptor(Type))
        || {typed_record_field, _Field, Type} <- Fields
    ]).

-spec record_field_name(erl_parse:af_record_field()) -> atom().
-doc "Extracts a field name from record declarations with or without a default.".
record_field_name({record_field, _L, {atom, _AtomL, Name}}) ->
    Name;
record_field_name({record_field, _L, {atom, _AtomL, Name}, _Default}) ->
    Name.

-spec validate_record_defaults(erl_parse:af_record_decl()) -> ok.
-doc """
Requires every field in a translated record to use the type-directed
`xls_type:zero()` marker, keeping Erlang defaults consistent with XLS `zero!`.
""".
validate_record_defaults({attribute, _L, record, {RecordName, Fields}}) ->
    lists:foreach(
        fun({
            typed_record_field,
            {record_field, Line, {atom, _AtomLine, FieldName}, Default},
            _Type
        }) ->
            case is_zero_default(Default) of
                true -> ok;
                false ->
                    error({invalid_xls_record_default, RecordName, FieldName, Line})
            end;
           ({
            typed_record_field,
            {record_field, Line, {atom, _AtomLine, FieldName}},
            _Type
        }) ->
            error({missing_xls_record_default, RecordName, FieldName, Line});
           (Field) ->
            error({untyped_xls_record_field, RecordName, Field})
        end,
        Fields
    ),
    ok.

-spec is_zero_default(erl_parse:abstract_expr()) -> boolean().
-doc "Recognizes the type-directed zero marker in a record declaration.".
is_zero_default({
    call,
    _Line,
    {remote, _RemoteLine, {atom, _ModuleLine, xls_type}, {atom, _NameLine, zero}},
    []
}) ->
    true;
is_zero_default(_Default) ->
    false.

%%%
%%% clause_state utilities
%%%

-spec anonymous_variable(clause_state()) -> {clause_state(), VarName :: string()}.
anonymous_variable(State = #clause_state{anonymous_counter = Counter}) ->
    {State#clause_state{anonymous_counter = Counter + 1}, [$_ | integer_to_list(Counter)]}.

-spec get_name(clause_state(), atom()) -> string().
-doc "Maps Erlang variable names onto emitted XLS names.".
get_name(_State, Name) ->
    %% The suffix avoids collisions with names hard-coded into the template
    %% (e.g., state and request). DSLX identifiers are case-sensitive, so keep
    %% the Erlang spelling instead of conflating variables such as Foo and FOO.
    atom_to_list(Name) ++ "_1".

-spec uniquify(clause_state(), atom() | string()) ->
    {string(), clause_state()}.
-doc "Rewrites NameAtom in a way that guarantees no collision with previous uses.".
uniquify(State, NameAtom) when is_atom(NameAtom) ->
    Name = atom_to_list(NameAtom),
    uniquify(State, Name);
uniquify(State = #clause_state{named_counters = Counters}, Name) ->
    Counter = maps:get(Name, Counters, 0) + 1,
    NamedCounters = Counters#{Name => Counter},
    NewName = Name ++ [$_ | integer_to_list(Counter)],
    {NewName, State#clause_state{named_counters = NamedCounters}}.

-spec reference(clause_state()) -> none | ir().
reference(ClauseState) ->
    ClauseState#clause_state.reference.

-spec reference(clause_state(), ir()) -> clause_state().
reference(ClauseState, Reference) ->
    ClauseState#clause_state{reference = Reference}.

-spec instr(clause_state(), ir()) -> clause_state().
instr(#clause_state{anonymous_counter = Counter} = ClauseState, Expr) ->
    instr(
        ClauseState#clause_state{anonymous_counter = Counter + 1},
        [$_ | integer_to_list(Counter)],
        Expr
    ).

-spec instr(clause_state(), ir(), ir()) -> clause_state().
instr(ClauseState, Place, Expr) ->
    % TODO: we should admit structured `Place`s in reference and print them in statements
    ClauseState#clause_state{
        reference = Place,
        statements = [["let ", Place, " = ", Expr, ";\n"] | ClauseState#clause_state.statements]
    }.

%%%
%%% Dictionaries for built-in calls
%%%

-spec op(Op :: atom(), Args :: [any()]) -> iolist().
-doc "Translates a built-in Erlang op to an XLS op.".
op('+', [Left, Right]) -> [Left, " + ", Right];
op('-', [Left, Right]) -> [Left, " - ", Right];
op('*', [Left, Right]) -> [Left, " * ", Right];
op('div', [Left, Right]) -> [Left, " / ", Right];
op('bsl', [Left, Right]) -> [Left, " << ", Right];
op('bsr', [Left, Right]) -> [Left, " >> ", Right];
op('band', [Left, Right]) -> [Left, " & ", Right];
op('bor', [Left, Right]) -> [Left, " | ", Right];
op('bxor', [Left, Right]) -> [Left, " ^ ", Right];
op('bnot', [Operand]) -> ["!", Operand];
op('not', [Operand]) -> ["!", Operand];
op('<', [Left, Right]) -> [Left, " < ", Right];
op('=<', [Left, Right]) -> [Left, " <= ", Right];
op('>', [Left, Right]) -> [Left, " > ", Right];
op('>=', [Left, Right]) -> [Left, " >= ", Right];
op('=:=', [Left, Right]) -> [Left, " == ", Right];
op('=/=', [Left, Right]) -> [Left, " != ", Right];
op('andalso', [Left, Right]) -> [Left, " && ", Right];
op('orelse', [Left, Right]) -> [Left, " || ", Right].

%%%
%%% Search / selection tools
%%%

-spec init([erl_parse:abstract_form()]) -> erl_parse:af_clause().
-doc "Picks out the init/1 function from the set of Forms.".
init(Forms) ->
    [Value] = find_function(Forms, init, 1),
    [Value].

-spec state([erl_parse:abstract_form()]) -> atom().
-doc "Finds the record name which carries an actor's rich data value.".
state(Forms) ->
    case find_optional_attribute(Forms, xls_data) of
        {ok, DataAtom} ->
            DataAtom;
        none ->
            inferred_state(Forms)
    end.

inferred_state(Forms) ->
    InitSpec = find_spec(Forms, init, 1),
    {attribute, _1, spec, {
        {init, 1},
        [{type, _2, 'fun', [
            _3,
            {type, _4, record, [{atom, _5, StateAtom}]}
        ]}]
    }} = InitSpec,
    StateAtom.

-spec find_record([erl_parse:abstract_form()], atom()) -> erl_parse:af_record_decl().
-doc "Find the record definition with the indicated name from the set of Forms.".
find_record(Forms, Name) ->
    {value, Record} = lists:search(
        fun ({attribute, _L, record, {NameAtom, _Fields}}) -> NameAtom == Name;
            (_) -> false
        end, Forms
    ),
    Record.

-spec find_function([erl_parse:abstract_form()], atom(), integer()) -> erl_parse:af_clause_seq().
-doc "Find the function definition with the indicated F/A from the set of Forms.".
find_function(Forms, F, A) ->
    {value, {function, _LineNo, F, A, Clauses}} = lists:search(
        fun ({function, _LineNo, FF, AA, _Clauses}) ->
                F == FF andalso A == AA;
            (_) -> false
        end,
        Forms
    ),
    Clauses.

-spec find_attribute([erl_parse:abstract_form()], atom()) -> erl_parse:af_wild_attribute().
-doc "Finds the attribute with the indicated name from the set of Forms.".
find_attribute(Forms, Atom) ->
    {value, {attribute, _L, _A, Value}} = lists:search(
        fun ({attribute, _L, A, _Value}) -> A == Atom;
            (_) -> false
        end,
        Forms
    ),
    Value.

-spec find_optional_attribute([erl_parse:abstract_form()], atom()) ->
    none | {ok, term()}.
find_optional_attribute(Forms, Atom) ->
    case lists:search(
        fun
            ({attribute, _Line, Name, _Value}) -> Name =:= Atom;
            (_Form) -> false
        end,
        Forms
    ) of
        {value, {attribute, _Line, Atom, Value}} -> {ok, Value};
        false -> none
    end.

-spec find_spec([erl_parse:abstract_form()], atom(), integer()) -> erl_parse:af_function_spec().
-doc "Finds the function type declaration with the given F/A from the set of Forms.".
find_spec(Forms, F, A) ->
    {value, Spec} = lists:search(
        fun ({attribute, _LineNo, spec, {{FF, AA}, _Data}}) ->
                F == FF andalso A == AA;
            (_) -> false
        end,
        Forms
    ),
    Spec.

%%%
%%% Other utilities
%%%

-spec parse_file(string()) -> [erl_parse:abstract_form()].
-doc "Helper routine for reading an entire .erl source file into memory.".
parse_file(Filename) ->
    {ok, Epp} = epp:open([{name, Filename}]),
    try
        {ok, epp:parse_file(Epp)}
    after
        epp:close(Epp),
        err
    end.
