%%%% xls_statem_codegen
%%%%
%%%% Renders the closed XLS state-machine representation prepared by
%%%% xls_parse.  Erlang syntax and the parser's intermediate representation do
%%%% not cross this module boundary.

-module(xls_statem_codegen).
-moduledoc false.

-export([emit/1]).
-export_type([spec/0]).

-type lowered_clause() :: #{
    body := iodata(),
    result := iodata()
}.
-type spec() :: #{
    source := file:filename(),
    capacity := 1..255,
    phases := [atom(), ...],
    message_name := atom(),
    data_name := atom(),
    record_declarations := iodata(),
    init := lowered_clause(),
    transition := lowered_clause()
}.

-spec emit(spec()) -> iolist().
emit(Spec) ->
    [
        preamble(Spec),
        maps:get(record_declarations, Spec),
        machine_declarations(Spec),
        initial_machine(Spec),
        dispatch(Spec),
        service(Spec),
        top()
    ].

%%%
%%% Module declarations
%%%

preamble(#{
    source := Source,
    capacity := Capacity,
    phases := Phases,
    message_name := MessageName,
    data_name := DataName
}) ->
    [
        "// ", Source, ".x\n",
        """
        // This file is auto-generated by xls_parse. Manual changes will be
        // overwritten the next time it is generated.

        import axis;

        const MAILBOX_CAPACITY = u8:
        """,
        integer_to_list(Capacity),
        ";\n\n",
        "pub enum Tag : u8 {\n",
        "  NONE = u8:0,\n",
        "  ERROR = u8:1,\n",
        "  ", uppercase(DataName), " = u8:2,\n",
        "  ", uppercase(MessageName), " = u8:3,\n",
        "}\n\n",
        phase_declaration(Phases),
        "enum Directive : u2 {\n",
        "  CONSUME = u2:0,\n",
        "  POSTPONE = u2:1,\n",
        "  FAIL = u2:2,\n",
        "}\n\n"
    ].

phase_declaration(Phases) ->
    [
        "enum Phase : u8 {\n",
        [
            [
                "  ", uppercase(Name), " = u8:", integer_to_list(Index),
                ",\n"
            ]
            || {Index, Name} <- lists:enumerate(0, Phases)
        ],
        "}\n\n"
    ].

machine_declarations(#{
    capacity := Capacity,
    message_name := MessageName,
    data_name := DataName
}) ->
    MessageStruct = record_struct_name(MessageName),
    DataStruct = record_struct_name(DataName),
    [
        "struct MailboxSlot {\n",
        "  postponed: u1,\n",
        "  blocked_phase: Phase,\n",
        "  message: ", MessageStruct, ",\n",
        "}\n\n",
        "struct Machine {\n",
        "  phase: Phase,\n",
        "  data: ", DataStruct, ",\n",
        "  slots: MailboxSlot[", integer_to_list(Capacity), "],\n",
        "  occupied: u8,\n",
        "  boot_pending: u1,\n",
        "  boot: ", MessageStruct, ",\n",
        "  // Reserves one queue slot for the frame being assembled.\n",
        "  admission_pending: u1,\n",
        "  // A failed service ignores input until reset.\n",
        "  failed: u1,\n",
        "}\n\n"
    ].

%%%
%%% Lowered callbacks
%%%

initial_machine(#{init := #{body := Body, result := Result}}) ->
    [
        "fn initial_machine() -> Machine {\n",
        Body,
        "  ", Result, "\n",
        "}\n\n"
    ].

dispatch(#{
    message_name := MessageName,
    data_name := DataName,
    transition := #{body := Body, result := Result}
}) ->
    MessageStruct = record_struct_name(MessageName),
    DataStruct = record_struct_name(DataName),
    [
        "fn dispatch(message: ", MessageStruct, ", phase: Phase, data: ",
        DataStruct, ") -> (axis::Frame, Phase, ", DataStruct,
        ", Directive) {\n",
        Body,
        "  ", Result, "\n",
        "}\n\n"
    ].

%%%
%%% Bounded scheduler
%%%

service(#{capacity := Capacity, message_name := MessageName}) ->
    MessageTag = uppercase(MessageName),
    MessageCodec = record_function_name(MessageName),
    #{
        eligible_bindings := EligibleBindings,
        found_expression := FoundExpression,
        selected_expression := SelectedExpression,
        compaction_bindings := CompactionBindings,
        compacted_array := CompactedArray,
        unblocked_array := UnblockedArray
    } = queue_expansion(Capacity),
    [
        "proc Service {\n",
        "  req_in: chan<axis::Frame> in;\n",
        "  resp_out: chan<axis::Frame> out;\n",
        "  admission_out: chan<u1> out;\n\n",
        "  config(req_in: chan<axis::Frame> in,\n",
        "         resp_out: chan<axis::Frame> out,\n",
        "         admission_out: chan<u1> out) {\n",
        "    (req_in, resp_out, admission_out)\n",
        "  }\n\n",
        "  init { initial_machine() }\n\n",
        "  next(machine: Machine) {\n",
        "    if machine.boot_pending {\n",
        "      let response = axis::pack(Tag::", MessageTag,
        " as u8, bits_from_", MessageCodec, "(machine.boot));\n",
        "      send(join(), resp_out, response);\n",
        "      Machine { boot_pending: u1:0, ..machine }\n",
        "    } else if machine.failed {\n",
        "      machine\n",
        "    } else {\n",
        "      let (tok, frame, received) = recv_if_non_blocking(\n",
        "        join(), req_in, machine.admission_pending,\n",
        "        zero!<axis::Frame>());\n",
        "      let tag_ok = frame.header.op == (Tag::", MessageTag,
        " as u8);\n",
        "      let accepted = received && tag_ok;\n",
        "      let invalid_input = received && !tag_ok;\n",
        "      let incoming = ", MessageCodec,
        "_from_bits(frame.payload);\n",
        "      let incoming_slot = MailboxSlot {\n",
        "        message: incoming,\n",
        "        ..zero!<MailboxSlot>()\n",
        "      };\n",
        "      let admitted_slots = if accepted {\n",
        "        update(machine.slots, machine.occupied as u32, incoming_slot)\n",
        "      } else { machine.slots };\n",
        "      let admitted_occupied = machine.occupied + (accepted as u8);\n",
        EligibleBindings,
        "    let found = ", FoundExpression, ";\n",
        "    let selected = ", SelectedExpression, ";\n",
        "    let message = admitted_slots[selected as u32].message;\n",
        "    let dispatchable = found && !invalid_input;\n",
        "    let (response, next_phase, next_data, directive) =\n",
        "      if dispatchable {\n",
        "        dispatch(message, machine.phase, machine.data)\n",
        "      } else {\n",
        "        (zero!<axis::Frame>(), machine.phase, machine.data,\n",
        "         Directive::CONSUME)\n",
        "      };\n",
        "    let emits = response.header.op != (Tag::NONE as u8);\n",
        "    let invalid_conclusion = dispatchable &&\n",
        "      directive != Directive::CONSUME && emits;\n",
        "    let effective = dispatchable && !invalid_conclusion;\n",
        "    let selected_slot = admitted_slots[selected as u32];\n",
        "    let postponed_slot = MailboxSlot {\n",
        "      postponed: u1:1,\n",
        "      blocked_phase: machine.phase,\n",
        "      ..selected_slot\n",
        "    };\n",
        "    let postponed_slots = update(\n",
        "      admitted_slots, selected as u32, postponed_slot);\n",
        CompactionBindings,
        "    let compacted_slots = ", CompactedArray, ";\n",
        "    let transition_slots = match directive {\n",
        "      Directive::CONSUME => compacted_slots,\n",
        "      Directive::POSTPONE => postponed_slots,\n",
        "      Directive::FAIL => admitted_slots,\n",
        "    };\n",
        "    let candidate_slots = if effective {\n",
        "      transition_slots\n",
        "    } else { admitted_slots };\n",
        "    let candidate_occupied = if effective &&\n",
        "        directive == Directive::CONSUME {\n",
        "      admitted_occupied - u8:1\n",
        "    } else { admitted_occupied };\n",
        "    let candidate_phase = if effective {\n",
        "      next_phase\n",
        "    } else { machine.phase };\n",
        "    let candidate_data = if effective {\n",
        "      next_data\n",
        "    } else { machine.data };\n",
        "    let phase_changed = candidate_phase != machine.phase;\n",
        "    let unblocked_slots = ", UnblockedArray, ";\n",
        "    let final_slots = if phase_changed {\n",
        "      unblocked_slots\n",
        "    } else { candidate_slots };\n",
        "    let should_send = effective &&\n",
        "      directive == Directive::CONSUME &&\n",
        "      emits;\n",
        "    let response_tok = send_if(\n",
        "      tok, resp_out, should_send, response);\n",
        "    let failed = invalid_input || invalid_conclusion ||\n",
        "      (effective && directive == Directive::FAIL);\n",
        "    let admission_pending = machine.admission_pending && !received;\n",
        "    // Preserve occupied + admission_pending <= MAILBOX_CAPACITY.\n",
        "    let reserve = !failed && !received && !admission_pending &&\n",
        "      candidate_occupied < MAILBOX_CAPACITY;\n",
        "    let _admission_tok = send_if(\n",
        "      response_tok, admission_out, reserve, u1:1);\n",
        "    Machine {\n",
        "      phase: candidate_phase,\n",
        "      data: candidate_data,\n",
        "      slots: final_slots,\n",
        "      occupied: candidate_occupied,\n",
        "      admission_pending: admission_pending || reserve,\n",
        "      failed,\n",
        "      ..machine\n",
        "    }\n",
        "    }\n",
        "  }\n",
        "}\n\n"
    ].

queue_expansion(Capacity) ->
    Indexes = lists:seq(0, Capacity - 1),
    EligibleBindings = [eligible_binding(Index) || Index <- Indexes],
    FoundExpression = join_with(" || ", [
        ["eligible_", integer_to_list(Index)] || Index <- Indexes
    ]),
    SelectedExpression = lists:foldr(
        fun(Index, Else) ->
            [
                "if eligible_", integer_to_list(Index), " { u8:",
                integer_to_list(Index), " } else { ", Else, " }"
            ]
        end,
        "u8:0",
        Indexes
    ),
    CompactionBindings = [
        compaction_binding(Index, Capacity) || Index <- Indexes
    ],
    CompactedArray = [
        "[",
        join_with(", ", [
            ["compacted_", integer_to_list(Index)] || Index <- Indexes
        ]),
        "]"
    ],
    UnblockedArray = [
        "[",
        join_with(",\n      ", [
            [
                "MailboxSlot { postponed: u1:0, ..candidate_slots[",
                integer_to_list(Index), "] }"
            ]
            || Index <- Indexes
        ]),
        "]"
    ],
    #{
        eligible_bindings => EligibleBindings,
        found_expression => FoundExpression,
        selected_expression => SelectedExpression,
        compaction_bindings => CompactionBindings,
        compacted_array => CompactedArray,
        unblocked_array => UnblockedArray
    }.

eligible_binding(Index) ->
    [
        "    let eligible_", integer_to_list(Index), " = u8:",
        integer_to_list(Index), " < admitted_occupied &&\n",
        "      (!admitted_slots[", integer_to_list(Index),
        "].postponed || admitted_slots[", integer_to_list(Index),
        "].blocked_phase != machine.phase);\n"
    ].

compaction_binding(Index, Capacity) when Index + 1 < Capacity ->
    [
        "    let compacted_", integer_to_list(Index), " = if u8:",
        integer_to_list(Index), " < selected {\n",
        "      admitted_slots[", integer_to_list(Index), "]\n",
        "    } else if u8:", integer_to_list(Index + 1),
        " < admitted_occupied {\n",
        "      admitted_slots[", integer_to_list(Index + 1), "]\n",
        "    } else { zero!<MailboxSlot>() };\n"
    ];
compaction_binding(Index, _Capacity) ->
    [
        "    let compacted_", integer_to_list(Index),
        " = zero!<MailboxSlot>();\n"
    ].

%%%
%%% Top-level streams
%%%

top() ->
    [
        "pub proc Top {\n",
        "  ext_recv: chan<axis::Beat> in;\n",
        "  ext_send: chan<axis::Beat> out;\n\n",
        "  config(ext_recv: chan<axis::Beat> in,\n",
        "         ext_send: chan<axis::Beat> out) {\n",
        "    let (req_p, req_c) = chan<axis::Frame, u32:1>(\"req\");\n",
        "    let (resp_p, resp_c) = chan<axis::Frame, u32:1>(\"resp\");\n",
        "    let (admit_p, admit_c) = chan<u1, u32:1>(\"admit\");\n",
        "    spawn axis::ReservedRx(ext_recv, req_p, admit_c);\n",
        "    spawn Service(req_c, resp_p, admit_p);\n",
        "    spawn axis::Tx(resp_c, ext_send);\n",
        "    (ext_recv, ext_send)\n",
        "  }\n\n",
        "  init { () }\n",
        "  next(state: ()) { state }\n",
        "}\n"
    ].

%%%
%%% Naming and iodata helpers
%%%

uppercase(Atom) ->
    string:uppercase(atom_to_list(Atom)).

record_struct_name(Atom) ->
    string:titlecase(record_function_name(Atom)).

record_function_name(Atom) ->
    lists:delete($_, atom_to_list(Atom)).

join_with(_Separator, []) ->
    [];
join_with(Separator, [First | Rest]) ->
    [First | [[Separator, Item] || Item <- Rest]].
